### ISSUE TITLE
Would picking up a syntax like in http-rewrite-middleware work?

### ISSUE THREAD

**Issue by chimurai** [chimurai/http-proxy-middleware#100]
Copied from https://github.com/chimurai/http-proxy-middleware/issues/52#issuecomment-241489572: (@Lalem001)

Would picking up a syntax like in [http-rewrite-middleware](https://www.npmjs.com/package/http-rewrite-middleware) work?

Example from their docs:

```js
var rewriteMiddleware = rewriteModule.getMiddleware([
    // Internal rewrite 
    {from: '^/index_dev.html$', to: '/src/index.html'},
    // Internal rewrite 
    {from: '^/js/(.*)$', to: '/src/js/$1'},
    // 301 Redirect 
    {from: '^/old-stuff/(.*)$', to: '/new-cool-stuff/$1', redirect: 'permanent'},
    // 302 Redirect 
    {from: '^/stuff/(.*)$', to: '/temporary-stuff/$1', redirect: 'temporary'}
]);
```

Having the paths in an array like this would guarantee order, and you can apply each rule in succession.

Thoughts?

P.S. I am actually using `http-rewrite-middleware` in my own projects, but it interferes with the operation of `http-proxy-middleware@>=0.14.0` somehow.

**Comment by chimurai** [comment]
@Lalem001 Can you elaborate on:
> Would picking up a syntax like in http-rewrite-middleware work?

Did you try the latest [http-proxy-middleware `v0.17.1`](https://github.com/chimurai/http-proxy-middleware/releases/tag/v0.17.1)?

It fixed a rewrite bug; Perhaps it solves the interference with `http-rewrite-middleware` too...

**Comment by Lalem001** [comment]
@chimurai I was under the impression in #52 that the OP, or you, were looking for a way to continue matching rewrite rules after the first match and have the rules be match in a specific order. So I was pointing out something that I have seen elsewhere that could potentially work.

**Comment by chimurai** [comment]
Ah... thanks for clearing up.

The discussion in #52 was about the behavior of the `pathRewrite` and its documentation.
When I implemented it, I didn't really foresee complicated path rewrites...

To fix this; PR https://github.com/chimurai/http-proxy-middleware/pull/74 introduced a custom function for `pathRewrite` to give the developer full control on path rewrite. (Without changing the behavior)

Suggestions to improve the API are really appreciated. If the community really wants some syntax sugar like the one used in `http-rewrite-middleware`. Please let me know by some votes :+1: 

IMHO, the custom `pathRewrite` function pretty much handles every use-case.
