### ISSUE TITLE
Circular dependency of build

### ISSUE THREAD

**Issue by Juansasa** [chimurai/http-proxy-middleware#1007]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

Got this error while compiling with Rollup

`node_modules/http-proxy-middleware/dist/index.js -> node_modules/http-proxy-middleware/dist/legacy/index.js -> node_modules/http-proxy-middleware/dist/legacy/public.js -> node_modules/http-proxy-middleware/dist/legacy/create-proxy-middleware.js -> node_modules/http-proxy-middleware/dist/index.js`

### Step-by-step reproduction instructions

```shell
Build with rollup + typescript
```

### Expected behavior (be clear and concise)

More consistent `dist` import termination

### How is http-proxy-middleware used in your project?

```shell
express proxy middleware
```

### What http-proxy-middleware configuration are you using?

```typescript
server.use(
  createProxyMiddleware({
    pathFilter: "/api",
    changeOrigin: true,
    secure: false,
    target: process.env.API,
    pathRewrite: {
      "^/api/": "/internal/endpoint/",
    },
    logger: console,
  }),
);
```

### What OS/version and node/version are you seeing the problem?

```shell
Mac OSX 14.4.1
Node v21.7.2
```

**Comment by chimurai** [comment]
Thanks for reporting @Juansasa 

Am able to confirm the circular dependencies:

```
npx madge --circular src/index.ts
```

<img width="931" alt="image" src="https://github.com/chimurai/http-proxy-middleware/assets/655241/8e127061-78cd-4d37-85ce-f0d0effcfd61">
