### ISSUE TITLE
The coverage directory is included in 0.17.1 

### ISSUE THREAD

**Issue by graingert** [chimurai/http-proxy-middleware#102]
The coverage directory is included in 0.17.1 https://registry.npmjs.org/http-proxy-middleware/-/http-proxy-middleware-0.17.1.tgz

**Comment by chimurai** [comment]
Thanks for reporting it. I noticed this too.

It is already fixed in: https://github.com/chimurai/http-proxy-middleware/commit/f670d6e08a5ac378f96fa8ab755b11da8d490859

Haven't pushed a new version to make it effective.

**Comment by SpaceK33z** [comment]
I'd recommend to use the `files` option in `package.json` to whitelist what you want to include instead. This will probably happen again in the future when you add a new folder / change a folders name.

**Comment by chimurai** [comment]
Thanks for the tip @SpaceK33z! Didn't know about `files` option.
Much nicer compared to `.npmignore`
