### ISSUE TITLE
Expected path behavior?

### ISSUE THREAD

**Issue by etrom** [chimurai/http-proxy-middleware#103]
### Expected behavior
Can't seem to use any paths containing ** in conjunction with any others. For ex: 
these work:
`proxyMiddleware(['/api', '/login']);`
`proxyMiddleware(['**']);`
`proxyMiddleware(['/api/**']);`

this does not: 
`proxyMiddleware(['/api/**', '/login']);`

throws error:
` [HPM] Invalid context. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]`

The rest of my config looks identical to the docs, kind of just wondering if this is intentional behavior?

**Comment by chimurai** [comment]
It's definitely implemented intentionally. The current implementation might be sub-optimal and it's something on my list to improve, along with some better documentation. 

Some background info on context matching.
Basically it has 3 modi:

1. string matching (`.indexOf()`), reads like: _paths starting with ..._
2. wildcard/glob matching (using `micromatch`)
3. custom matching function (`Function` returning a `boolean`)

---

The logic in [context-matcher.js#L23](https://github.com/chimurai/http-proxy-middleware/blob/8fe60080d2dd91e063913600896cc08424967336/lib/context-matcher.js#L23) is preventing mixed usage glob and non-glob patterns.

Say the following config `proxyMiddleware(['/api/**', '/login']);` would be allowed and the matching is handled by `micromatch`; It would match:
- any path starting with `/api/`
- exactly `/login` ; `/login/foo` and `/login/bar` won't get matched.

Curious to hear how you interpret the following config:
```javascript
proxyMiddleware(['/api/**', '/login']);
```

**Comment by chimurai** [comment]
Closing issue due lack of response. Feel free to re-open issue.

**Comment by gregmac** [comment]
Just ran into this, and it took a while to figure out what was going on.

Reading this it makes total sense, but it would be nice if there was a better error message explaining it, instead of just:
```
Invalid context. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]
```
