### ISSUE TITLE
What happen if the proxied api has dependency?

### ISSUE THREAD

**Issue by iroy2000** [chimurai/http-proxy-middleware#104]
Currently I have an 2 api, but actually the second api depends on a response from the first api.  And right now I need to do that from the client side which I would love to know if there is a way to simplified it.   ( E.g. my first api could be getting a token to append to the second api )

```javascript

const moreProxy = proxy(config.get('more.apiUrl'), {
  changeOrigin: true,
  logLevel: 'debug',
});


const fancyProxy = proxy(config.get('fancy.apiUrl'), {
  changeOrigin: true,
  logLevel: 'debug',
});

router.use('/api/more',  moreProxy);

router.use('/api/fancy', fancyProxy);

```

So instead of having two routes, how can I make it only one route, so that I call the first api, only when it is done, it will call the second api ??

For example, something like the following could be possible ??

```javascript
router.use('/api/fancy', moreProxy, fancyProxy);
```

**Comment by chimurai** [comment]
Can you provide the static values for the following to get a better picture of what you are trying to achieve?

`config.get('more.apiUrl')`
`config.get('fancy.apiUrl')`

**Comment by chimurai** [comment]
Closing issue due lack of response. Feel free to re-open issue.
