### ISSUE TITLE
Responsible Vulnerability Disclosure

### ISSUE THREAD

**Issue by mhassan1** [chimurai/http-proxy-middleware#1042]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

I would like to report a security vulnerability in all versions of `http-proxy-middleware`. What is the best way to report this to you responsibly?

### Step-by-step reproduction instructions

```shell
TBA
```

### Expected behavior (be clear and concise)

TBA

### How is http-proxy-middleware used in your project?

```shell
TBA
```

### What http-proxy-middleware configuration are you using?

```typescript
TBA
```

### What OS/version and node/version are you seeing the problem?

```shell
TBA
```

**Comment by chimurai** [comment]
hi @mhassan1,

you can send the details to: <http_proxy_middleware at o u t l o o k dot c o m>

**Comment by mhassan1** [comment]
@chimurai Sent!
