### ISSUE TITLE
Can you help / document webpack configuration

### ISSUE THREAD

**Issue by pgangwani** [chimurai/http-proxy-middleware#105]
### Expected behaviour
proxying : /api/users/1 to http://jsonplaceholder.typicode.com/users/1

### Actual behavior
returns 404 with below configuration , I suspect pathRewrite doesnt work, it passess http://jsonplaceholder.typicode.com/api/users/1
 instead of 
http://jsonplaceholder.typicode.com/users/1

* "webpack": "2.1.0-beta.6",

#### proxy middleware configuration in webpack 👎 
```javascript
        proxy: [{
            path: `/api/**`,
            target: "http://jsonplaceholder.typicode.com",
            changeOrigin: true,
            pathRewrite: { '^/api': '' },
            logLevel: 'info',
        }]
```

Could you please help me and/ document these stuff as you guys added for browsersyn,connect etc.
Would be great help.

**Comment by chimurai** [comment]
Not sure where you got the `Array` and `path` config from.
Certainly not part of http-proxy-middleware.

From their documentation the proxy config should look like this:
```javascript
proxy: {
  '/api': {
    target: 'https://other-server.example.com',
    pathRewrite: {'^/api' : ''}
  }
}
```
More info: http://webpack.github.io/docs/webpack-dev-server.html#rewriting-urls-of-proxy-request

**Comment by pgangwani** [comment]
Certainly, I tried this also : 
`proxy: {
            '/api': {
                target: 'http://jsonplaceholder.typicode.com',
                pathRewrite: { '^/api': '' },
                 changeOrigin: true,
            }
        }`

As I said, I think pathRewrite is not working as expected.

**Comment by chimurai** [comment]
Can you provide the log output after you've set the `logLevel` to `'debug'`?

**Comment by chimurai** [comment]
Don't think it a http-proxy-middleware issue.
You are probably mixing up `webpack` and `webpack-dev-server`.

I think StackOverflow would be a better place to troubleshoot your setup.

If you really think its a http-proxy-middleware issue/bug, please provide a minimal setup showing the issue. Feel free to re-open the issue in that case.
