### ISSUE TITLE
version 2.0.7 is not in the CHANGELOG file

### ISSUE THREAD

**Issue by JuanmaMenendez** [chimurai/http-proxy-middleware#1055]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

version 2.0.7 is not in the CHANGELOG file
https://www.npmjs.com/package/http-proxy-middleware/v/2.0.7

Please add it to know the change that were introduced.

### Step-by-step reproduction instructions

```shell
1. ...
2. ...
```

### Expected behavior (be clear and concise)

version 2.0.7 is not in the CHANGELOG file
https://www.npmjs.com/package/http-proxy-middleware/v/2.0.7

Please add it to know the change that were introduced.

### How is http-proxy-middleware used in your project?

```shell
version 2.0.7 is not in the CHANGELOG file
https://www.npmjs.com/package/http-proxy-middleware/v/2.0.7

Please add it to know the change that were introduced.
```

### What http-proxy-middleware configuration are you using?

```typescript
version 2.0.7 is not in the CHANGELOG file
https://www.npmjs.com/package/http-proxy-middleware/v/2.0.7

Please add it to know the change that were introduced.
```

### What OS/version and node/version are you seeing the problem?

```shell
version 2.0.7 is not in the CHANGELOG file
https://www.npmjs.com/package/http-proxy-middleware/v/2.0.7

Please add it to know the change that were introduced.
```

**Comment by chimurai** [comment]
Here is the change log for 2.0.7:
https://github.com/chimurai/http-proxy-middleware/blob/2.x/CHANGELOG.md
