### ISSUE TITLE
Unable to proxy root path `/` to back end server

### ISSUE THREAD

**Issue by jamesjieye** [chimurai/http-proxy-middleware#107]
### Expected behavior

When the proxy setting is like the following

```
proxy('/', {target:'http://localhost:8080'})
```

Only the request to the root path should be proxied. No other requests should be proxied. In my opinion, since the wildcard already provides the ability to match any requests, context `/` should be used to match the root path. In this way, it becomes possible for an app to proxy the root path to the back end server for rendering the initial HTML content. 

### Actual behavior

Any requests are proxied.

**Comment by jamesjieye** [comment]
A little more background detail on the use case.

I'm setting up a Spring Boot + Vue.js project and I want to proxy the root path to the back end server and use the back end server to dynamically generate the HTML which will be sent back to the client side and start loading js, css, and other assets. 

The reason to use back end server to generate the HTML dynamically is because I need to save some data to the HTML rather than to use a static HTML file. For example, I can save some logged in user's info, like name, avatar image, to save the effort of sending an additional request for that when using a static HTML file.

And that's why it is important for me to proxy the `/` to the back end server.

**Comment by chimurai** [comment]
Thanks for reporting this @jamesjieye .

Changing this will break the current behavior unfortunately, as documented here:
https://github.com/chimurai/http-proxy-middleware#context-matching

There are a couple of context matching improvements I want to make and I'll certainly consider to add this one to the list.

For now you can provide a custom function to determine when to proxy a request:

```javascript
function filter(path) {
  return path === '/';  // only proxy root path
}

proxy(filter, {target:'http://localhost:8080'});
```

**Comment by jamesjieye** [comment]
@chimurai Thanks for the tip!

The custom function is a good workaround for me.
