### ISSUE TITLE
lite-server proxy don't respond when the amount of loaded data is huge!!!

### ISSUE THREAD

**Issue by Hmizawi** [chimurai/http-proxy-middleware#115]
Hi,
This is the config of my proxy :

```javascript
var proxy = require('http-proxy-middleware');
var fallback = require('connect-history-api-fallback');

var apiProxy = proxy('/stats', {
    target: 'http://localhost:8080',
    changeOrigin: true,   // for vhosted sites,
    logLevel: 'debug'
});

var local = fallback({
	index: '/index.html', 
	verbose: true
});

module.exports = {
	injectChanges: false,
	files: [ './**/*.{html,htm,css,js}' ],
	watchOptions: { ignored: 'node_modules' },
	port : 3000,
    server: {
    	baseDir: './',
        middleware: {
            1: apiProxy,
            2: local
        }
    }
};
```

Every thing works correctly when the amount of data is not big but this is not the case  when the amount became big.
In fact the application block while loading the data despite the fact that the server respond correctly.
Thanks in advance for your help

**Comment by chimurai** [comment]
Can you specify `big`? Is it the frequency of request/responses and/or the size of the requests and responses? Please provide numbers or even better; an isolated use-case which exposes this issue.

The `http-proxy` library does the actual work of proxying the requests.
Can you verify if you have the same issue when using that library?

**Comment by Hmizawi** [comment]
What i mean by big isthe size of responses. In fact if the nomber of objects in the array returned is 30.EveryThing is oK but when this number become 400. Here i can no more control the web application which block and they show me that they are loading data  and that the operation of loading didn't finish yet.

**Comment by chimurai** [comment]
Would be nice if you can create an isolated example.
Until then, there is little I can do.

Feel free to re-open the issue when you have an example.
