### ISSUE TITLE
Question: running behind corporate http proxy

### ISSUE THREAD

**Issue by wvanderdeijl** [chimurai/http-proxy-middleware#116]
We use http-proxy-middleware to forward requests to /api/* to amazon AWS to prevent CORS issues. This works great until I run the application on my personal laptop within the corporate LAN which needs a http proxy to accept the internet (and thus Amazon AWS).

Is it possible to configure http-proxy-middleware to use a http proxy for the outbound requests it is making to Amazon AWS?

**Comment by chimurai** [comment]
There is a recipe for this:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md

**Comment by wvanderdeijl** [comment]
Thanks for the tip! I am currently out of the office with no access to the corporate proxy (which makes life so much easier), but will try this out once I'm back at the office.
