### ISSUE TITLE
Confusion around path rewrite and app.use()

### ISSUE THREAD

**Issue by ltamrazov** [chimurai/http-proxy-middleware#117]
From the example:
```javascript
var options = {
        target: 'http://www.example.org', // target host
        changeOrigin: true,               // needed for virtual hosted sites
        ws: true,                         // proxy websockets
        pathRewrite: {
            '^/old/api' : '/new/api',     // rewrite path
            '^/remove/api' : '/api'       // remove path
        },
        router: {
            // when request.headers.host == 'dev.localhost:3000',
            // override target 'http://www.example.org' to 'http://localhost:8000'
            'dev.localhost:3000' : 'http://localhost:8000'
        }
    };

// create the proxy (without context)
var exampleProxy = proxy(options);

// mount `exampleProxy` in web server
var app = express();
    app.use('/api', exampleProxy);
    app.listen(3000);
```

Judging by this example, and the path rewrite will never happen since it specified "^/old/api" and "^/remove/api" but the proxy is only set on "/api" ( app.use('/api') ) thus matching paths cannot possibly reach it. Is that understanding correct? 

The same applies to router,  multiple hosts are specified, is is assumed that the app is listening on all those hosts? 

Thank you,

**Comment by chimurai** [comment]
The `pathRewrite` example is indeed confusing and wouldn't work. Thanks for spotting this.

Changing it to this should make the example valid.
```javascript
pathRewrite: {
    '^/api/old/path' : '/api/new/path',     // rewrite path
    '^/api/remove/path' : '/api/path'       // remove path
}
```

Indeed. The app would be listening to all those hosts.
There are a couple of use cases for `router` I can think of.

One would be:
Assuming you have a local development server running on 127.0.0.0 (localhost).
And you want to be able to develop/point to different `target` servers, without changing the server/proxy configuration. `router` can be used to point to different `target` servers. For example when you're working with an API in a [DTAP](https://en.wikipedia.org/wiki/Development,_testing,_acceptance_and_production) setup.


Not sure how to improve the `router` example... Any suggestions?

**Comment by ltamrazov** [comment]
Sorry for late reply, and thank you for clarifying. Yes, the router use case makes sense. However, as far as I know, the only way to make it applicable to express, is if you have several apps. This is because (again as far as I know) a single app can listen on only one host. So you would create two apps and have them listen on different hosts, and both use the same proxy that has the router implemented in the options. 

Of course if in fact you can listen on multiple hosts in express app this is all moot, and sorry for confusion :)
