### ISSUE TITLE
File upload using proxy and express

### ISSUE THREAD

**Issue by RaghavendhraK** [chimurai/http-proxy-middleware#119]
It seems that file upload from the express app using proxy is not working.
We do have used the body parser and have not used the multer in express app.
And on file upload, the source app throws error that the file is missing.
However the file upload in source app without proxying works

It seems to be that we are missing something while uploading the file using proxy app. Could you please help with that?

Thanks,
Raghu

**Comment by chimurai** [comment]
Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.

[_How to Ask Good Coding Questions That Get Great Answers..._](http://zellwk.com/blog/asking-questions/)
