### ISSUE TITLE
Error occured while trying to proxy in demo browsersync

### ISSUE THREAD

**Issue by Danieler** [chimurai/http-proxy-middleware#120]
When i try to execute the demo of browsersync appears the error
**Error occured while trying to proxy to: localhost:8080/users**

"browser-sync": "^2.16.0",
"http-proxy-middleware": "^0.17.1"

**Comment by chimurai** [comment]
Just tested the [browser-sync proxy example](https://github.com/chimurai/http-proxy-middleware/tree/master/examples/browser-sync) without any issues:

```
$ node examples/browser-sync/
[HPM] Proxy created: /users  ->  http://jsonplaceholder.typicode.com
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[DEMO] Server: listening on port 3000
[DEMO] Opening: http://localhost:3000/users
[BS] Access URLs:
 ---------------------------------------------
       Local: http://localhost:3000/users
    External: http://192.168.168.12:3000/users
 ---------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.168.12:3001
 ---------------------------------------------
[BS] Serving files from: ./
[HPM] GET /users -> http://jsonplaceholder.typicode.com
```

Did you modified the example?

**Comment by Danieler** [comment]
Could be because im behind a corporate proxy?
i have to config something more in this case?
i didn't modified the example

**Comment by chimurai** [comment]
The corporate proxy could be the issue.
Try configuring it this way: https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md

**Comment by chimurai** [comment]
Closing issue due lack of response. Feel free to re-open issue.

**Comment by HiZhaoxiaoyang** [comment]
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md 
isn't works, 
it's nothing to do with "https".
