### ISSUE TITLE
Setting up Reverse Proxy to circument access-control-allow-origin problem

### ISSUE THREAD

**Issue by gkatsanos** [chimurai/http-proxy-middleware#124]
### Expected behavior
I am trying to setup a reverse proxy in webpack that will allow me to perform an AJAX request to a server that does not have access-control-allow-origin in its headers. 
I added 
```
  proxy: {
    '/api': {
      target: 'http://api.rottentomatoes.com',
      secure: false
    }
  },
```
to my `webpack.dev.config.js`
### Actual behavior
I make the XHR request and instead of seeing http://api.rottentomatoes.com/api/.. I see http://localhost:8080/api.. (404 NOT found)
### Setup

* http-proxy-middleware: 0.17.2
* server: express: 4.13.3
* other relevant modules:
```
    "webpack": "^1.13.2",
    "webpack-dev-middleware": "^1.8.3",
    "webpack-hot-middleware": "^2.12.2",
    "webpack-merge": "^0.14.1"
```

**Comment by chimurai** [comment]
Try adding the option `changeOrigin: true`

```javascript
  proxy: {
    '/api': {
      target: 'http://api.rottentomatoes.com',
      changeOrigin: true,
      secure: false
    }
  },
```

**Comment by gkatsanos** [comment]
I found the answer.
In fact my setup uses the proxyTable object (I am using a generator which uses its own versions of each module, and the actual configuration was not in weback.base.conf but in an index.js loaded separately.. ://

**Comment by chimurai** [comment]
Glad to hear you've found the solution.
