### ISSUE TITLE
upload file will fail when use express middleware 

### ISSUE THREAD

**Issue by zenghuiLee** [chimurai/http-proxy-middleware#125]
when use http-proxy-middleware with express,and  use express middleware to check users. when upload files throw http-proxy-middleware and get the error messages below:
**"MultipartParser.end(): stream ended unexpectedly: state = START_BOUNDARY"
name:"BadRequestError"
restCode:"BadRequestError"
statusCode:400**

when not use middleware in express,the http-proxy-middleware works ok, why? where maybe the prolems is ? 
@trbngr @klimashkin @sunnylqm @chimurai @cloudmu

**Comment by chimurai** [comment]
Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
