### ISSUE TITLE
Sending a string as JSON root in POST body proxies into plaintext

### ISSUE THREAD

**Issue by kroltan** [chimurai/http-proxy-middleware#126]
### Expected behavior

When proxying POST requests with content type `application/json` where the whole body is a string literal, the body should be untouched, or at least reinterpreted as equivalent JSON.
### Actual behavior

Somewhere in the proxy, the request body is parsed as JSON and re-emitted as a plain string, so the string `"some string value"` becomes `some string value`. The content-type is still reported as JSON. A reasonable target will then error with the fact that it's invalid JSON.
### Setup
- http-proxy-middleware: _version_
- server: _connect/express/browser-sync..._ + _version_
- other relevant modules
#### proxy middleware configuration

``` javascript
var apiProxy = proxy('http://www.example.org/api');
```
#### server mounting

``` javascript
var app = express();

app.use(apiProxy);
app.listen(3000);
```
#### send a test request

``` bash
curl 'http://localhost:3000/' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -d '"some string value"'
```

**Comment by chimurai** [comment]
Can you provide a minimal example?

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.

**Comment by contractpendev** [comment]
app.use(bodyParser.json()); This breaks the http-proxy-middleware for this case - this can cause this bug, see https://github.com/chimurai/http-proxy-middleware/issues/90

Solution is to remove app.use(bodyParser.json());
