### ISSUE TITLE
Unable to proxy requests on remote Apache Tomcat server

### ISSUE THREAD

**Issue by nitoloz** [chimurai/http-proxy-middleware#129]
### Expected behavior
I don't know it I am doing smth wrong or it's some error caused by usage of apache tomcat or whatever else.
/api requests are proxied on remote Apache tomcat server.
### Actual behavior
/api requests are not proxied on remote Apache tomcat server.
I have my UI and backend hosted on different servers and I want to proxy requests from Ui to backend.
When I start a proxy server it shows the following line that seems to be correct, however when I try to execute any of the responses they all fail with 404.
ROOT>node server.js
[HPM] Proxy created: /api  ->  http://myservice.azurewebsites.net
![http-proxy-fail](https://cloud.githubusercontent.com/assets/7154361/20611262/35d61826-b2a7-11e6-824e-b0737a75672a.png)

Am I choosing the wrong port probably? (I've taken 8080 from request url, so it seems to be correct as well).
### Setup
* browser Chrome 54.0.2840.99 m
* http-proxy-middleware: 0.17.2
* server: connect, version: 3.5.0
* other relevant modules
node -v: v7.2.0
npm -v: 3.10.9

#### proxy middleware configuration
```javascript
var http = require('http');
var connect = require('connect');
var proxy = require('http-proxy-middleware');
var apiProxy = proxy('/api', {target: 'http://myservice.azurewebsites.net', changeOrigin: true });
```
#### server mounting
```javascript
var app = connect();
app.use(apiProxy);

http.createServer(app).listen(8080)
```

**Comment by chimurai** [comment]
The [http 404](https://en.wikipedia.org/wiki/HTTP_404) probably means the proxied request url to the server is incorrect.

From your  config it seems the request to the server is: `http://myservice.azurewebsites.net/api/Account/Token`

Check if this url is correct...

**Comment by nitoloz** [comment]
@chimurai thank you for a quick reply!
I've replaced the url, cause I thought it's not that important.
The actual url is POST http://abnservice.azurewebsites.net/api/Account/Token

I'm using the http-proxy-middleware locally and it works perfectly fine, so I was surprised that it didn't work on a deploy server.

**Comment by chimurai** [comment]
Does a manual POST to http://abnservice.azurewebsites.net/api/Account/Token work?

**Comment by nitoloz** [comment]
Yes, it works fine if you are registered already with a request body parameters **email** and **password**.
You can also try  http://abnservice.azurewebsites.net/api/Account/Register to sign up with payload `{email:'some@email.com', password:'mypass'}`

**Comment by chimurai** [comment]
This minimal config works for me. So it must be something in your configuration...

```javascript
var express = require('express');
var proxy = require('http-proxy-middleware');

var app = express();

var apiProxy = proxy('/api', {
    target: 'http://abnservice.azurewebsites.net',
    changeOrigin: true,             // for vhosted sites, changes host header to match to target's host
    logLevel: 'debug'
});

app.use(apiProxy);
app.listen(3000);
```

```
$ curl --verbose --data "email=some3@email.com&password=mypass" http://localhost:3000/api/Account/Register
* timeout on name lookup is not supported
*   Trying ::1...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (::1) port 3000 (#0)
> POST /api/Account/Register HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.48.0
> Accept: */*
> Content-Length: 37
> Content-Type: application/x-www-form-urlencoded
>
} [37 bytes data]
* upload completely sent off: 37 out of 37 bytes
100    37    0     0  100    37      0     30  0:00:01  0:00:01 --:--:--    30< HTTP/1.1 200 OK
< x-powered-by: ASP.NET
< cache-control: no-cache
< pragma: no-cache
< content-length: 0
< expires: -1
< server: Microsoft-IIS/8.0
< x-aspnet-version: 4.0.30319
< set-cookie: ARRAffinity=5bd719511e04645e2f1a8be6db3a00fef2b100c847a571949f42699bacfb3a92;Path=/;Domain=abnservice.azurewebsites.net
< date: Fri, 25 Nov 2016 18:09:20 GMT
< connection: close
<
100    37    0     0  100    37      0     19  0:00:01  0:00:01 --:--:--    19
* Closing connection 0
```

**Comment by nitoloz** [comment]
Thank you very much for the investigation!
I'll try your config as well.

By the way I've noticed that http-proxy-middleware is listening to localhost by default (http://127.0.0.1), so for my config with port :8080 it will listen to http://127.0.0.1:8080, but requests on my remote server are sent to http://188.227.65.161:8080. Can this be the reason to requests not being proxied? Can I change the default host or this should not matter?

**Comment by nitoloz** [comment]
Dear @chimurai !
Thank you for suggestion to use logLevel:debug. This is what I got:
`E:\Tomcat8\webapps\ROOT>node connect.js
[HPM] Proxy created: /api  ->  http://abnservice.azurewebsites.net
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1262:14)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1376:9)
    at Object.<anonymous> (E:\Tomcat8\webapps\ROOT\connect.js:14:24)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
`

Do you have any ideas what may cause this?
Probably the reason is that my http folder in node_modules contains only package.json?

**Comment by chimurai** [comment]
> EADDRINUSE means that the port number which listen() tries to bind the server to is already in use.

Here is a nice explanation of the error: http://stackoverflow.com/a/9898697

May I close this issue? ([basic setup](https://github.com/chimurai/http-proxy-middleware/issues/129#issuecomment-263006856) works)

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.
