### ISSUE TITLE
How to keep origin header?

### ISSUE THREAD

**Issue by adamreisnz** [chimurai/http-proxy-middleware#139]
I am using the proxy for a development server but am finding that it loses the Origin header along the way. I tried to set it back manually by using the `onProxyRes` callback in the options, but that didn't seem to work.

Any thoughts on how I can keep the origin header on the forwarded request?

**Comment by chimurai** [comment]
Sounds very similar to https://github.com/facebookincubator/create-react-app/pull/1212

[`http-proxy`](https://github.com/nodejitsu/node-http-proxy) provides the actual proxy functionality.
IMO; fixing it in the `http-proxy` would benefit a broader audience.

Can you create an issue in their tracker? https://github.com/nodejitsu/node-http-proxy/issues

**Comment by adamreisnz** [comment]
Indeed, I will file it there, thanks

**Comment by adamreisnz** [comment]
It seems it was user error, I was using proxyRes instead of proxyReq to set the header, but proxyRes is the actual *response* from the target.
