### ISSUE TITLE
Post request responses 401

### ISSUE THREAD

**Issue by leonisme** [chimurai/http-proxy-middleware#146]
```javascript
var express = require('express');
var proxy = require('http-proxy-middleware');
var app = express();
app.use('/api', proxy({target: 'http://www.example.org:5000', changeOrigin: true, pathRewrite: {'^/api': ''}}));
app.listen(8080);
```
The target host is OK, which responded correctly when I send a get request. But when I send a post request, server responded with a status of 401 (Unauthorized). I checked the server and find out it had never gotten post request. So, I think the middleware hasn't send post request to the server successfully. But I don't know why.

**Comment by chimurai** [comment]
Hi,

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
