### ISSUE TITLE
[Question] How to handle relative urls?

### ISSUE THREAD

**Issue by roccomuso** [chimurai/http-proxy-middleware#148]
Is there any `http-proxy` option that handle this case?

https://serverfault.com/questions/561892/how-to-handle-relative-urls-correctly-with-a-reverse-proxy

**Comment by roccomuso** [comment]
Should I change the response body from the proxy perhaps?
Using tools like: https://github.com/philippotto/transformer-proxy
or https://github.com/No9/harmon for the HTML.

**Comment by chimurai** [comment]
As far as I know [`http-proxy`](https://github.com/nodejitsu/node-http-proxy) doesn't have an option to rewrite urls in the body of responses automatically (neither does `http-proxy-middleware`).

However you can modify requests and responses as you wish by subscribing to these HPM events:

- [onProxyReq](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onproxyreq)
- [onProxyRes](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onproxyres)

Or use tools like you indicated.

**Comment by chimurai** [comment]
You can now easily change responses:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/response-interceptor.md
