### ISSUE TITLE
http request proxy to https backend server

### ISSUE THREAD

**Issue by nicelj** [chimurai/http-proxy-middleware#159]
how can i use this to proxy http request from frontend to https backend server?I aways get this message:
 Error occurred while trying to proxy request /api/login from localhost:8888 to https://myserverip:22 (EPROTO) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by chimurai** [comment]
This has been asked and answered before: https://github.com/chimurai/http-proxy-middleware/issues/24#issuecomment-139020987

Please follow the guidelines: [CONTRIBUTING.md#got-questions-or-problems](https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md#got-questions-or-problems
)
