### ISSUE TITLE
using do redirect to local API

### ISSUE THREAD

**Issue by masterviana** [chimurai/http-proxy-middleware#161]
### Expected behavior

I've a prodution api in cloud, using a app from mobile I'm changing my phone proxy ip and port do my instance of this proxy and I want redirect all request that should ping my prodution API do local api

### Setup

It's possible to configure this?

* http-proxy-middleware: _version_
* server: _connect/express/browser-sync..._ + _version_
* other relevant modules

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/api', {target:'http://www.example.org', changeOrigin:true});
```
#### server mounting
```javascript
var app = express();

app.use(apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
