### ISSUE TITLE
proxy to same ip and port

### ISSUE THREAD

**Issue by lcxfs1991** [chimurai/http-proxy-middleware#162]
### Expected behavior
127.0.0.1:9000/news/ -> 127.0.0.1:9000
### Actual behavior
the server hang
### Setup

* http-proxy-middleware: latest
* server: _connect/express/browser-sync..._ + _version_
* other relevant modules

#### proxy middleware configuration & server mounting
```javascript
var app = express();
app.use('/news/', proxy({target: 'http://127.0.0.1:9000'}));

app.listen(port, function(err) {
	if (err) {
		console.error(err);
	}
	else {
		console.info("Listening on port %s. Open up http://127.0.0.1:%s/ in your browser.", 9000, 9000);
	}
});
```

This package works fine [proxy-middleware](https://www.npmjs.com/package/proxy-middleware)

**Comment by chimurai** [comment]
Hi,

With the configuration: `app.use('/news/', proxy({target: 'http://127.0.0.1:9000'}));`
You are proxying to the same url: `127.0.0.1:9000/news/` -> `127.0.0.1:9000/news/`
This probably explains why the server is hanging.

Try adding the `pathRewrite` to re-write the path:

`app.use('/news/', proxy({target: 'http://127.0.0.1:9000', pathRewrite:{'^/news/' : '/'}}));`

This will remove the `/news` from the path.

---

Considering to change the proxy and pathRewrite behaviour to make it behave more agnostic of the mounting path. So it'll behave more like proxy-middleware as you indicated. And for use-cases when you are using [Express Router](https://expressjs.com/en/4x/api.html#router); Think the current behaviour is limiting the Express Router re-use...
