### ISSUE TITLE
option.router not work

### ISSUE THREAD

**Issue by superpig** [chimurai/http-proxy-middleware#164]
### Expected behavior
My project servers on the  localhost:8000, but I get data from `http://tpt.test.com`, What I want to do is, when I make a http request, such as `http://tpt.test.com/my/api/activity/list`, I want to proxy the request to `http://localhost:8881`. I don't know that is there anything wrong.

### Actual behavior
It don't proxy the request to `http://localhost:8881`, it still send request to `http://tpt.test.com`.

### Setup

* http-proxy-middleware:  0.17.4
* server: express +  4.14.0
* webpack: 2.4.1

#### proxy middleware configuration
```javascript
var proxyMiddleware = require('http-proxy-middleware');
app.use(proxyMiddleware(
    '/my/api',
    {
        target: 'http://localhost:8881',
        changeOrigin: true,
        router: {
            'tpt.test.com' : 'http://localhost:8000'
        }
    }
));
```

#### http reuqest 
```js
$http({
    method: 'POST',
    url: 'http://tpt.test.com/my/api/activity/list',
    data: {objectId : 1}
}).then(function successCallback (response) {
    ...
}, function errorCallback (response) {
    ...
});
```

**Comment by chimurai** [comment]
`router` allows you to re-route to a different using the client's hostname and/or path.

You've configure your proxy in the opposite way, think it should look like:

```javascript
var proxyMiddleware = require('http-proxy-middleware');
app.use('/my/api', proxyMiddleware(
    {
        target: 'http://tpt.test.com',
        changeOrigin: true
    }
));

```

**Comment by udayms** [comment]
I'm having a similar problem.... My options looks like this - 

`return httpProxyMiddleWare('/api/**', {
        target: 'http://vm:8080',
        logLevel: 'debug',
        autoRewrite: true,
        pathRewrite: {
            '^/api/login': '/login',
            '^/api/logout': '/logout',
            '^/api/web/*': '/web/v1/',
            '^/api/cli/*': '/cli/v1/'
        },
        router: {
            'test1.eval': 'http://test1.eval.server.com:8080',
            'demo1.dev': 'http://demo1.dev.server.com:8080',
        },
        onProxyReq: onProxyReq,
        onProxyRes: onProxyRes,
        logProvider: function (provider) {
            return {
                log: logger.info,
                debug: logger.debug,
                info: logger.info,
                warn: logger.warn,
                error: logger.error
            };
        },
        changeOrigin: true
    });`

Am I doing anything wrong here? The onProxyReq method prints out the host correctly as passed. No errors. Except that the router is completely ignored. I'm running version `http-proxy-middleware@0.15.2`

**Comment by chimurai** [comment]
https://github.com/chimurai/http-proxy-middleware/blob/master/CHANGELOG.md#v0160

`router` option is introduced in `0.16.0`. Try updating HPM.

**Comment by udayms** [comment]
But, I am unable to update to 0.16.0... 
```
➜ git:(develop) ✗ npm update http-proxy-middleware --save
➜ git:(develop) ✗ npm install http-proxy-middleware --save
appname@1.5.0 /app
└── http-proxy-middleware@0.15.2
➜ git:(develop) ✗ npm install http-proxy-middleware@0.16.0 --save
percipient@1.5.0 /app
└── http-proxy-middleware@0.16.0  invalid
```
