### ISSUE TITLE
@types for http-proxy-middleware

### ISSUE THREAD

**Issue by katagaStyle** [chimurai/http-proxy-middleware#166]
Are there any @types declartions for http-proxy-middleware out there? 

Thx.

**Comment by chimurai** [comment]
Not aware of types declarations out there. Only seen some generated ones.

I'll put it on the todo list. Thx.

**Comment by lukeclifton** [comment]
@katagaStyle Is this what your looking for:
https://www.npmjs.com/package/@types/http-proxy-middleware

**Comment by chimurai** [comment]
Looks like this issue is resolved.
Closing issue. Feel free to re-open.
