### ISSUE TITLE
Docs for  rewriting path /** to empty

### ISSUE THREAD

**Issue by CallMeXYZ** [chimurai/http-proxy-middleware#175]
need docs for cases like below

proxy all path matching `/**/a.js` to `http://target.com/a.js`. 
In other words, just dont know how to rewrite path `/**` to empty

**Comment by chimurai** [comment]
Already documented here:

- https://github.com/chimurai/http-proxy-middleware#http-proxy-middleware-options
- https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/pathRewrite.md#remove-paths

**Comment by CallMeXYZ** [comment]
`'^/api/' : '/' ` and `'^/remove/api' : ''` both  are nice examples, the difference is all sub-paths should be removed.
any config like `'^/**/': '/'` or   `'^/**' : ''` ?

**Comment by chimurai** [comment]
"*" is a glob; you should use a valid regurlar expression.

You can also provide a function to rewrite the url.
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/pathRewrite.md#custom-rewrite-function
