### ISSUE TITLE
How can I add jsessionid to request

### ISSUE THREAD

**Issue by jianqiao0313** [chimurai/http-proxy-middleware#178]
### Nodejs
```
var options = { 
    hostname: '192.168.41.4:8080',
    path: '/mcms/v1/login',
    method: 'POST',
    port : config.get('_hostPort'),
    headers: {'Cookie': 'JSESSIONID='+global.jsessionid , "Content-Type": 'application/x-www-form-urlencoded', "Content-Length": data.length  }
};
var req = http.request(option,function(res){
    //dosomething
})
```
It is work,I can login because I add 'Cookie' that Tomcat know the Jsessionid.

### http-proxy-middleware
```
app.use('/api', proxy({
	target: 'http://192.168.41.4:8080/mcms/v1/',
	pathRewrite: {'^/api' : '/'}, 
	changeOrigin: true,
	onProxyReq : function(proxyReq, req, res){
		proxyReq.setHeader('cookie','JSESSIONID='+global.jsessionid);
	},
}));
```

But I use http-proxy-middleware it is not work.
I Read [Persisting a cookie based session over node-http-proxy](https://stackoverflow.com/questions/10291000/persisting-a-cookie-based-session-over-node-http-proxy?answertab=active#tab-top)
Please help me

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
