### ISSUE TITLE
proxyReqOptDecorator  does not change parameters

### ISSUE THREAD

**Issue by victorbucutea** [chimurai/http-proxy-middleware#182]
in decorateProxyReqOpts.js you have this line **delete processedReqOpts.params;**.

How am I supposed to modify the request params if not in a proxyReqOptDecorator ? 

`return Promise
    .resolve(resolverFn(container.proxy.reqBuilder, container.user.req))
    .then(function(processedReqOpts) {
        delete processedReqOpts.params;
        container.proxy.reqBuilder = processedReqOpts;
        return Promise.resolve(container);
    });`

**Comment by victorbucutea** [comment]
I can submit a PR if you want.

**Comment by chimurai** [comment]
Don't recognize this piece of code in `http-proxy-middleware` or `http-proxy`
Think you're confusing the library with other middleware?

https://github.com/search?q=processedReqOpts&type=Code&utf8=%E2%9C%93

**Comment by victorbucutea** [comment]
Oh yeah. But the question still stands for `http-proxy-middelware`. Let me post another issue
