### ISSUE TITLE
get body no data

### ISSUE THREAD

**Issue by xwinie** [chimurai/http-proxy-middleware#187]
### Expected behavior
req.body{"username":1111}
### Actual behavior
req.body {}

### Setup

* http-proxy-middleware: 0.17.4
* server:express:4.14.0
* body-parser

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/api', {target:'http://www.example.org', changeOrigin:true,
  onProxyReq(proxyReq, req, res) {
        let bodyData = JSON.stringify(req.body);
        console.log('request body : ' + bodyData);
    }});
```
#### server mounting
```javascript
var app = express();

app.use(apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
Not a HPM issue.
Please read the body-parser documentation carefully:
https://www.npmjs.com/package/body-parser
