### ISSUE TITLE
Undocumented 'buffer' option

### ISSUE THREAD

**Issue by jonhunter1977** [chimurai/http-proxy-middleware#191]
This is more of a question than an issue.

I have some middleware that runs prior to calling this proxy middleware that reads the request stream of the http request into a `req.rawbody` field on the request (so I can validate the message before passing it onto the proxy).

This caused me problems as it seems the http-proxy code wants to read the stream that has already been consumed.

So I was digging around and found there was an option called `buffer` that could be set to a stream and this solved my problem.  For example this is my middleware:

```
'use strict';

const streamify = require('stream-array');
const proxy = require('http-proxy-middleware');

module.exports = (req, res, next) => {

  const dummyEndpointProxy = proxy({
    target: 'http://localhost:4003/',
    buffer: streamify(req.rawBody)
  });

  return dummyEndpointProxy(req, res, next);
};
```
I was just wondering if its OK to do things this way or am I hacking it badly?

Thanks

Jon

**Comment by chimurai** [comment]
Does look like a undocumented option in the `http-proxy` library. ([http-proxy/passes/web-incoming.js#L114](https://github.com/nodejitsu/node-http-proxy/blob/927357bedc42f2e3067c44c10ab9563be7d8b032/lib/http-proxy/passes/web-incoming.js#L114))

Care to create an issue or a simple PR to documenting this option? (in the [http-proxy](https://github.com/nodejitsu/node-http-proxy) repo)
If it gets documented, it's not a hack anymore :wink:

I'll keep this issue open until the docs are fixed upstream.

**Comment by jonhunter1977** [comment]
Hi,

Yes I'm happy to put a PR in!  I'll get working on it :+1:

**Comment by chimurai** [comment]
Great!

Can you link back to this issue? To keep track of it.

**Comment by jonhunter1977** [comment]
I've created the PR here https://github.com/nodejitsu/node-http-proxy/pull/1202

**Comment by imfht** [comment]
Hi, Can I disable the buffer here?
I'm using vue and I want http-proxy-middleware return what the server returned to me.
By default http-proxy-middleware would return only when the server returned all the data to me.

**Comment by ifaomobileios** [comment]
Aren't we creating a new proxy instance, using this approach with http-proxy-midleware? On every request I get the following debug log: 

**[HPM] Proxy created: /  ->  http://localhost:3000/test/multipart
 [HPM] Proxy rewrite rule created: "^/foo/bar" ~> ""
 [HPM] Subscribed to http-proxy events:  [ 'proxyReq', 'error', 'close' ]
 [HPM] Rewriting path from "/foo/bar" to ""
 [HPM] POST /foo/bar ~> http://localhost:3000/test/multipart
**

**Comment by stoyanmkd** [comment]
Aren't we creating a new proxy instance on every request, using this approach with http-proxy-midleware? On every request I get the following debug log:

**[HPM] Proxy created: / -> http://localhost:3000/test/multipart
[HPM] Proxy rewrite rule created: "^/foo/bar" ~> ""
[HPM] Subscribed to http-proxy events: [ 'proxyReq', 'error', 'close' ]
[HPM] Rewriting path from "/foo/bar" to ""
[HPM] POST /foo/bar ~> http://localhost:3000/test/multipart
**
