### ISSUE TITLE
Doesn't correctly proxy some requests (may involve Firebase)

### ISSUE THREAD

**Issue by SidneyNemzer** [chimurai/http-proxy-middleware#198]
I'm developing a Firebase app using Webpack and the Webpack DevServer (which uses http-proxy-middleware). To load Firebase in the browser, I'm taking advantage of the [reserved URLs](https://firebase.google.com/docs/hosting/reserved-urls) that Firebase hosting provides. Of course, these URLs don't work when DevServer is hosting my files, so I set up the proxy to redirect any requests to `/__` to go to my Firebase hosting URL (`https://[myapp].firebaseapp.com`). It works for the library files (eg `/__/firebase/4.2.0/firebase-app.js`).

However, the proxy does not work for the init file (`/__/firebase/init.js`). That file returns a page like this:

![image](https://user-images.githubusercontent.com/21203108/29894481-3b98873a-8d8a-11e7-885f-3cd966f8f195.png)

However, directly visiting `https://[myapp].firebaseapp.com/__/firebase/init.js` DOES return the init file, as expected. I can also retrieve the file using Postman, so I don't think it's an issue with the useragent.

It seems to be some issue with the proxy. 

Any ideas/solutions would be appreciated.

### Setup

* http-proxy-middleware: 0.17.4
* server: webpack-dev-server 2.5.0
* webpack: 3.0.0

#### proxy middleware configuration
```javascript
// webpack config
{
  // webpack stuff
 //...

  devServer: {
    contentBase: './public',
    inline: true,
    stats: {
      colors: true
    },
    proxy: {
      '/__': {
        target: 'https://my-app.firebaseapp.com',
        secure: false // Without this, all requests fail
      }
    }
  }
}
```

**Comment by chimurai** [comment]
Can you try the wildcard config? i.e.:  `'/__/**'`

```javascript
    proxy: {
      '/__/**': {
        target: 'https://my-app.firebaseapp.com',
        secure: false // Without this, all requests fail
      }
    }
```

**Comment by SidneyNemzer** [comment]
Thanks for the reply @chimurai, but unfortunately I still have the same issue with the wildcard URL.

**Comment by chimurai** [comment]
Can you try adding this option: `changeOrigin: true`.

```javascript
    proxy: {
      '/__': {
        target: 'https://my-app.firebaseapp.com',
        changeOrigin: true,
        secure: false // Without this, all requests fail
      }
    }
```

**Comment by SidneyNemzer** [comment]
That fixed it! Err, just for my benefit, what exactly does that option do and why would Firebase care?

**Comment by chimurai** [comment]
It's described in the documentation: https://github.com/chimurai/http-proxy-middleware

Firebase uses name-based virtual hosts; Basically they are reusing a single ip-address for multiple host names.
The `host` header needs to be proxied correctly for name-based virtual hosts. Setting `changeOrigin` to `true` will fix the `host` header for you.

> https://en.wikipedia.org/wiki/Virtual_hosting#Name-based

**Comment by elisherer** [comment]
To whoever comes to this issue trying to configure the middleware to do the same using `create-react-app`
This is my solution that worked:
(using `customize-cra`)
```js
const { override, addWebpackExternals, overrideDevServer } = require("customize-cra");

const firebasePrefix = "^/__/firebase";

const mockFirebaseHosting = () => config => {
  config.proxy = {
    [firebasePrefix]: {
      target: "https://www.gstatic.com",
      changeOrigin: true,
      secure: false, // Without this, all requests fail
      //logLevel: "debug",
      pathRewrite: {
        [firebasePrefix]: "/firebasejs",
      },
      bypass: function (req, res, proxyOptions) {
        if (req.url.includes("init.js")) {
          return "/local-init.js";
        }
      },
    },
  };
  return config;
};

module.exports = {
  webpack: override(addWebpackExternals("firebase")),
  devServer: overrideDevServer(mockFirebaseHosting()),
};
```
Create a `local-init.js` file in your `public` folder with the `initializeApp` script.
