### ISSUE TITLE
how to change proxy target dynamically 

### ISSUE THREAD

**Issue by crazyxhz** [chimurai/http-proxy-middleware#200]
### Expected behavior
change the proxy target when an api is called
### Actual behavior
log info display the new proxy is set up, but in fact it is still proxy to the old proxy target
### Setup

* http-proxy-middleware: _version_
^0.17.3
* server: _connect/express/browser-sync..._ + _version_
^4.14.1
* other relevant modules

#### proxy middleware configuration
```javascript
var opt = {
        target: 'https://sitea.com/',
        changeOrigin: true,
        secure: false,
        xfwd: true,
        hostRewrite: true,
        cookieDomainRewrite: true,
        headers:'...'
}
app.use(proxyMiddleware('/api', opt));


router.get('/online', function (req, res) {
  opt.target = 'http://siteb.com/';
  app.use(proxyMiddleware('/api', opt));
  console.log(chalk.red(`switching to site b proxy`));
  res.json('ok');
});

```

**Comment by chimurai** [comment]
Try the `router` option: https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md

**Comment by crazyxhz** [comment]
@chimurai thanks. It works.

**Comment by tojoirinah** [comment]
I'm using VueJS 2.x, how to configure this dynamically proxy target change? Do you have some example to show ?

**Comment by daverogers** [comment]
```js
function customRouter(req) {
  const { hostname } = req
  const tenant = hostname.split('.')[0]
  return `https://${tenant}.sub.domain.com`
}

module.exports = {
  ...
  devServer: {
   ...
    proxy: {
      '^.*$': {
        target: 'https://tenant.sub.domain.com',
        router: customRouter
      }
    }
  }
}
```

An example for anybody else using Vue 2.x, I needed a dynamic target to pass-through a subdomain in a multi-tenant application (so when one of our customers runs `customername.sub.domain.com` then `customername` would pass through the proxy)
