### ISSUE TITLE
proxyRes.on('data', function) does not work.

### ISSUE THREAD

**Issue by taveratch** [chimurai/http-proxy-middleware#203]
<img width="458" alt="screen shot 2560-09-21 at 12 39 38" src="https://user-images.githubusercontent.com/8603253/30680468-013644f0-9eca-11e7-8a23-d49d090aa83a.png">

I'm trying to grab body from response before send it to client. But it seems socket ( .on(...) ) function is not executed. However, the response is sent to client successfully.

Did I miss anything or did anything wrong ?

**Comment by ortonomy** [comment]
It does... data is in a stream. you have to parse it.

**Comment by Eugenio161288** [comment]
Does anyone know how to return custom response in res object based on proxyRes, but do not copy the data directly from res object?

The question from stackoverflow: https://stackoverflow.com/questions/54005345/custom-response-with-http-proxy-middleware-package

Need help with that :)

**Comment by devinrhode2** [comment]
Seems that this is not working for us on windows, but it works on mac...
same node version
same module versions..
Mac - proxyRes.on('data' fires the callback
on windows, it just doesn't fire

the client(browser) does not receive any response data...

**Comment by devinrhode2** [comment]
we still get a status 200 and response headers....
@taweesoft @nahushf make sure you are setting selfHandleResponse: true

**Comment by yy7054wyq5** [comment]
same as "the client(browser) does not receive any response data".

**Comment by marcusds** [comment]
I am having a similar issue, but it only happens on every second request that `proxyRes.on('data', data => {});` does not fire. `end` always fires however.  50% of the time it works fine. There is no such issue when hitting the proxied end point directly.

**Comment by hpl002** [comment]
> It does... data is in a stream. you have to parse it.

Heres a quick copy pasta:
```
      const apiProxy = createProxyMiddleware("/api", {
        logLevel: "debug",
        target: "http://localhost:3020",
        onProxyRes: (proxyRes, req, res) => {
          proxyRes.on("data", (data) => {
            console.log("received data as stream");
            const bufferAsString = data.toString("utf-8");
            console.log(bufferAsString);
          });
        },
      });
```

**Comment by chimurai** [comment]
`responseInterceptor` might help:

https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/response-interceptor.md
