### ISSUE TITLE
the websocket proxy does not work if there is no http request route to the proxy first.

### ISSUE THREAD

**Issue by ulion** [chimurai/http-proxy-middleware#207]
### Expected behavior
a websocket only proxy setup should work without require http request to the proxy first.

### Actual behavior
if no http request to the proxy was made after the server started, the pure websocket request (from browser or from wscat ws/wss request) will only result socket hang up, and non log entry produced at all even in debug log level.

### Setup

* http-proxy-middleware: 0.17.4
* server: express + 4.13.3

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/socket.io', {
      target: 'https://socket.xxxx.com',
      changeOrigin: true,
      ws: true});
```
#### server mounting
```javascript
var app = express();

app.use('/socket.io', apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
Please try this and see if it works:
https://github.com/chimurai/http-proxy-middleware#external-websocket-upgrade

**Comment by ulion** [comment]
thx, it does resolved the problem. but it's very tricky to get the http server object in the code. so there is no better way to overcome this?

**Comment by chimurai** [comment]
> it's very tricky to get the http server object 

Same story from a middleware perspective.
