### ISSUE TITLE
 FR: Add a option to allow change Referer header

### ISSUE THREAD

**Issue by Jack-Works** [chimurai/http-proxy-middleware#208]
### Expected behavior
change the Referer header or give a option to do this

### Actual behavior
Directly passed.

### Setup
See https://github.com/webpack/webpack-dev-server/issues/1151

* http-proxy-middleware: latest
* server: webpack-dev-server@latest
* other relevant modules

**Comment by chimurai** [comment]
Try using the `headers` option to supply your own `referer` header.
As documented in https://github.com/chimurai/http-proxy-middleware#http-proxy-options

**Comment by Jack-Works** [comment]
Oh I just think headers option is that from server to client...
We need change the header like way of changeOrigin option, tell me if I got something wrong

**Comment by chimurai** [comment]
`headers` option is to change the headers between client to server.

`referer` can be basically any url. Not sure how you want to change that similar to changeOrigin.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

Perhaps you can explain your use case a bit?

**Comment by Jack-Works** [comment]
I've read that. Maybe I'm just not clear about what I am doing...

**Comment by SidKwok** [comment]
I got a js file, and use it in this way:
```
...
script.src = 'http://example/a/b/test.js'
...
```

And how am I supposed to write the proxy to change its referer.

**Comment by joaocraveiro** [comment]
@SidKwok were you ever able to solve that? I'm having the exact same issue.

**Comment by SidKwok** [comment]
@joaocraveriro it can’t be solved. It is a http request, webpack can’t proxy a http request. You can try to change headers via chrome extensions

**Comment by aranmohyeddin** [comment]
So what are we supposed to do if our backend enforces referer check??
