### ISSUE TITLE
[Question] Empty pathname context

### ISSUE THREAD

**Issue by aaronte** [chimurai/http-proxy-middleware#210]
### Question 

Is it possible to have an empty pathname (`/`) to be proxied to a target? It seems like currently, 
```js
proxy('/', {...})
```
matches any route.

**Comment by chimurai** [comment]
Described behaviour is correct.

You can provide your own function to determine when to proxy.

```javascript
proxy(path => { return path === '/' }, {...})
```

Also documented here:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md#custom-filtering

**Comment by aaronte** [comment]
@chimurai I tried doing the function as a parameter of `proxy` initially but the path for an empty path seems to be returned as `/null`

**Comment by chimurai** [comment]
Must be something in the way the proxy is mounted.

https://github.com/chimurai/http-proxy-middleware/blob/master/ISSUE_TEMPLATE.md#server-mounting
