### ISSUE TITLE
How to get proxy and page details

### ISSUE THREAD

**Issue by vvbhandare** [chimurai/http-proxy-middleware#213]
I am trying below snippet

```
var express = require('express');
var proxy = require('http-proxy-middleware');
 
var app = express();
 
app.use('/', proxy({target: 'https://www.google.co.in/search?q=hello+world', changeOrigin: true}));
app.listen(5000);
```

I want to get proxy details through which e.g. IP it is redirect to specific url and loaded page html.

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.

**Comment by vvbhandare** [comment]
Please don't close it. Better place is this than SO because dev team can quickly suggest better solution as they developed this library.
