### ISSUE TITLE
Proxy dont work with post action

### ISSUE THREAD

**Issue by minhduchcm** [chimurai/http-proxy-middleware#215]
I setup proxy middleware on express. Proxy work as expected with get request. But I can't use login form in anymore.
note: i have rewrite the form action url to my proxy manually.
![capture](https://user-images.githubusercontent.com/25229001/32131482-2b1ceb1c-bbd9-11e7-87fb-7dada38081e7.PNG)

### Setup
* server: express

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/proxy', {
    target: 'https://m.facebook.com/',
    changeOrigin: true,
    pathRewrite: {  '^/proxy/login.php': '/login.php' },
    onProxyReq: (proxyReq, req, res) => {
        proxyReq.setHeader( 'User-Agent', 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)' );
    }
});
```
#### server mounting
```javascript
var app = express();

app.use(apiProxy);
app.listen(3001);
```

**Comment by chimurai** [comment]
Can you reproduce this in an isolated setup?
(without the m.facebook.com as target)

Even better if you can provide a working setup in a repo.

**Comment by foisonocean** [comment]
I have the same problem

**Comment by santimendoza** [comment]
Having the same issue with POST proxys. Give a couple hours and I try to reproduce an example.

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.

Thanks.

PS: I think StackOverflow would be a better place to troubleshoot your setup.

**Comment by udalov** [comment]
@chimurai I've met the same issue and after seeing this ticket, assumed this is a known problem that is going to be addressed. I'm not sure if I can extract a small repro from my project. Are POST requests actually supported by http-proxy-middleware?

**Comment by chimurai** [comment]
POST requests are supported. Some issues might occur if your using `body-parser` for example. In those cases make sure you've configured/mount the proxy prior to the body-parser.

**Comment by udalov** [comment]
Thanks, I'm using `body-parser` indeed, I'll try your suggestion.

**Comment by timtutt** [comment]
FYI - I just tried this - moving above bodyParser... Curious as to why this is necessary?

**Comment by tornado-softwares** [comment]
> POST requests are supported. Some issues might occur if your using `body-parser` for example. In those cases make sure you've configured/mount the proxy prior to the body-parser.

Thank you very much, I probably saved hours of debugging, but I really wonder why this is happening, I'm going to look a little further.
