### ISSUE TITLE
js file can't be proxy

### ISSUE THREAD

**Issue by SidKwok** [chimurai/http-proxy-middleware#216]
### Expected behavior
Proxy the js file from web.
### Actual behavior
it can't
### Setup

* http-proxy-middleware: 0.17.4
* server: express  4.16.2
* [vue-template/webpack](https://github.com/vuejs-templates/webpack)

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/a/**/*.js', {
  target: 'http://www.example.org',
  changeOrigin:true,
  onProxyReq: function () {
    console.log('it works')
  }
});
```
#### server mounting
```javascript
var app = express();

app.use(apiProxy);
app.listen(3000);
```

#### import the js
```javascript
let script = document.createElement('script');
script.src = 'http://www.example.org/a/test.js'
document.head.appendChild(script);
...
```

No log info in the terminal.

Let me know if you need more info.

**Comment by chimurai** [comment]
Guess you're not using/hitting the proxy at all.

Should your script look more like:
```
script.src = 'http://localhost:3000/a/test.js'
```

or on you `localhost:3000`

```
script.src = '/a/test.js'
```

**Comment by cobish** [comment]
@SidKwok 现在 js 文件还能够代理吗？

**Comment by chimurai** [comment]
Hi @cobish, please use stackoverflow to troubleshoot setup.

**Comment by cobish** [comment]
@chimurai OK, thank a lot.
