### ISSUE TITLE
How can I get correct request

### ISSUE THREAD

**Issue by mqliutie** [chimurai/http-proxy-middleware#218]
When match `/api` I want get data from 'http://localhost:3000'
When match `/api/test` I want get data from 'http://localhost:3001';

I have try do 
```
devServer : {

    proxy:{
        '/api':{target:"http://localhost:3000"},
        '/api/test':{target:"http://localhost:3001"}
    }

}
```

But not work

**Comment by chimurai** [comment]
`route` options should do the trick.

https://github.com/chimurai/http-proxy-middleware/blob/92bb9b7a431fb48e8014d7e4452f4b5f892da6d1/recipes/router.md
