### ISSUE TITLE
Route based on hostname

### ISSUE THREAD

**Issue by c0debreaker** [chimurai/http-proxy-middleware#223]
So I got http-proxy-middleware and http-proxy-agent working well now. However, to make my life easier :) I'll need to be able to route traffic based on hostname rather than just paths. It's because we have several backend api endpoints that are on different servers.

Basically, I want to do something similar to my config code below but I'm sure it might not work. So any HTTP requests that goes to http://server-api-a will be forwarded to http://10.0.0.1:3128. Any HTTP requests that goes to http://server-api-b will be forwarded to http://192.168.1.10:8888

```js
var HttpsProxyAgent = require('https-proxy-agent');
var proxy = require("http-proxy-middleware");

var optionsServerA = {
    target: 'http://thatserver',
    agent: new HttpsProxyAgent('http://10.0.0.1:3128')
};

var optionsServerB = {
    target: 'http://anotherserver',
    agent: new HttpsProxyAgent('http://192.168.1.10:8888')
};

var apiProxy = proxy('http://server-api-a', optionsServerA);
var apiProxy = proxy('http://server-api-b', optionsServerB);
```

Any ideas how this can be achieved?

**Comment by c0debreaker** [comment]
I can add each /path and it works but more prone to error especially if I miss one or few more paths.

**Comment by chimurai** [comment]
The `router` option is maybe something you're looking for.

https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md

**Comment by c0debreaker** [comment]
WOW! Looks like that could be it! :D I'll play with it tonight. Thanks a lot! :)

**Comment by c0debreaker** [comment]
I'm very close but I need to bypass the http-proxy-agent when my request is ` onlylocal.com `. What do I need to change?

```js
var customRouter = function(req) {
  let host = '';
  switch  (req.headers.host) {
    case 'cs.video.example.com': host = 'http://cs.video.exampe.com'; break;
    case 'onlylocal.com': {
        if (req.originalUrl.indexOf('/app') !== -1) {
          host = 'http://localhost:9990';
        }
        if (req.originalUrl.indexOf('/static') !== -1) {
          host = 'http://localhost:8888';
        }
        break;
    }
  }
  return host;
};

var options = {
    agent: new HttpsProxyAgent('http://10.10.214.92:2301'),
    target: 'http://www.example.com',
    router: customRouter
};

var myProxy = proxy(options);

var app = express();
app.use(myProxy);
```

**Comment by c0debreaker** [comment]
I got this working now

**Comment by cawoodm** [comment]
Is there any way to use the router based on `X-Forwarded-Host` and not the `Host` header?

**Comment by cawoodm** [comment]
> Is there any way to use the router based on `X-Forwarded-Host` and not the `Host` header?

OK, we have managed this using a higher priority express middleware to overwrite `req.headers.host`.
