### ISSUE TITLE
http-proxy-middleware is choking when there are many http requests

### ISSUE THREAD

**Issue by c0debreaker** [chimurai/http-proxy-middleware#224]
One of our web applications(called Inflight Entertainment) retrieves 220+ thumbnails during loading of the app and renders it on screen. I noticed that when HTTP requests of the images are sent to HTTP-PROXY-MIDDLEWARE, the first 20 to 30 requests are fast but as it keeps on retrieving the remaining 200 urls of the images, HPM would be so slow up to the point the browser will just showing pending state for a long time. Eventually, Chrome would show them as 404. Also when this happens, the cpu fan of my laptop goes crazy. The cpu fan stops after 8-10 mins.

When I configure my Chrome browser to point directly to the proxy that HTTP-PROXY-MIDDLEWARE is using, our app loads up fine without any issues retrieving the 220+ thumbnails.

Is there a workaround to this?

**Comment by c0debreaker** [comment]
I had a bug in the code. It's faster now.

**Comment by chimurai** [comment]
Hi @c0debreaker ,

Thank you for your question.
Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
