### ISSUE TITLE
How to set this

### ISSUE THREAD

**Issue by guoxiangwen** [chimurai/http-proxy-middleware#228]
```
app.use(`/apiProxy`, proxy({
  target: 'http://172.17.123.131:10241',
  // target: 'http://172.17.123.216:4000',
  changeOrigin: true,
  logLevel: 'debug',
  proxyReq: function (req) {
    console.log(req)
  }
}));
```
when i ajax get(`/apiProxy/TaxRate/GetTaxRates`)  i want to refer to `http://172.17.123.131:10241/TaxRate/GetTaxRates`

not `http://172.17.123.131:10241/apiProxy/TaxRate/GetTaxRates`

How did i do this?

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
