### ISSUE TITLE
Question on pathrewrite

### ISSUE THREAD

**Issue by ghost** [chimurai/http-proxy-middleware#229]
Hello,

I'm trying to reverse proxy a server. My server looks like this: 

```
- server.js
- static/
    - index.html
    - *.js
```

Here's a working sample:

```
const serverProxy = proxy('/', { 
    target: 'http://localhost:3001'
});

app.use(serverProxy);
app.listen(3001);
```

When I go to http://localhost:3000, I get to see the same thing that I would on http://localhost:3001. 

Here's a non-working sample, where I try to access the server from `/server` instead of `/`:

```
const serverProxy = proxy('/server', { 
    target: 'http://localhost:3001',
    pathRewrite: {
        '^/server' : ''
    },
});

app.use(serverProxy);
app.listen(3001);
```

Here I get a blank page when I go onto http://localhost:3000/server. It's kind of weird because:

- I do make a request on http://localhost:3001 and not http://localhost:3001/server (because of the rewrite). When I look into the logs of my reverse proxied server I can see that I received a request on '/' and not on '/server'.
- I do receive the proper index.html from the server.

but

- I failed to load the .js files (it looks like it tries to load them from http://localhost:3000/ instead of http://localhost:3001/)

What am I doing wrong?

**Comment by chimurai** [comment]
Sounds like your html contains full urls to the .js files (including  http://localhost:3000)

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
