### ISSUE TITLE
How to access httpProxy object?

### ISSUE THREAD

**Issue by Paxa** [chimurai/http-proxy-middleware#230]
Is it possible?

**Comment by chimurai** [comment]
Currently not not able to.
Can you describe the use case why you might need it?

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.

**Comment by rizkyramadhan** [comment]
I think my issue https://github.com/chimurai/http-proxy-middleware/issues/281 will need this to be re-opened
