### ISSUE TITLE
How to set HTTP read timeout?

### ISSUE THREAD

**Issue by monkeyWie** [chimurai/http-proxy-middleware#231]
I have a request and this response  block more than 2 min，then browser throw a error，as below.

![image](https://user-images.githubusercontent.com/13160176/34484973-1c2baac2-f003-11e7-8e5b-d4a5b1d79a6a.png)

so,how should I set unlimited response timeout？
THX！

**Comment by Sunaree1985** [comment]
Fuck

**Comment by monkeyWie** [comment]
@Sunaree1985 
操你妈

**Comment by chimurai** [comment]
Hi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.

**Comment by Fi1osof** [comment]
> Hi,
> 
> Thank you for your question.
> 
> Please use StackOverflow. I think that would be a better place to troubleshoot your setup.
> 
> Thanks.

This is not 3d party troubleshoot. In my case i set timeout in express response object
```
response.setTimeout(seconds * 1000, () => {
  console.error('Request has timed out.');
  res.writeHead(408, 'Request Timeout');
  res.end('Timeout!')
});
```
When i send direct request (without http-proxy-middleware) all works fine. But when i use proxy, request canceled on default 2 minutes.
```
app.use(proxy('/api/', {
  target: 'http://localhost:4000/',
  ws: true,
  pathRewrite: {
    "^/api/": "/"
  }
}));
```

**Comment by chimurai** [comment]
Did you try the `timeout` option?
https://github.com/chimurai/http-proxy-middleware#http-proxy-options
