### ISSUE TITLE
Request redirecting not proxing

### ISSUE THREAD

**Issue by dottodot** [chimurai/http-proxy-middleware#234]
Bit confused as to what's going on as on localhost it works as expected but when uploaded to my server it's redirecting to the proxy url.

So on localhost if I goto `https://localhost:4200/sitemap.xml` then url stays the same and I get the response from the proxy but my test site if goto `https://example.com/sitemap.xml` it redirects to `https://api.example.com/sitemap`

```
app.use(
  '/sitemap.xml',
  proxy({
    target: 'https://api.example.com',
    changeOrigin: true,
    pathRewrite: {
      '^/sitemap.xml': '/sitemap'
    }
  })
);
```

**Comment by chimurai** [comment]
[Absolute urls](https://tools.ietf.org/html/rfc3986#section-4.3) are not proxied.
Suspecting you sitemap.xml contains absolute urls...

**Comment by dottodot** [comment]
I don't really understand why the xml data returned from `https://api.example.com/sitemap` would cause it to redirect

**Comment by chimurai** [comment]
Probably it's returning a 302 redirect. (https://en.wikipedia.org/wiki/HTTP_302)
Sounds like your facing a setup issue than a bug.

Think StackOverflow would be a more appropriate place to ask this question.

**Comment by Mizziw** [comment]
orkid came and left
