### ISSUE TITLE
Simple GET proxy does not work when the request url ends in .php (Using the vue-cli)

### ISSUE THREAD

**Issue by johndatserakis** [chimurai/http-proxy-middleware#235]
### Expected behavior
Proxying should occur for POST and GET (among other) requests when the request ends in `.php`. This is all using the [vue-cli proxying method](https://vuejs-templates.github.io/webpack/proxy.html) in a vue-cli webpack project.

### Actual behavior
**Proxying only occurs in POST requests where .php is the last part of the url.** When a GET request is tried with the same exact code and set up - the raw php is found - and it is evident that the actual proxy did not trigger. 

I confirmed this by turning on the debug mode (as seen in the config) and confirmed that when a POST request is used (all requests are from axios), 

`let response = await axios.post('/static/api/v1/index.php')`

I get the proper feedback and result: 

`[HPM] POST /static/api/v1/index.php -> http://mylocaltesturl.test` 

When I simply change the method, 

`let response = await axios.get('/static/api/v1/index.php')`

there is no console feedback and the proxy is not run. Then, just because I wanted to be sure, I ran this test: 

`let response = await axios.get('/static/api/v1/')`

so I could *trick* the setup into sending it to `index.php` without physically writing `index.php`, it did work successfully and I received the proper feedback: 

`[HPM] GET /static/api/v1/ -> http://mylocaltesturl.test`. 

So essentially I proved that it is not that GET request it doesn't like, but rather the fact that the url ended in `.php`.

### Setup
Using the [vue-cli webpack build](https://github.com/vuejs-templates/webpack) which uses the http-proxy-middleware

#### proxy middleware configuration
```javascript
    proxyTable: {
        // proxy all requests starting with /static to the .test url for this site
        '/static': {
            target: 'http://mylocaltesturl.test',
            changeOrigin: true,
            logLevel: 'debug'
        }
    },
```

Has anyone ran into anything like this? Any tips or suggestions?

**Comment by chimurai** [comment]
Please verify your php server config...
Not sure what your setup is... Starting it with slightly different config might help? https://github.com/chimurai/http-proxy-middleware/issues/21

If you're using the `body-parser` middleware, it might cause issues with POST...
https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-163398924

**Comment by johndatserakis** [comment]
I will further study that thread, thank you.

It's just that this issue only happens when the url ends with `.php` - I feel like that must be something in the `http-proxy-middleware` side - just because that is literally the only time it *doesn't* work - everything else proxies great.

**Comment by johndatserakis** [comment]
@chimurai Thanks for your link. I am not using Laravel - as this is just some raw php. This raw php is being served using Vagrant at `http://mylocaltesturl.test/static/api/v1/index.php`. When I POST or GET to that page with Postman it works as intended.

Also, as I mentioned, using POST through the proxy works perfectly. I get the debug information and everything - the only issue is that with everything else the same - a GET request doesn't seem to trigger the proxy - it just calls `http://localhost.8080/static/api/v1/index.php` and the php code comes through raw. No proxy triggered - I can confirm that by watching the debug log.

What's interesting I found, is that when I remove the `index.php` part of the request and just use `http://mylocaltesturl.test/static/api/v1/` - the GET request with the proxy works great.

So I think I've narrowed it down to it getting upset when .php at the end of the url - you every seen anything like this or have a clue as to why that out of all things would cause it to freak out?

Also, to anyone else reading this - have you ever got a GET request to work through the proxy with a url that ended in `.php`? I feel like that's the exact issue I've uncovered here.

**Comment by chimurai** [comment]
Not aware of any special code written in the middleware to handle 'file' extensions; e.g. `.php`

1. You might wanna check the raw requests received on server-side and compare the requests between the ones made with Postman.
2. Or create a dead simple `.php` page which can print some 'hello world' message; "Hello GET" for GET request and "Hello POST" for POST request for example.
3. Check you PHP server config: https://stackoverflow.com/questions/17703980/html-form-returning-raw-php-code#comment25802834_17703980

Don't think it's a bug in the middleware, untill some concrete proof is provided  ;-)

**Comment by johndatserakis** [comment]
Thank you for your help. I ended up going a different direction, and cannot confirm the issue was with this tool. I'll close this for now. Thank you.
