### ISSUE TITLE
Using this module on dynamic URLs

### ISSUE THREAD

**Issue by mercmobily** [chimurai/http-proxy-middleware#239]
#Hi there,

First of all, thank you for the wonderful module.

[Quick intro, you can skip]
I just finished developing https://github.com/mercmobily/best-webdriver, which is a _much_ simpler implementation of the webdriver protocol. I am actually trying to gather up people to mimic the same API in python, ruby, .net and Java... but that's another story).
I decided that I can go another step and actually write an implementation of a webdriver remote end.
[End of quick intro]

The way it works, is simple: the hub/proxy will have a list of remote "ends", call them `r1`, `r2`, `r3`, `r4` listening to `http://r1/`, `http://r2/`, `http://r3/`, `http://r4/`, When somebody calls anything in the form of `/session/r1_session/something`, I will need to proxy to `http://r1/`; when the requested URL is `/session/r2_session/something`, I will need to proxy to `http://r2/`; etc.

Is there a simple way to do this?
I saw this:

    var apiProxy = proxy(filter, {target: 'http://www.example.org'})  

But `filter` will only ever say 'yay' or 'nay'. What I need, is a way to change WHERE it gets proxied too (which is what I need)

I can't do:

    var apiProxy = proxy('/session/r1_session/', {target: 'http://r1'});

Mainly because express doesn't have `app.release`, and I can't really to this easily.

I *could*:

    app.get('/session/:sessionId', (req, res) => {
      if (req.params.sessionid === 'r1_session'){
        proxy('http://r1/')(req, res)
      }
    })

(Sorry, I haven't tested it, but you get the gist of what I am doing).

Is this a sane way to go?

Merc.

**Comment by chimurai** [comment]
Thank you for the kind words.

You might want to take a look at the `router` option:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md

This option allows you to route to a different target; Using a table or a custom function.

**Comment by mercmobily** [comment]
Wow... is there a use case you haven't considered?!?!
Nice one. Thank you so much for your help...
