### ISSUE TITLE
HPM proxy sockjs got Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by chris4dd** [chimurai/http-proxy-middleware#245]
### Expected behavior
Now I'm writing a quotation system . Back end is spring-boot and front is Vue. 
I use sockjs-client and stompjs to communicate with backend tomcat server
What I want is to prxoy
 ws://localhost:9528/jcs/websocket to ws://localhost:8088/jcs/websocket,
also all the http request with prefix /jcs 
http://10.8.8.75:9528/jcs/websocket/info to  http://10.8.8.75:8088/jcs/websocket/info

### Actual behavior
It seems I can't achieve this with config below. Am I missing anything?
### Setup

* http-proxy-middleware: 0.17.4
* server: express +4.15.3
* "sockjs-client": "^1.1.4",
*  "stompjs": "^2.3.3",   

#### proxy middleware configuration
'/jcs' : {
              target : 'http://10.8.8.75:8088',
              changeOrigin: true,
              pathRewrite: {
                  '^/jcs' : '/jcs'
              },
              ws: true
          }
#### js code to open websocket connection 
let socket = new sockjs('jcs/websocket'); // it will fail here               
let stompClient = stomp.over(socket);

If I didn't use proxy it works fine. There would be two request in browser network:
`Request URL:http://localhost:8080/jcs/test-info/info?t=1519957548721
Request Method:GET
Status Code:200 
Remote Address:[::1]:8080
Referrer Policy:no-referrer-when-downgrade`
`Request URL:ws://localhost:8080/jcs/test-info/327/ytsc34dk/websocket
Request Method:GET
Status Code:101 `

If I user proxy , the first one would return 200 since it proxy to 8088 correctly:
`Request URL:http://10.8.8.75:9528/jcs/websocket/info?t=1519959085127
Request Method:GET
Status Code:200 OK
Remote Address:10.8.8.75:9528
Referrer Policy:no-referrer-when-downgrade`
the second one will not return 101:
`Request URL:ws://10.8.8.75:9528/jcs/websocket/204/drp3cmqo/websocket` 
and I will get this error in console:
`WebSocket connection to 'ws://10.8.8.75:9528/jcs/websocket/204/drp3cmqo/websocket' failed: Connection closed before receiving a handshake response`

Please help me out, it takes me almost a whole day with no luck :(

**Comment by chris4dd** [comment]
Fixed by setAllowedOrigins in the javaside

**Comment by shouldbai** [comment]
goodjob
