### ISSUE TITLE
How does the middleware parse the target URL?

### ISSUE THREAD

**Issue by TaroWong** [chimurai/http-proxy-middleware#246]
Hi @chimurai , thanks for creating and maintaining this module. 

I am using express as my server with `http-proxy-middleware` to call [Metaweather API ](https://www.metaweather.com/api/).

The problem is that I was able to get data from the endpoints below

- https://www.metaweather.com/api/location/2487956/
- https://www.metaweather.com/api/location/2487956/2013/4/30/

But when I try to call the API from https://www.metaweather.com/api/location/search/?lattlong=36.96,-122.02 

I get the error below which lead me thinking that the proxy added some values after `122.02` as it was not closed with `/`
```
SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data[Learn More] 
```
### Setup

* http-proxy-middleware: _0.17.4_
* server: _express_ + _4.15.3_
* next: _latest_

#### proxy middleware configuration
```javascript
const devProxy = {
  "/api": {
    target: "https://www.metaweather.com/api/location/search/?lattlong=36.96,-122.02",
    pathRewrite: { "^/api": "/" },
    changeOrigin: true
  }
};
```
#### server mounting
```javascript
const port = parseInt(process.env.PORT, 10) || 3000;
const env = process.env.NODE_ENV;
const dev = env !== "production";
const app = next({
  dir: ".", // base directory where everything is, could move to src later
  dev
});

const handle = app.getRequestHandler();

let server;
app
  .prepare()
  .then(() => {
    server = express();

    // Set up the proxy.
    if (dev && devProxy) {
      const proxyMiddleware = require("http-proxy-middleware");
      Object.keys(devProxy).forEach(function(context) {
        server.use(proxyMiddleware(context, devProxy[context]));
      });
    }

    // Default catch-all handler to allow Next.js to handle all other routes
    server.all("*", (req, res) => handle(req, res));

    server.listen(port, err => {
      if (err) {
        throw err;
      }
      console.log(`> Ready on port ${port} [${env}]`);
    });
  })
  .catch(err => {
    console.log("An error occurred, unable to start the server");
    console.log(err);
  });
```

Thanks for looking into this issue.

**Comment by TaroWong** [comment]
I have tried using `node-http-proxy` and got a different error. 

https://github.com/nodejitsu/node-http-proxy/issues/1239

**Comment by chimurai** [comment]
`target` is passed to the `http-proxy` library. With the `router` option you can make it dynamic.

`target` shouldn't contain query parameters... 
Think that is causing the issue. Just pass the protocol + host should be enough:
`target: "https://www.metaweather.com"`

Maybe add `secure: false` if you run into SSL issues.

**Comment by TaroWong** [comment]
Hi @chimurai , 

Thanks for sharing that! So if I would like to call `https://www.metaweather.com/api/location/search/?lattlong=36.96,-122.02`. 

I would just fetch `/api/location/search/?lattlong=36.96,-122.02`?

**Comment by chimurai** [comment]
That should work.
Check out https://github.com/chimurai/http-proxy-middleware/blob/master/examples/express/index.js for a working example.
