### ISSUE TITLE
add caching

### ISSUE THREAD

**Issue by trickydisco78** [chimurai/http-proxy-middleware#252]
Anyone managed to add caching to the onProxyReq option?

I've added a memory caching function to onProxyReq

#### proxy middleware configuration
```javascript
var cache = duration => {
  return (proxyReq, req, res) => {
    let key = '__express__' + proxyReq.path || proxyReq.url;
    //console.log(proxyReq);
    console.log(key);
    let cachedBody = mcache.get(key);
    console.log(cachedBody);
    if (cachedBody) {
      console.log('use cache');
      res.send(cachedBody);
      return;
    } else {
      console.log('set cache');
      //console.log(body);
      console.log(res.send);
      res.sendResponse = res.send;
      res.send = body => {
        console.log(body);
        mcache.put(key, body, duration * 5000);
        console.log('set cache');
        res.sendResponse(body);
        return;
      };
    }
  };
};

onProxyReq: cache(10),
```

It looks like it's not grabbing the body information or getting to set the cache at 
```
mcache.put(key, body, duration * 5000);
```
body comes up as null as wel

Any ideas?

**Comment by trickydisco78** [comment]
I've managed to do this using the apicache npm module

**Comment by liorbd** [comment]
@trickydisco78 can you share your solution?

**Comment by trickydisco78** [comment]
Yep: here: https://glitch.com/~flint-garage

But i've now found this which is much better : https://github.com/daniloc/airtable-api-proxy

**Comment by sebtoombs** [comment]
If anybody finds this in 2019, I came up with a solution I think works well. I'm using express and http-proxy-middleware. Essentially the cache middleware just runs before the proxy middleware. The only tricky part is getting the response from the proxy. Here's my solution:

```
server.use(
        '/proxypath',
        cacheMiddleware(10),
        proxyMiddleware
);
```

```
//cacheMiddleware
var mcache = require('memory-cache');

var cacheMiddleware = (duration) => {
    return (req, res, next) => {
        if(req.method !== "GET") return next();

        let key = '__proxy_cache__' + req.originalUrl || req.url

        let cachedBody = mcache.get(key)
        if (cachedBody) {
            res.send(cachedBody)
        } else {

            var _end = res.end;
            var _write = res.write;
            var buffer = new Buffer.alloc(0);
            // Rewrite response method and get the content.
            res.write = function (data) {
                buffer = Buffer.concat([buffer, data]);
            };
            res.end = function() {
                var body = buffer.toString();
                mcache.put(key, body, duration * 1000);
                _write.call(res, body);
                _end.call(res);
            };
            next()
        }
    }
}
```

```
//ProxyMiddleware eg
var proxyMiddleware = proxy({
    target: 'http://localhost:3000/'
});
```


This is simply using the proxyMiddleware as per the examples, but running a cache middleware first. The cache middleware (only for GET requests) checks if the path is in cache, and if so returns the body from cache and ends the route handler. If it's not in cache it passes on to the proxy handler, but first modifies the res.end (there are other ways to do this, but this seems to be the most reliable?) function to grab a copy of the response body and store in cache.

**Comment by dptoot** [comment]
@sebtoombs I like your solution but seem to be getting an ```incorrect header check``` error... any ideas or experience?  google search is not helping me :(

**Comment by animhotep** [comment]
`res.send is not a function`
this function is working for me now
`function cache(req, res, next) {
        if(req.method !== 'GET') return next();

        let key = '__proxy_cache1__' + req.originalUrl || req.url;

        let cachedBody = mcache.get(key);
        if (cachedBody) {
            console.log('from cache =>> ', req.originalUrl);
            res.writeHead(200, {'Content-Type': 'application/json'});
            res.send(cachedBody);
            res.end();
            next();
        } else {
            console.log('cached', req.originalUrl);
            var _end = res.end;
            var _write = res.write;
            var buffer = new Buffer.alloc(0);
            // Rewrite response method and get the content.
            res.write = function (data) {
                buffer = Buffer.concat([buffer, data]);
            };
            res.end = function () {
                var body = buffer.toString();
                mcache.put(key, body);
                _write.call(res, body);
                _end.call(res);
            };
            next();
        }
    }`
