### ISSUE TITLE
Webpack dev server proxy not working

### ISSUE THREAD

**Issue by VishalGulati** [chimurai/http-proxy-middleware#254]
I am trying to set webpack dev server proxy. However, I am getting following error:

    Error occurred while trying to proxy to: localhost:8080/abc/v1/user/search/?id=123122

Here is my webpack devserver config:

        proxy:  {
            "^/abc/v1/**":  "https://my-services.net/",
            changeOrigin: true,
            secure: false
        }

I get following error in VS Code IDE:

    [HPM] Error occurred while trying to proxy request (UNABLE_TO_VERIFY_LEAF_SIGNATURE)

As mentioned in various posts, I have tried following solutions but none seems to help:

    'process.env': {
        'NODE_TLS_REJECT_UNAUTHORIZED': '0'
    }

    strict-ssl=false

I am using webpack-dev-server version **2.11.2**.

cc: @chimurai

**Comment by chimurai** [comment]
Looks like a https certificate issue in you setup; Not a bug in http-proxy-middleware...
Think stackoverflow would be a better place to troubleshoot this.
