### ISSUE TITLE
Proxy localhost:port -> subdomain.localhost:another_port doesn't work

### ISSUE THREAD

**Issue by PetrShypila** [chimurai/http-proxy-middleware#256]
### Expected behavior
I have two running dev servers on localhost. I need to proxy a request from `localhost:4000` to `subdomain.localhost:3000`

### Actual behavior
On server launch I receive:
`[HPM] Proxy created: /  ->  http://agent.localhost:3000`
On request I see following message in console:
```[HPM] Error occurred while trying to proxy request /config from localhost:4000 to http://agent.localhost:3000 (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)```
And in a browser I receive following `504` response:
`Error occurred while trying to proxy to: localhost:4000/config`

At the same time requesting that endpoint in Chrome works fine.
### Setup

* http-proxy-middleware: 0.18.0
* server: express@4.16.2
* webpack-dev-middleware@3.1.0

#### proxy middleware configuration
```javascript
  app.use(require('webpack-dev-middleware')(compiler, {
    noInfo: true,
    publicPath: config.output.publicPath
  }));
  app.use(require('webpack-hot-middleware')(compiler));

  config.devServer.proxyConf.endpoints.forEach((endpoint) => {
    app.use(endpoint, proxy(config.devServer.proxyConf.config));
  });
```
```javascript
  proxyConf: {
    endpoints: [
      "/config",
    ],
    config: {
      target: "http://agent.localhost:3000",
      secure: false,
      changeOrigin: true
    },
  }
```

#### server mounting
```javascript
  app.listen(port, function (err) {
    if(err) {
      console.log(`Error during app launch: ${err.message}`.red);
    } else {
      console.log(`Server is listening on ${port}...`.green);
    }
  });
```

**Comment by simpslandyy** [comment]
Has anyone found a solution to this issue yet?
I'm also getting a ENOTFOUND error, but my target is slightly different, but more or less the same concept.

**Comment by chimurai** [comment]
Care to create a minimal working setup so it can be investigated?

**Comment by PetrShypila** [comment]
Afterall I just started to proxy to another environment. So solution wasn't found

**Comment by dominicfraser** [comment]
Is this helpful? 

https://stackoverflow.com/questions/36745592/node-http-proxy-middleware-not-working-with-local-servers-as-targert

**Comment by a-type** [comment]
I've hit this as well. My path is correct for the target server. I can hit the same endpoint in Chrome (`admin.localhost:8080`), but the proxy middleware will not route it.

**Comment by prem-prakash** [comment]
putting my local subdomains on hosts file solved the issue to me, not the best solution but ok
