### ISSUE TITLE
Log levels

### ISSUE THREAD

**Issue by chimurai** [chimurai/http-proxy-middleware#26]
Introduce `option.logLevel`:
* debug
* info
* warn
* error
* silent

Ability to control the log levels or disable logging.

**Comment by GryfonN** [comment]
yes very good idea, I would like to see the pairs of addresses in log somewhere that were redirected

**Comment by chimurai** [comment]
Can you create a new issue for logging the pairs of addresses? (Keeping issues/discussions separate :D)

Would be great if you can provide some logging examples to clarify exactly what information would be useful in the log statements.
