### ISSUE TITLE
Proxy absolute assets

### ISSUE THREAD

**Issue by robdonn** [chimurai/http-proxy-middleware#260]
### Expected behavior

If the proxy returns a html page which has an asset that uses an absolute address, the proxy should rewire it.

### Actual behavior

The browser tries to grab the asset from the proxy server root rather than the target root.

### Setup

http://site1.com/proxy --> http://site2.com

- index.html - site2.com
```html
<html>
	<head>
		...
		<link rel="stylesheet" href="/assets/styles.css" />
		...
	</head>
	<body>
		...
	</body>
</html>
```

The browser tries to serve `http://site1.com/assets/styles.css` rather than `http://site1.com/proxy/assets/styles.css`

* http-proxy-middleware: _0.18.0_
* server: _express: 4.16.2_
* other relevant modules

#### proxy middleware configuration
```javascript
var apiProxy = proxy({
    pathRewrite: {
      '^/proxy': '/',
    },
    target: `http://site2.com`,
  })
```
#### server mounting
```javascript
var app = express();

app.use('/proxy', apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
absolute address ([rfc3986 absolute URI](https://tools.ietf.org/html/rfc3986#section-4.3)) will work.

You'll have to rewrite the .html and rewrite those paths or the page should use absolute/relative paths.
