### ISSUE TITLE
getting error: ERR_CONTENT_LENGTH_MISMATCH when modifying the output

### ISSUE THREAD

**Issue by zeuscronos** [chimurai/http-proxy-middleware#268]
### Expected behavior

When going to:
http://localhost:3002

I should see: "This server is now running on port: 3002"

### Actual behavior

The browser cannot go thru and raises the error: `ERR_CONTENT_LENGTH_MISMATCH`
(Google Chrome is a good browser to see this error (very explicit))

### Description of the issue

First I did a dummy http server you can try here:

http://localhost:3001

Then, when going to the proxy server:

http://localhost:3002

based on the terminal output (you can see it at the bottom)...

`res.setHeader('content-length', <content-length>);`

uses the proper value for: `<content-length>`, but the output is empty (content-length: 0) and I think this mismatch is what is causing this error.

Going deep on this...

If I set `res.setHeader('content-length', 0);` then there is no error.
Probably because the actual output is empty. Which makes the `content-length` match the actual output.

If I set `res.setHeader('content-length', output.length);` then there is an error. Probably because `output.length` is 40, but the actual output length is: 0.

### Setup

    http-proxy-middleware: 0.18.0
    server: express 4.16.3

    // run
    $ node 01.js

file content: **01.js**

    var express = require('express');
    var http = require('http');
    var proxy = require('http-proxy-middleware');
    
    function bodyTransform(body) {
    	body = body.replace('is running', 'is now running');
    	body = body.replace('3001', '3002');
    	return body;
    }
    
    var onProxyRes = (proxyRes, req, res) => {
    
    	const _writeHead = res.writeHead;
    	const _end = res.end;
    	var buffer = new Buffer('');
    	let body = '';
    
    	proxyRes.on('data', (chunk) => {
    		console.log("inside: .on('data', ...)");
    		buffer = Buffer.concat([buffer, chunk]);
    	});
    	proxyRes.on('end', () => {
    		console.log("inside: .on('end', ...)");
    		body = buffer.toString('utf8');
    	});
    
    	// defer writeHead
    	res.writeHead = (...writeHeadArgs) => {
    		const output = bodyTransform(body);
    		if (proxyRes.headers && proxyRes.headers['content-length']) {
    			// if 'content-length' is set to: 'output.length' it causes:
    			// ERR_CONTENT_LENGTH_MISMATCH (Google Chrome is explicit about the error)
    			// because it seems that the actual content output is an empty string (length: 0)
    			res.setHeader('content-length', output.length);
    			console.log('assigned => content-length: ' + output.length);
    
    			// if the following line is uncommented, there are no errors
    			// because it seems that the actual content output is an empty string (length: 0)
    			// so the 'content-length' will match
    			// res.setHeader('content-length', 0);
    		}
    		// disabling chunked encoding
    		res.setHeader('transfer-encoding', '');
    		// disabling cache for all http as well
    		res.setHeader('cache-control', 'no-cache');
    		_writeHead.apply(res, writeHeadArgs);
    	};
    
    	// defer all writes
    	res.write = (chunk) => { };
    
    	res.end = (...endArgs) => {
    		const output = bodyTransform(body);
    		if (body.length) {
    			_end.apply(res, [output]);
    		}
    		else {
    			_end.apply(res, endArgs);
    		}
    		console.log('after: _end.apply(...);');
    	};
    }
    
    const portApp01 = 3001;
    const app01 = express()
    app01.get('/', (req, res) => {
    	res.send('This server is running on port: 3001');
    });
    app01.listen(portApp01, () => {
    	console.log('app01 is listening on port: ' + portApp01);
    });
    
    const portProxy = 3002;
    const appProxy = express()
    appProxy.use(proxy('/', { target: 'http://localhost:3001', onProxyRes: onProxyRes }));
    http.createServer(appProxy).listen(portProxy, function () {
    	console.log('appProxy is listening on port: ' + portProxy);
    });

Terminal output:

    inside: .on('data', ...)
    inside: .on('end', ...)
    assigned => content-length: 40
    after: _end.apply(...);

Could you check that?

I'm just trying to change the response.
In case it is my fault could you let me know what's my mistake?

I really appreciate your help.

Thanks!

**Comment by chimurai** [comment]
Hi @zeuscronos,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
