### ISSUE TITLE
 failed: Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by gauseen** [chimurai/http-proxy-middleware#269]
my config
```js
var express = require('express');
var proxy = require('http-proxy-middleware');

var wsProxy = proxy('/', {
	target: 'http://preview-hgpos.behuntergatherer.com',
	changeOrigin: true, // for vhosted sites, changes host header to match to target's host
	ws: true, // enable websocket proxy
	logLevel: 'debug'
})

var app = express()
app.use('/', express.static(__dirname))
app.use(wsProxy) // add the proxy to express

var server = app.listen(8070)
server.on('upgrade', wsProxy.upgrade) // optional: upgrade externally
```

my terminal
```sh
 Proxy created: /  ->  http://preview-hgpos.behuntergatherer.com
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
[DEMO] Server: listening on port 3000
[DEMO] Opening: http://localhost:3000
[HPM] GET /websocket/webSocketIMServer -> http://preview-hgpos.behuntergatherer.com
[HPM] Upgrading to WebSocket
```

browser console error
```js
WebSocket connection to 'ws://localhost:8070/websocket/webSocketIMServer' failed: Error during WebSocket handshake: Unexpected response code: 403
```
I need help, Thx!

**Comment by datacabinet** [comment]
I am facing another websocket error:
On the console:
kernel.js:461 WebSocket connection to 'wss://mondaytest.datacabinet.systems/jupyterproxy/8888/api/kernels/322058d6-4375-4c4d-97a2-2177d51eb225/channels?session_id=7AEECF5B67EE41B78140847CC99DB1F9' failed: Error during WebSocket handshake: Invalid status line

On the cloud:
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Upgrading to WebSocket
[HPM] Error occurred while trying to proxy request /jupyterproxy/8888/api/kernels/322058d6-4375-4c4d-97a2-2177d51eb225/channels?session_id=A6BE4AAC52144BFDA9BF8586893A4A0E from mondaytest.datacabinet.systems to http://localhost:8890 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)10:10:05 PM INFO ip:34.217.46.12 cloud:AWS
	{"ResponseMetadata":{"RequestId":"dbc6757d-70e8-11e8-b764-e1cfd7ce25b4"}}

**Comment by gauseen** [comment]
我的问题已经解决，因为后端框架websocket限制了其他域请求，后端把限制去掉就可以连接了

**Comment by aral** [comment]
To translate the last comment: “My problem has been solved because the backend framework restricts websocket requests from other domains, and the backend can be connected by removing the restrictions.”

**Comment by kellywang1234** [comment]
@gauseen @aral could you be more specific on how to remove the backend framework? i have the same handshake issue while using http-proxy-middleware. Thank you!!

**Comment by aral** [comment]
@kellywang1234 I’m sorry, I don’t remember what this was about. Perhaps the original poster does (CC @gauseen).

I wonder, based on the last comment, if it was a CORS issue.

**Comment by gauseen** [comment]
@kellywang1234 不好意思，时间太久忘记了，好像是跨域的问题，配置一下 CORS 就可以了
