### ISSUE TITLE
django-rest-framework filters disappeared after proxy

### ISSUE THREAD

**Issue by misakamaiyako** [chimurai/http-proxy-middleware#270]
### Expected behavior
 the filters of the framework is able to see in the page
### Actual behavior
 only input is visible and  the sever seems lost the params
### Setup

* http-proxy-middleware: 0.17.4
* server:  Express 4.16.3
* other relevant modules
* webpack-dev-server@2.11.2

#### proxy middleware configuration
```javascript

    devServer:{
        proxy:{
            '/api':{
                target: 'http://xxx.hospital.bimsheng.com',
                pathRewrite: {
                    '^/api' : ''
                }
            }
        },
    },
```
#### server mounting
```javascript
webpack/vue default setup
```

**Comment by chimurai** [comment]
Not really sure what you mean with disappearing filters...

If this is a issue in your setup, StackOverflow is a better place to troubleshoot it.

If you think it's a bug in http-proxy-middleware, please provide a minimal reproducible setup so it can be investigated.

Thanks!

**Comment by misakamaiyako** [comment]
i am so sorry,it's an error width NGINX's agency,it directed me to the wrong ip.emmm ,but i still can't understand why it go to the wrong ip,it's ok to visit the website by browser.is there any different between browser and proxyTable?

**Comment by chimurai** [comment]
Closing stale issue.
Feel free to re-open.
