### ISSUE TITLE
Dynamically change target via request headers

### ISSUE THREAD

**Issue by kunokdev** [chimurai/http-proxy-middleware#273]
Is there any way to dynamically change target depending on request headers? 

PS. I tried your router thing, but for it, I still need to predefine urls, however I need them to be fully dynamic.

**Comment by UseHandsfree** [comment]
You should still be able to define fully dynamic targets with the router, as it accepts the request, from which you can grab the headers. So, something like this:

```js
app.use(proxy({
  target: 'http://example.com',
  router (req) => {
    let newTarget = req.headers['my-header-containing-the-url-or-flag']
    // ... transformation logic ... //
    return newTarget
  }
})
```

**Comment by kunokdev** [comment]
@UseHandsfree Thanks, that works well!
