### ISSUE TITLE
Middleware is not rewriting requests for index.html 

### ISSUE THREAD

**Issue by Steveiwonder** [chimurai/http-proxy-middleware#279]
### Expected behavior
Should rewrite request to https://localhost/app/index.html
### Actual behavior
Request is handled by local web pack server and not rewritten
### Setup

* http-proxy-middleware: http-proxy-middleware@0.18.0
* server: webpack-dev-server@^3.1.4"
* angular 6

#### proxy middleware configuration
```javascript
const PROXY_CONFIG = [
  {
    context: [
      '/client-config',
      '/api',
      '/brand',
      'index.html'
    ],
    'target': 'https://localhost/app/',
    'autoRewrite': true,
    'secure': false,
    'changeOrigin': false,
    'logLevel': 'debug',
    'bypass': function (req, res, proxyOptions) {
    }
  }
];

module.exports = PROXY_CONFIG;
```

The proxy middleware seems to completely ignore requests for index.html and hands them off to the web pack dev server. The other routes define (client-config,brand, api) all work

**Comment by deissh** [comment]
I have this bug too.

**Comment by chimurai** [comment]
A slash should be added to: `/index.html`
