### ISSUE TITLE
Proxy image

### ISSUE THREAD

**Issue by markolofsen** [chimurai/http-proxy-middleware#283]
### Expected behavior
Strange behavior. In first case I received image from proxy, in another one not. All images really exist.

Existed paths:
http://127.0.0.1:1234/media/cache/cf/e3/cfe3b75478e1ee04f7156a4998b43603.jpg
http://127.0.0.1:1234/media/cache/e2/9c/e29c57b02bc58087c468e177d139736a.jpg

Call with proxy:
http://127.0.0.1:3000/media/cache/cf/e3/cfe3b75478e1ee04f7156a4998b43603.jpg <— available
http://127.0.0.1:3000/media/cache/e2/9c/e29c57b02bc58087c468e177d139736a.jpg <— not available

### Setup

* http-proxy-middleware: 0.18.0
* server: express 4.16.2

#### proxy middleware configuration
```javascript
const apiDomain = 'http://127.0.0.1:1234'
// .......
server.use('/media/', proxy({
          target: apiDomain,
          changeOrigin: true,
          secure: false,
          xfwd: true,
        }))
```
#### server mounting
```javascript
var app = express();

app.use(apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
Doesn't sounds like a bug in HPM.

Suggest using Stackoverflow for troubleshooting your setup.

**Comment by markolofsen** [comment]
@chimurai It's maybe it not a bug, but I'm sure problem in middleware. Works partly ...

**Comment by chimurai** [comment]
Can you make a reproducible/isolated working setup? So it can be investigated?

**Comment by chimurai** [comment]
Issue has gone stale; Closing issue.
Feel free to re-open.
