### ISSUE TITLE
Host name verification

### ISSUE THREAD

**Issue by johndc7** [chimurai/http-proxy-middleware#284]
Should have an option to check for a host name instead of just a path.

For example:
`proxy('example.com',{target:'http://example2.com'})`

This would resolve an issue where websockets are upgraded when they shouldn't be. The `shouldProxy` function in `index.js` only checks for a path. This causes an issue when using this with multiple domains as it will attempt to proxy websockets for other domains.

Example:
```
var testProxy = proxy({target:'http://example2.com', ws: true});
app.use(function(req, res, next){
    if(req.hostname == 'example.com')  testProxy(req,res,next);
    else res.send("Hello world");
});
```

In this example, any websocket would be proxied to http://example2.com since `testProxy` is listening for all upgrades but not checking for the host.

**Comment by chimurai** [comment]
This configuration `proxy('example.com', {target:'http://example2.com'})` checks for the path `example.com`... not `host`.

Provide your own function for custom filtering; in your case checking for hostname.
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md#custom-filtering

**Comment by johndc7** [comment]
I looked through the documentation but didn't see that. Thanks.

**Comment by EddieOne** [comment]
Does the router check the host?

**Comment by johndc7** [comment]
What router are you referring to? If you are referring to the router in express, it does not.

**Comment by EddieOne** [comment]
For something like this

```
var test2 = proxy('localhost:80', {
  target: 'http://example.com',
  router: {
    'test1.localhost': 'example2.com',
    'test2.localhost': 'http://google.com',
  }
});
```

**Comment by johndc7** [comment]
I have personally never used that feature, but it appears to override the target. So in the case of your example, it would go to the default.com unless it is somedomain.com someotherdomain.com. It would then go to either 0.0.0.0:3000 or 0.0.0.0:3001 respectively.

**Comment by Empowerful** [comment]
> This configuration `proxy('example.com', {target:'http://example2.com'})` checks for the path `example.com`... not `host`.
> 
> Provide your own function for custom filtering; in your case checking for hostname.
> https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md#custom-filtering

This doesn't work because the custom function is given the pathname without the host:

https://github.com/chimurai/http-proxy-middleware/blob/3b9730826187c708fbd16cb0baa588f6aad73a00/src/context-matcher.ts#L30-L34

**Comment by EddieOne** [comment]
I had better luck using node-http-proxy
