### ISSUE TITLE
query match instead the path

### ISSUE THREAD

**Issue by santosh0705** [chimurai/http-proxy-middleware#286]
This is not an issue but a question.
Is it possible to match a query string and proxy the same?

Like if the url matches `/?q=config` it should proxy it to some other port but the `/` itself should not be proxied.

**Comment by chimurai** [comment]
Think `router` is what you're looking for: 
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md#custom-router-function

**Comment by santosh0705** [comment]
Hi @chimurai thanks for your reply. I'm using http-proxy-middleware only during the development of frontend.
The backend is completely isolated from the frontend and not written in node. The frontend is plain HTML and JS only which is served by webpack devserver during development.
I tried to create a custom proxy function for it but I realise that the webroot is not considered here. Below is my sample webpack devserver configuration:
```
    devServer: {
      host: '0.0.0.0',
      port: 8080,
      proxy: [
        {
          context: function(pathname, req) {
            console.log("url: " + req.url +"\n")
            return !!req.url.match(/^\/\?q=config$/)
          },
          target: 'http://127.0.0.1:7681'
        },
        {
          context: ['/ws', '/auth_token.js'],
          target: 'http://127.0.0.1:7681',
          ws: true
        }
      ]
    }
```
I got surprised that the webroot is not printed on console.
This is the first time i'm using this middleware so i'm not knowing is this the normal or it is missing somehow.

**Comment by santosh0705** [comment]
@chimurai is there any possibility to proxy the webroot?

**Comment by santosh0705** [comment]
I didn't get any solution native to http-proxy-middleware so I did a workaround. Hoping this would help someone stopping by this issue.
This is my webpack devserver configuration:

```
devServer: {
      host: '0.0.0.0',
      port: 8080,
      before: function (app) {
        app.get('/', function (req, res, next) {
          if (Object.keys(req.query).length > 0) {
            res.redirect('/redir' + req.url)
          }
          return next()
        })
      },
      proxy: [
        {
          context: '/redir',
          pathRewrite: {
            '^/redir': '/'
          },
          target: 'http://127.0.0.1:7681'
        },
        {
          context: ['/ws', '/auth_token.js'],
          target: 'http://127.0.0.1:7681',
          ws: true
        }
      ]
    }
```
