### ISSUE TITLE
inconsistency

### ISSUE THREAD

**Issue by sahanDissanayake** [chimurai/http-proxy-middleware#291]
Hi there

```
var wsProxy = proxy('/', {target: 'ws://echo.websocket.org', changeOrigin:true});
app.use(wsProxy);
```
this works fine and I could proxy everything just fine, But what I need is to proxy through all requests to `/api`

```
var wsProxy = proxy('/api', {target: 'ws://echo.websocket.org', changeOrigin:true});
app.use(wsProxy);
```
surprisingly this doesn't work

any thoughts on why please ?

**Comment by dtm5011** [comment]
@sahanDissanayake did you ever find a solution to this?

**Comment by chimurai** [comment]
You'll have to subscribe to the `upgrade` event manually: https://github.com/chimurai/http-proxy-middleware#external-websocket-upgrade
