### ISSUE TITLE
The "target" is "http" but at the target side, it gets "https"

### ISSUE THREAD

**Issue by ilovepumpkin** [chimurai/http-proxy-middleware#295]
I think this is a question, not a bug, but I do need a solution. 

Say, my initial request url is **https**://host1/test, and in http-proxy-middleware, the "target" is "**http**://host2". In host application (Java), there is one line code to get "baseUrl"

`final String baseUrl = containerRequestContext.getUriInfo().getBaseUri().toString().trim();`

I expect "baseUrl" is "**http**://host2", but now I got "**https**://host2". host2 is both accessible via http or https. But since my target is specifiying "http", why I get "https"? Is there any option to let me get "http" for baseUrl. I reviewed all the proxy options, nothing seems helpful. 

Anyone has idea about this problem? Thanks!

**Comment by chimurai** [comment]
Think you server is configured to redirect http requests to https
