### ISSUE TITLE
websocket proxy

### ISSUE THREAD

**Issue by miladmeidanshahi** [chimurai/http-proxy-middleware#296]
Hi i have a WebSocket and  i want to proxy in my development server i set this config
```
devServer: {
        proxy: {
                '/websocket': {
                       target: 'ws://127.0.0.1:8000/websocket', // example
                       changeOrigin: true,
                       secure: false,
                       ws: true
                }
        }
}
```
and for client:
```
new WebSocket('/weboscket')
```
but it doesn't work how can i proxy that ?

**Comment by chenendian** [comment]
me too  ， who can help me?

**Comment by chenendian** [comment]
Have you solved the problem?

**Comment by miladmeidanshahi** [comment]
@chimurai please check this

**Comment by cedricVu** [comment]
`target: proxy.TARGETS.PLAYERDUO_SERVICE,
    changeOrigin: true,
    ws: true,
    secure: false,
    pathRewrite: {
        '^/player-service' : '',
    }`
client: 
`io.connect('http://localhost:4001', { path: '/socket/player-service'});`
It's working for me.

**Comment by chimurai** [comment]
Hi @miladmeidanshahi,

Thank you for your question.

Please use StackOverflow. I think that would be a better place to troubleshoot your setup.
If you think it is a bug, can use the [issue_template](https://github.com/chimurai/http-proxy-middleware/blob/master/.github/ISSUE_TEMPLATE.md) to create a ticket.

Thanks.

/cc @chenendian
