### ISSUE TITLE
Cannot match URL without period

### ISSUE THREAD

**Issue by kradalby** [chimurai/http-proxy-middleware#297]
### Is this a bug report?

Yes

### Steps to reproduce

I am trying to match the url: 
`api/0.1/locations/katwijk-zh/bushalte-estec/departure-times?lang=en-GB`

with the following code: 
```
proxy(
    '/api',
    {
        logLevel: 'debug',
        target: 'http://api.9292.nl',
        changeOrigin: true,
        pathRewrite: {'^/api': ''}
    }
)
```

But the URL never matches. However, if I do something weird like adding a dot in parts of the url, it matches.

e.g.:
`api/0.1/locations/katwijk-zh/bushalte-estec/departure-times?lang=en-GB` does not match
`api/0.1/locations/katwijk-zh/bushalte-estec/departure-times.js?lang=en-GB` does match (but obviously fail with the api as it is incorrect)

### Expected behavior
I expect that `api/0.1/locations/katwijk-zh/bushalte-estec/departure-times?lang=en-GB` will match with '/api' or '/api/**'

### Actual behavior
Does not match, but matched with some permutations of the url.

### Setup

* http-proxy-middleware: 0.19.0
* http-proxy-middleware configuration: above
* server: webpack-serve

#### client info
macOS 10.13.6
curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0
Safari

#### target server info
9292.nl's api server, details unknown

**Comment by kradalby** [comment]
I cannot reproduce it with express.
After looking more closely, it looks like webpack-serve uses the koa server and I use a connect module `"koa-connect": "^2.0.1"` to glue together your proxy middleware.

I am however starting to think that something weird is happening preventing some of the routes to even make it to the middleware. Does this make sense? I have tried to use something else than `/api`, but it does not help.

**Comment by chimurai** [comment]
Thanks for looking more closely.
Not sure what's happening exactly when implemented in koa.

Will need to investigate this.

Can you reproduce it in a isolated koa + http-proxy-middleware setup?

**Comment by kradalby** [comment]
The webpack-serve plugin was just [deprecated](https://github.com/webpack-contrib/webpack-serve/commit/edaf28c6c935c3e29d26dbb02a9d6b672cc5148a) (4 hours ago). Switching to webpack-dev-server solves the issue.

Thanks for the help :)

**Comment by chimurai** [comment]
That's interesting news. Thanks for the update!

**Comment by shellscape** [comment]
@kradalby (and anyone else that happens across this issue) `webpack-serve` was/is not a plugin. it was/is a strand-alone module.
