### ISSUE TITLE
Cannot proxy after parsing body

### ISSUE THREAD

**Issue by connelhooley** [chimurai/http-proxy-middleware#299]
I cannot re-send a proxied request's body after I have parsed it.

Using this [recipe](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/modify-post.md), this [comment](https://github.com/chimurai/http-proxy-middleware/issues/202#issuecomment-330405028) and this [comment](https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-249430255) I have written the following example:

``` js
import express from 'express';
import proxy from 'http-proxy-middleware';
import bodyParser from 'body-parser'

const app = express();
app.use(bodyParser.json());
app.post('*', proxy({
    target: 'http://target.here.com',
    secure: false,
    onProxyReq: (proxyReq, req) => {
        if (req.body) {
            const bodyData = JSON.stringify(req.body);
            proxyReq.setHeader('Content-Type','application/json');
            proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
            proxyReq.write(bodyData);
        }
    }
}));
app.listen(2001, () => console.log('Listening'));
```

I get an error when trying to set the first header on the `proxyReq` saying: `Cannot set headers after they are sent to the client`. 

If that is the case how does the [recipe](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/modify-post.md) work?

**Comment by connelhooley** [comment]
Looks related to:
https://github.com/nodejitsu/node-http-proxy/issues/1279

**Comment by SBRK** [comment]
+1 got the same issue. Moving the middlewares before body.json works

**Comment by connelhooley** [comment]
> +1 got the same issue. Moving the middlewares before body.json works

Yes that's correct. I need to parse the body to know if I need to proxy the request though.

**Comment by windix** [comment]
If need to parse the body before proxy, I have followed suggestion from this issue: https://github.com/chimurai/http-proxy-middleware/issues/177#issuecomment-420423934

**Comment by taozhi8833998** [comment]
same issue

**Comment by ThalesMatoso** [comment]
+1

**Comment by XiaoweiLiu0812** [comment]
+1

**Comment by stuartZhang** [comment]
This is my solution: https://github.com/stuartZhang/coexist-parser-proxy

**Comment by chimurai** [comment]
fixed in https://github.com/chimurai/http-proxy-middleware/pull/492

**Comment by phoenixstudiodz** [comment]
The solutions proposed here worked fine, but after adding an agent (sock5 `SocksProxyAgent` from `socks-proxy-agent`) I started getting ` Can't set headers after they are sent to the client`.
I fixed that by overriding `verify` in the bodyParser.
```javascript
//
const bodyParser = require('body-parser') 
const { Readable } = require('stream');
//
app.use(bodyParser.json({
  // verify function has access to buff that contains the stream
  // create a new readable stream and save it to streamBody
  verify: (req, res, buf, encoding) => {
  const readableStream = Readable.from(buf);
  req.streamBody = readableStream
 }
}));
 // Param "buffer" accept a stream if the original one was consumed
app.all("*", (req, res) => proxy.web(req, res, {
 target: "target-here",
 buffer: req.streamBody
}); 
```
