### ISSUE TITLE
Linter in param assign

### ISSUE THREAD

**Issue by amine2z** [chimurai/http-proxy-middleware#304]
### Is this a question?
Yes
Hello, first thanks for this great lib. When using it i was surprised that the linter dont agree with  the assignement of function variable from the doc.
`function onProxyRes(proxyRes, req, res) {
    proxyRes.headers['x-added'] = 'foobar';     // add new header to response
    delete proxyRes.headers['x-removed'];       // remove header from response
}`

I want to know if theres a solution to correct that in the lib. I can submit a MR for that.

thanks

**Comment by chimurai** [comment]
Types were externally managed by https://www.npmjs.com/package/@types/http-proxy-middleware

Nowadays there are included in `http-proxy-middleware`

Feel free to reopen if issue persists in latest version
