### ISSUE TITLE
Got "400 bad request" error on proxy requests

### ISSUE THREAD

**Issue by Scit** [chimurai/http-proxy-middleware#306]
Proxy requests end with 400 status (bad request) while I'm trying to fetch json-data.

### Proxy config:
```
const proxy = require('http-proxy-middleware');

module.exports = function(app) {
    app.use(proxy('/users',
      {
          target: 'https://api.github.com',
          secure: false
      }
    ));
};
```

### Fetch request:
`fetch('/users/example');`

### Fetch result:
`App.js:7 GET http://localhost:3000/users/example 400 (Bad Request)`

### Additional info:
lib version = 0.19.0

### Browser screenshot:
![screenshot at 2018-11-06 12-09-29](https://user-images.githubusercontent.com/661855/48054116-8ae2fb80-e1bd-11e8-8e1c-a1d668610f44.png)

**Comment by chimurai** [comment]
Looks like you need this:

```
💡 Tip: Set the option changeOrigin to true for name-based virtual hosted sites.
```

Please [README.md](https://github.com/chimurai/http-proxy-middleware/blob/master/README.md)
For help with your setup, please consider using StackOverflow
