### ISSUE TITLE
Cannot pass options to micromatch

### ISSUE THREAD

**Issue by Rody-Kirwan** [chimurai/http-proxy-middleware#307]
### Is this a question?

No

### Is this a bug report?

No

### Is this a feature request?

Yes

### Steps to reproduce

There is currently no way to pass options to micromatch via http-proxy-middleware options.
Because of this we are bound to using micromatch defaults which may not suit everyones needs.
As an example:

Any endpoint containing `/.` will fail the contextMatcher.match() and never reach the server.

(Write your steps here:)

1. Create an api endpoint '/.test'
2. Try to proxy a request e.g `localhost:3200/.test`
3. The browser will respond with an error Cannot Get /.test
4. The request never makes it past ` shouldProxy()` in index.js

### Expected behavior

Middleware should pass custom options to `micromatch` in `contextMatch.match()`
Something like:
```
matchOptions: {dot: true}
```
```
function shouldProxy(context, req, [options]) {
        var path = (req.originalUrl || req.url);
        return contextMatcher.match(context, path, req, [options]);
    }
```

(Write what you thought would happen.)

### Actual behavior

No options are passed to micromatch so defaults are always used

(Write what happened.)

### Setup

Setup is a basic webpack-dev-server setup:
```
devServer: {
    port: 5000,
    noInfo: true,
    logLevel: 'debug',
    proxy: {
      '*': {
        target: 'http://localhost:3000'
      }
    },
    stats: {
      colors: true
    },
  },
```

* http-proxy-middleware: v0.18.0
* http-proxy-middleware configuration
```
proxy: {
      '*': {
        target: 'http://localhost:3000'
      }
    },
```
* server: _connect/express/browser-sync..._ + _version_
* other relevant modules

#### client info

ReactJS application built with webpack 4
#### target server info

Express.js server running on node v8.12
### Reproducible Demo

https://github.com/Rody-Kirwan/http-proxy-middleware-dot-notation

**Comment by chimurai** [comment]
@Rody-Kirwan Thanks for the PR.

I have some doubts on passing options for transitive dependencies (in this case `micromatch`).
Limiting the library unnecessary.

If you use the middleware in express, you can provide your own `context` function, in which you can write your own logic and not being limited at all...
`app.use(proxy(context, options));`

In `webpack-dev-server` there is no way to provide your own `context`...  as you noticed.

To solve this I was thinking to move the `context` argument to the `options`; thus giving you the same, if not, more control on when you want requests to be proxied.

Maybe naming the option to `filter`, is probably a better semantic.

What do you think?

**Comment by Rody-Kirwan** [comment]
@chimurai Thank you for your reply. I apologise for the delay in responding.

I'm not sure I understand your solution... or at least how it would help in this situation.

The issue we are having is that requests to valid endpoints (that we wish to proxy) are being rejected by micromatch because of their specific format - in this case a "forwardslash" followed by "dot" `/.name`

The PR only propose to add an extra options param:
https://github.com/chimurai/http-proxy-middleware/pull/309/files

I don't see how this change limits the library - It does the opposite IMO as it allows us to pass valid options to micromatch `{ dot: true }`

So - using my forked `http-proxy-middleware` my webpack-config now looks like this:
```
devServer: {
    port: 3200,
    proxy: {
      '*': {
        target: 'http://localhost:3000',
        matchOptions: { dot: true }
    }
},
```

This works fine for us as a temp fix but there are obvious concerns when we are forking `webpack-dev-server` to pull in a fork of `http-proxy-middleware` :D 

Are you concerned that certain micro-match options may break the proxy?
If so we could possibly add functionality for specific options as needed....
```
// index.js
var matchOptions = _.pick(proxyOptions.matchOptions, ['dot'])
```

What do you think?

**Comment by Rody-Kirwan** [comment]
@chimurai after everything - It seems I can pass a `context` function from `webpack-dev-server`
The documentation is a little incorrect as the options need to be wrapped in an array for it to work
```
// From the docs (Not working)
proxy: {
   context: () => true,
   target: 'http://localhost:1234'
}
```

```
// Working
proxy: [{
   target: 'http://localhost:3000',
   context: () => true
}]
```

I guess this issue can be closed!

Thanks for your help

**Comment by chimurai** [comment]
Thanks for pointing out the webpack-dev-server configuration.
