### ISSUE TITLE
TL-DR example is not working

### ISSUE THREAD

**Issue by jakubjosef** [chimurai/http-proxy-middleware#312]
### Is this a bug report?
Yes it is.

TL DR example contains `app.use('/api', proxy({target: 'http://www.example.org', changeOrigin: true}));` which is not working as expected.

Correct syntax is `app.use(proxy('/api', {target: 'http://www.example.org', changeOrigin: true}));` for this example.

It's small issue, but it takes some time to fix it for me,  and it's not good to have bug in first TLDR example.

**Comment by adarrra** [comment]
it should work both way actually https://github.com/chimurai/http-proxy-middleware#appusepath-proxy
