### ISSUE TITLE
window.location.host ReferenceError: window is not defined

### ISSUE THREAD

**Issue by shahzad-sarwar** [chimurai/http-proxy-middleware#326]
Hi, Any help would be really appreciated on this issue.

I want to set the proxy target to 

`proxyTable: {
    '/api': {
    target: 'http://' +  window.location.hostname.split('.')[0] + '.example.com',
    changeOrigin: true,
    pathRewrite: {
      '^/api': ''
    }
  }
},`

and webpack is giving error ReferenceError: window is not defined

**Comment by chimurai** [comment]
All the configuration is ran on NodeJS; So that explains why `window` doesn't work.

**Comment by chimurai** [comment]
Closing issue.
Feel free to re-open.
