### ISSUE TITLE
Need help. proxy webSocket - Error: read ECONNRESET

### ISSUE THREAD

**Issue by yesongling** [chimurai/http-proxy-middleware#327]
### Is this a question?

Using HPM to proxy webSocket. But once webSocket server shut down, HPM server will catch this error and crash.

The root cause seem to be an error event has not been handled. But I dont know where to handle it.

**Env**
Node: 10.8.0
HPM: 0.19.0
System: Mac OS 10.13.6

**Error logs & config**
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onread (net.js:660:25)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

![image](https://user-images.githubusercontent.com/28178382/53710611-183b1180-3e79-11e9-9dec-570c0ca5b92c.png)

### Is this a bug report?

(write your answer here)

### Is this a feature request?

(write your answer here)

### Steps to reproduce

(Write your steps here:)

1. 2. 3.

### Expected behavior

(Write what you thought would happen.)

### Actual behavior

(Write what happened.)

### Setup

- http-proxy-middleware: _version_
- http-proxy-middleware configuration
- server: _connect/express/browser-sync..._ + _version_
- other relevant modules

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by yesongling** [comment]
Fixed.
Handle error on upgrade callback can fix it.
![image](https://user-images.githubusercontent.com/28178382/53711263-5128b580-3e7c-11e9-8c81-e306b2179d15.png)

**Comment by chimurai** [comment]
thanks for sharing your solution!
