### ISSUE TITLE
Websocket Proxy 404s Despite Following Examples

### ISSUE THREAD

**Issue by RVilgalysCrispin** [chimurai/http-proxy-middleware#334]
### Expected behavior

We are trying to use http-proxy-middleware to upgrade an older reverse proxy (running on Redbird) so that we can use express to provide token checks for most of the microservices we are proxying. 

It is 404-ing requests to websockets on a RabbitMQ messaging service. The IP is copied out of the old proxy and requests still work when that is switched back on. 

### Actual behavior

Http-proxy-middleware is logging that it is getting the reqests & upgrading them. Morgan is showing we are getting connections. It is still coming back with a 404. 

### Setup

We are running on express. Relevant code is here: 

```
const httpProxyMiddleware = require('http-proxy-middleware');
...
const wsProxy = httpProxyMiddleware('/rmq', {
    target: 'http://localhost:15674/ws',
    changeOrigin: true,
    autoRewrite: true,
    ws: true,
    logLevel: 'debug'
});
app.use('/rmq', wsProxy);
...
const server = app.listen(process.env.PORT, () => {
    console.log(`🍕🍔🍟 we are up and running on http://localhost:${process.env.PORT}`);
});
server.on('upgrade', (req, socket, head) => {
    console.log("upgrade request recieved");
    wsProxy.upgrade(req, socket, head);
});
```

#### client info

Happens in all clients. 

#### target server info

This is on express, running on a Windows VM. Appears to be running Node 9.8.0 so possible we need to update that, but was also packaged on Node 10 and still had issue. 

### Reproducible Demo

Unfortunately we develop for closed systems. Screenshots are below of the logs. 
![Capture](https://user-images.githubusercontent.com/49564091/56048407-74654100-5d15-11e9-81c6-964402ecfa36.PNG)
![Capture2](https://user-images.githubusercontent.com/49564091/56048619-e3429a00-5d15-11e9-8c0c-9340de79ebd7.PNG)

Any guidance or help is greatly appreciated! Thanks for working on such a great tool.

**Comment by chimurai** [comment]
Thank you for the kind words.

Can you try this config?
```javascript
const wsProxy = httpProxyMiddleware('/rmq', {
    target: 'http://localhost:15674',
    changeOrigin: true,
    autoRewrite: true,
    ws: true,
    pathRewrite: {
        '/rmq': '/ws'
    },
    logLevel: 'debug'
});
app.use('/rmq', wsProxy);
```

Hope this'll make it work.

Kind of counterintuitive way to rewrite the mounting path...

Planning to correct this behaviour in a future version.

```javascript
//from
app.use('/rmq', proxy({target: 'http://localhost:15674', pathRewrite: {'/rmq': '/ws'}}));
// to
app.use('/rmq', proxy({target: 'http://localhost:15674/ws'}));
```

**Comment by RVilgalysCrispin** [comment]
That worked! Thanks again for the help!
