### ISSUE TITLE
ERROR: fs dependency was not found in ./node_modules/snapdragon/lib/source-maps.js

### ISSUE THREAD

**Issue by zemse** [chimurai/http-proxy-middleware#336]
### Is this a bug report?

Yes

### Steps to reproduce

1. I am working on an Ethereum project. I am under college proxy and we always need to set the proxy address (10.32.0.1) everywhere. In react, I could simply add a proxy property in package.json but now I need to send requests from the backend, so I require to set a proxy using your package.
2. Installed the package from npm. 
3. Put a require statement in the js file I'm working on. 
4. Got error.

### Expected behavior

1. I thought I will install this package from npm.
2. Set require statement to variable name proxy.
3. Use proxy() method as in the documentation and get my work done.

### Actual behavior

As I am using next.js, I entered in terminal npm run dev. And it gave me this error.

```
 ERROR  Failed to compile with 1 errors                                                                                                             2:35:18 AM

This dependency was not found:

* fs in ./node_modules/snapdragon/lib/source-maps.js

To install it, you can run: npm install --save fs
> 

```
### Setup

- http-proxy-middleware: 0.19.1
- http-proxy-middleware configuration
- server: next @ 4.1.4
- other relevant modules: fs-extra web3 truffle-hd-wallet-provider

#### client info

MacOS

#### target server info

This is a next server. I'm trying to first send a request from the server using infura api and then send the output HTML to the client.

### Reproducible Demo

I've uploaded my project on github
[https://github.com/zemse/kickchainer/blob/master/ethereum/web3.js](https://github.com/zemse/kickchainer/blob/master/ethereum/web3.js)

**Comment by chimurai** [comment]
Sound more like you didn't install the dependencies correctly.

Closing this issue.

Feel free to re-open, if you still think it's a bug in http-proxy-middleware.
Please provide a minimal setup in which this can be reproduced, so it can be investigated.

StackOverflow would be a better place to troubleshoot your project.
