### ISSUE TITLE
update micromatch

### ISSUE THREAD

**Issue by AlvinYuXT** [chimurai/http-proxy-middleware#339]
### Is this a feature request?

(write your answer here)
yes. 
I find that micromatch this project used is "^3.1.10", and now the latest version is 4.0.2.
And in version 4 `micromatch("/a/b/c/d", ["!/a/b/c/**", '/**']) // true` which in version 3 is fasle
So is there a need to update micromatch to version 4?

**Comment by chimurai** [comment]
just published a beta version `0.20.0-beta.0`

can you give it a try?
`npm install http-proxy-middleware@0.20.0-beta.0`

**Comment by chimurai** [comment]
fixed in: `npm install http-proxy-middleware@0.20.0`
