### ISSUE TITLE
[Feature Request] Include TypeScript declaration in npm package

### ISSUE THREAD

**Issue by joshuaavalon** [chimurai/http-proxy-middleware#345]
Since this package is already written in TypeScript, why not include TypeScript declaration in the npm package?

You just need to add the following lines to `tsconfig.json`

```json
{
  "compilerOptions": {
    "declaration": true
  }
}
```

and `packacge.json`

```json
{
  "types": "./dist/index.d.ts"
}
```

You can keep the declaration up to date instead of requiring to update `@types/http-proxy-middleware` separately.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
Good point. I do not want to manage `@types/http-proxy-middleware` separately.
Please include TypeScript declaration.
