### ISSUE TITLE
Does http-proxy-middleware work in production?

### ISSUE THREAD

**Issue by willemevenwel** [chimurai/http-proxy-middleware#356]
### Is this a question?

Does http-proxy-middleware work in production?

### Is this a bug report?

No

### Setup

React project. Included via npm install http-proxy-middleware, configured in setupProxy.js

#### client info

Windows development PC.

#### target server info

The target is a hosted development api. Which can be hit via postman and normal ajax call in a static html file.

### Reproducible Demo

Cant share the project.

### The problem:

When I run my project via: npm start dev, the proxy configurations work well and fine without any issues.

When I make a built with: npm build

And then serve that build with: serve -s -l 3000 build/ then it doesnt work any longer. It basically routes to localhost:3000 instead of what is configured in the setupProxy.js

**Comment by willemevenwel** [comment]
I have come to the conclusion that http-proxy-middleware should only be used for development purposes, and cors policies must be adhered to correctly.

**Comment by mahendrathotakura** [comment]
Hey you said, it will only work for development purposes, then how to handle in the deployment build ?

**Comment by Juggernaut9** [comment]
@mahendrathotakura you have to configure your server. I also recent went through this issue. I hosted my react app on vercel and added a vercel.json file in the root of the folder, if you use vercel then check their document on how to configure vercel.json, not sure how you would do this on some other server, but it's not a react problem, its a problem of server not being configured
