### ISSUE TITLE
Breaking Changes and Versioning?

### ISSUE THREAD

**Issue by reintroducing** [chimurai/http-proxy-middleware#358]
### Is this a question?

I'm upgrading this module in my project and I took a look at the changelog to see what changed. There are multiple entries for BREAKING yet the version did not get a major bump rather a minor. Does this project follow semantic versioning? If so, why are these changes not bumping the major version? Thanks.

### Is this a bug report?

(write your answer here)

### Is this a feature request?

(write your answer here)

### Steps to reproduce

(Write your steps here:)

1. 2. 3.

### Expected behavior

(Write what you thought would happen.)

### Actual behavior

(Write what happened.)

### Setup

- http-proxy-middleware: _version_
- http-proxy-middleware configuration
- server: _connect/express/browser-sync..._ + _version_
- other relevant modules

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chimurai** [comment]
Hi @reintroducing ,

http-proxy-middleware does follow [semver](https://semver.org).

Think there's a common misunderstanding regarding `0.y.z` versions:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

source: https://semver.org/#spec-item-4

To avoid confusion maybe I should go for version `1.y.z`?

**Comment by reintroducing** [comment]
@chimurai You are right, I missed that part in the spec so thank you for clarifying. I was always under the impression that any breaking change, even in a 0.x.x release, should be breaking. They should probably update the summary at the top to just give a blurb about this in my opinion for the MAJOR portion.

Your module is used by almost 2.3 million other modules, and it would probably be a shame that others would make the same mistake I just did, but that's on me (them) for not fully reading the spec I suppose. Its entirely up to you at this point if you want to version it as major just to possibly help mitigate that confusion, but you've answered my question so I'm going to close this. Thanks again for the quick response.
