### ISSUE TITLE
Unable to catch 'econnreset'

### ISSUE THREAD

**Issue by klimashkin** [chimurai/http-proxy-middleware#363]
Hi!

Currently all modern browsers support [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) which can cancel running http request.
And [http-proxy](https://github.com/http-party/node-http-proxy) **can** [catch](https://github.com/http-party/node-http-proxy/blob/4a657a71267ae093e43473a155a3bb9dfc9784f8/lib/http-proxy/passes/web-incoming.js#L155) that and actually provides `econnreset` event for that case.

But seems like http-proxy-middleware doesn't expose that to the consumer, [list of events ](https://github.com/chimurai/http-proxy-middleware#http-proxy-events) doesn't contain _onEconnreset_.

Is there a workaround for that case or it might be considered as a bug?

**Comment by chimurai** [comment]
Hi @klimashkin 

http-proxy-middleware comes with a default error handler:
https://github.com/chimurai/http-proxy-middleware/blob/v0.20.0/src/handlers.ts#L52

This default error handler can be overridden with the `onError` option:
https://github.com/chimurai/http-proxy-middleware#http-proxy-events

**Comment by klimashkin** [comment]
Hi @chimurai! Please take a look at the link i posted one more time:
https://github.com/http-party/node-http-proxy/blob/4a657a71267ae093e43473a155a3bb9dfc9784f8/lib/http-proxy/passes/web-incoming.js#L155

Since ~2016 `ECONNRESET` has its own `econnreset` event, not `error` event

**Comment by klimashkin** [comment]
Since Dec 2016 to be precise:
https://github.com/http-party/node-http-proxy/commit/927357bedc42f2e3067c44c10ab9563be7d8b032

**Comment by chimurai** [comment]
ah, my bad.

Think you can use the `onProxyReq` option, which just exposes the `http-proxy`.`on('proxyReq')` event.

```javascript
function onProxyReq(proxyReq, req, res) {
  // add custom header to request
  proxyReq.setHeader('x-added', 'foobar');
  // or log the req
}
```
📓 https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onproxyreq

You should be able to add listeners to `proxyReq` and `req`, like you pointed out earlier.
https://github.com/http-party/node-http-proxy/commit/927357bedc42f2e3067c44c10ab9563be7d8b032#diff-6b475017a1a35b15c446d2edf40979f6R143

**Comment by klimashkin** [comment]
@chimurai Yes, you right, it's possible to override the whole `proxyError` handler!
