### ISSUE TITLE
Multiple set-cookie in array

### ISSUE THREAD

**Issue by mlabarre** [chimurai/http-proxy-middleware#364]
Hello
Is-it normal that proxy returns multiple Set-Cookie headers in only one header 'Set-Cookie' with an array as value ?
Many thanks

**Comment by aspirisen** [comment]
Have the same issue, any updates?

**Comment by chimurai** [comment]
This question can be best answered in the [http-proxy](https://github.com/http-party/node-http-proxy/issues) project.

http-proxy-middleware doesn't do anything with headers actively.
