### ISSUE TITLE
Multiple Targets?

### ISSUE THREAD

**Issue by Fenny** [chimurai/http-proxy-middleware#367]
Hi Lads,

I managed to proxy one host, how do I proxy multiple hosts?

```javascript
var http      = require('http')
var httpProxy = require('http-proxy')

var proxy = httpProxy.createProxyServer({
  target: {
    host: 'localhost',
    port: 5001
  }
})

proxy.listen(80)

proxy.on('error', (err, req, res) => {
  res.writeHead(500, {
    'Content-Type': 'text/plain'
  })
  res.end('Something went wrong. We pride ourselves on meeting expectations, so to make it up to you, we\'re going to fire Patrick.');
})
```

**Comment by chimurai** [comment]
You might want to try the `router` option:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md#router

**Comment by visgotti** [comment]
> You might want to try the `router` option:
> https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md#router

Why don't you just allow target to optionally take a function? It throws an error if you leave target out but have a valid router function, seems very redundant.

**Comment by chimurai** [comment]
`target` is an option from the `http-proxy` library.
It was a choice not to override options from the transitive dependency to avoid confusion.

Throwing the error was initially added to make the `target` option mandatory.
`router` was added later without taking into account the previous.

Think indeed it can be improve to check for the presence of either `target` of `router` option
