### ISSUE TITLE
Trailing slash unexpectedly added to target

### ISSUE THREAD

**Issue by jetibest** [chimurai/http-proxy-middleware#368]
I am using this middleware to proxy `https://example.com/app` to `http://localhost:8080` running the app, which seems like a common use-case.

However, from within the app, it is impossible to distinguish between `https://example.com/app` and `https://example.com/app/`, because the proxy always adds a trailing slash to the target. So even though one writes the target as `http://localhost:8080` it is always parsed as `http://localhost:8080/`, due to the `http-proxy` package using `require('url').parse`, which parses `http://localhost:8080` incorrectly with the path being `/`, even though there is no such path in the original URL.

This issue causes relative paths to be broken, and the path redirection from `/app` to `/app/` must be written in the router, instead of the app being routed to. Which is not good, because the router should not need to know whether or not `/app` is valid or not (maybe it is a single resource app that does not require redirection to a directory-path).

As a workaround, I am adding the original path to the header with this option:
```
onProxyReq: function(proxyReq, req, res, options)
{
    proxyReq.setHeader('X-Forwarded-Original-Path', req.originalUrl);
}
```

I am not sure how a possible fix would be more elegant than the workaround, but I am not feeling very inspirational after looking through the http-proxy-middleware code. Perhaps this issue actually belongs to the node-http-proxy repository, I'm unsure.

**Comment by chimurai** [comment]
If this is an issue, it indeed should be investigated in the node-http-proxy repo.

**Comment by itaied246** [comment]
I'm facing that bug as well, any updates or fixes?

**Comment by chimurai** [comment]
Can you provide a minimal repo where this issue can be reproduced?

**Comment by secondfry** [comment]
@chimurai here you go
https://github.com/secondfry/http-proxy-middleware-issue-368-repro

**Comment by eduardoamills2** [comment]
Hi

I had the same problem, i am not sure but that worked for me is:
`		if( proxyReq.path.endsWith('/')) {
			proxyReq.path = proxyReq.path.slice(0, -1);
		}`

**Comment by nithishv** [comment]
> Hi
> 
> I had the same problem, i am not sure but that worked for me is: ` if( proxyReq.path.endsWith('/')) { proxyReq.path = proxyReq.path.slice(0, -1); }`

Thanks! That was helpful
