### ISSUE TITLE
Proxy websocket when using gulp, browsersync, ng-websocket

### ISSUE THREAD

**Issue by redi-madhava** [chimurai/http-proxy-middleware#37]
Hi,

**Can you please review the http-proxy-middleware config below?**

I'm not able to proxy local websocket (separate) process with http-proxy-middleware as I see "[HPM] Upgrading to WebSocket" message on the window where I ran "gulp serve", and the error "WebSocket connection to 'ws://localhost:3000/ws/myobjects' failed: Connection closed before receiving a handshake response" on the browser console window. 

I'm using v0.9.0 of http-proxy-middleware, v0.2.1 of ng-websocket, v2.8.3 of browser-sync.

When browser makes a websocket call to **"ws://localhost:3000/ws/myobjects"** I expect the call to be served by a server listening for web socket connection on **"ws://localhost:10009/ws/myobjects"**
There are other static assets served under http://localhost:3000 that are not related to websockets.

```javascript
function browserSyncInit(baseDir, browser) {
  browser = browser === undefined ? 'default' : browser;

  var routes = null;
  if(baseDir === conf.paths.src || (util.isArray(baseDir) && baseDir.indexOf(conf.paths.src) !== -1)) {
    routes = {
      '/bower_components': 'bower_components'
    };
  }

  var server = {
    baseDir: baseDir,
    routes: routes
  };

  /*
   * You can add a proxy to your backend by uncommenting the line bellow.
   * You just have to configure a context which will we redirected and the target url.
   * Example: $http.get('/users') requests will be automatically proxified.
   *
   * For more details and option, https://github.com/chimurai/http-proxy-middleware/blob/v0.0.5/README.md
   */
   server.middleware = proxyMiddleware('/ws/myobjects', {
     target: 'http://localhost:10009',
     ws: true,
     changeOrigin : true,
     proxyTable: {
       'localhost:3000/ws/myobjects' : 'http://localhost:10009'
     }
   });

  browserSync.instance = browserSync.init({
    startPath: '/',
    server: server,
    browser: browser
  });
}
```

**Comment by chimurai** [comment]
This is a known WebSocket issue (https://github.com/chimurai/http-proxy-middleware/issues/15) when `http-proxy-middleware` is used in `browser-sync`.
With `express` and `connect` this issue does not seem to occur.

Issue is also reported @ https://github.com/BrowserSync/browser-sync/issues/780.

Unfortunately there is no fix available yet for this problem.

**Comment by chimurai** [comment]
Closing this issue to keep the conversations centralized.
