### ISSUE TITLE
Set header does not work

### ISSUE THREAD

**Issue by youncccat** [chimurai/http-proxy-middleware#372]
Hi! I'm using nuxt recent, but I have a problem with @nuxtjs/proxy, the @nuxtjs/proxy is wrapped to `http-proxy-middleware`. So can you help me?

I want to set `x-foo-bar` to request header, but I can see that `x-foo-bar` is not in headers in Network in Chrome.

This is my part of nuxt config

```
proxy: {
    '/proxy': {
      target: 'http://localhost:3000',
      pathRewrite: { '^/proxy/': '' },
      onProxyReq(proxyReq, req) {
        proxyReq.setHeader('x-foo-bar', '123')
      },
    },
  }
```

**Comment by web3devin** [comment]
@youncccat I am only replying to this necropost as it is still open and I ran into the same issue. The Network tab doesn't update with the new header values, however, they do still get passed along. So Chrome Dev Tools won't show your header. But the Server will see that header.

**Comment by youncccat** [comment]
@web3devin  thanks for the reply that resolve my problem. You're right, the header is sent from the node server,  so I can't see it in the Network tab.

**Comment by aaadipop** [comment]
sorry for reopening,

but how can be set the 'Content-Type'?

without '-' works good, but with '-'?

I tried with
- headers: {'Content-Type': 'value'}
- headers: {"Content-Type": "value"}
- JSON.parse('{"Content-Type":"app/json"}')

thanks
