### ISSUE TITLE
License violation issue as indirect dependency node-forge is now under GPL

### ISSUE THREAD

**Issue by akankshagaur** [chimurai/http-proxy-middleware#373]
Hi,

I am using angular & http-proxy-middleware in my project & whitesource gave us a license violation alert for an indirect dependency node-forge which is under GPL now. Is there an alternate for the same?

Thanks
Akanksha Gaur

**Comment by akx** [comment]
Probably a false alert: https://github.com/jfromaniello/selfsigned/issues/34#issuecomment-553094099

**Comment by chimurai** [comment]
`node-forge` is not used in this project
