### ISSUE TITLE
Angular CLI proxy is very slow

### ISSUE THREAD

**Issue by TheNemus** [chimurai/http-proxy-middleware#375]
### Is this a question?
Hi,

I'm using the HPM from the angular cli bundle. I notice that every single request I make pass from the proxy has a latency time increased of 3/4 tenth of second. No logic inside the proxy, just this:

- http-proxy-middleware: 
Angular CLI: 8.3.0
Node: 12.8.1
OS: win32 x64
(I'm sorry but I cannot extract HPM version)
- http-proxy-middleware configuration
```
'/api/postman' : {
    target: 'https://postman-echo.com/get?foo1=bar1&foo2=bar2',
    pathRewrite: {
      '/api/postman': ''
    },
  },
```

**Comment by chimurai** [comment]
Does this happen if you try your proxy configuration in a minimal setup?

You can modify the example:
https://github.com/chimurai/http-proxy-middleware/blob/master/examples/express/index.js

After git clone:

1. `yarn`
2. `yarn build`
3. `node examples/express/index.js`    << start example

**Comment by chimurai** [comment]
feel free to re-open when issue can be reproduced in minimal setup

**Comment by chimurai** [comment]
Might be related to this: https://github.com/webpack/webpack-dev-server/issues/1850
