### ISSUE TITLE
response of api called is to large

### ISSUE THREAD

**Issue by vacrozet** [chimurai/http-proxy-middleware#378]
The answer from my API that is calling with the proxy is really very big and the proxy does not support it. Have you ever encountered this problem, and do you have a solution, option for big data?

```
api.use(\'/funnel\', middle(), proxy({
  logLevel: "debug",
  target: config.bigDataFunnelUrl,
  pathRewrite: {
    '^/funnel/upload-csv': 'funnel/smatch/csv/collect_api',
    '^/funnel/update-funnel-analysis': 'funnel/command/update_funnel_analysis',
    '^/funnel/update-funnel': 'funnel/command/update_funnel_csv',
  },
}));

**Comment by chimurai** [comment]
What is the size of the response you are dealing with?

Would be nice if you can provide a minimal setup to reproduce the issue for investigation.

**Comment by vacrozet** [comment]
when i try with response body of approximatly 44ko it's OK but 77ko it's KO.

**Comment by chimurai** [comment]
Maybe it's me. The unit `ko` is unkown to me.
Is that kilobytes, megabytes?

**Comment by vacrozet** [comment]
yes kilobytes

**Comment by chimurai** [comment]
That's not super large. I've have been proxying responses which are larger than 77 kilobytes...

Can you provide a minimal example in which this issue is reproduced?

**Comment by chimurai** [comment]
Closing issue.

Feel free to reopen when issue can be reproduced in a minimal example
