### ISSUE TITLE
Webworker proxy with If-Modified-Since header

### ISSUE THREAD

**Issue by bigkrp** [chimurai/http-proxy-middleware#381]
### Is this a bug report?
Yes

### Steps to reproduce

I have poller in shared worker with header `If-Modified-Since`

1. run `webpack-dev-server` with proxy
2. Poller starts
3. backend returns `304` status

### Expected behavior
`http-proxy-middleware` send 304 status, not 502

### Actual behavior

i have errors in console
```
[HPM] Error occurred while trying to proxy request /api/[API_METHOD] from localhost:3000 to http://[SERVER_IP]/ (HPE_INVALID_CONSTANT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```
and errors in `Network` in chrome devtools:
General:
```
Request URL: http://localhost:3000/api/[API_METHOD]
Request Method: GET
Status Code: 502 Not Modified
Remote Address: [::1]:3000
Referrer Policy: no-referrer-when-downgrade
```

Request Headers:
```
Accept: application/json, text/plain, */*
If-Modified-Since: Fri, 20 Dec 2019 12:41:54 GMT
Referer: http://localhost:3000/assets/worker.60f6a122912284b508fb.js
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36
X-Requested-With: XMLHttpRequest
```

Response:
```
Error occured while trying to proxy to: localhost:3000/api/[API_METHOD]
```

But on server nginx log have:

```
"GET /api/[API_METHOD] HTTP/1.1" 304 20 "http://94.125.123.16/assets/worker.18dcf756e7fd7ec3befb.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36"
```

304 - status, but proxy send me 502 status with `Not Modified` message

### Setup
webpack-dev-server configuration:
```
proxy: {
    '/api/**': {
      target: "http://[SERVER_IP]/",
      changeOrigin: true
    }
}
```

- http-proxy-middleware: 0.19.1(as webpack-dev-server@^3.1.3 dependencies)
- server: "webpack-dev-server": "3.1.3"

#### client info

Fedora 31 (5.3.16-300.fc31.x86_64)
node version: v12.13.1

**Comment by jontuk** [comment]
I'm also hitting this after upgraded node to v14 and npm to v7.

Perfectly good (according to Chrome/Firefox) HTTP 1.1 304s turn into 502s.

```[HPM] Error occurred while trying to proxy request /version from localhost:2992 to http://localhost:5000 (HPE_INVALID_CONSTANT) (https://nodejs.org/api/errors.html#errors_common_system_errors)```

Any update, others experiencing or something I could be doing wrong? Thanks

**Comment by bigkrp** [comment]
Same situation without worker. With other statuses 300, 301,302, 303 - it proxy well.
But when i back from server 304, it fires error

**Comment by takeTrace** [comment]
wait for a solution, I found it cause a Zlib Error: unexpected end of file, I think it's nothing to decompress, so it crash.
And I tried to return statusCode just 304 from local simple express server, it normally work. So, doesn't know what response with 304 cause this issue, anybody have precise demo for reproduce this issue? 

> Same situation without worker. With other statuses 300, 301,302, 303 - it proxy well. But when i back from server 304, it fires error
> 
> Still no solution?
