### ISSUE TITLE
Can I use http-proxy-middleware inside http-server

### ISSUE THREAD

**Issue by senzacionale** [chimurai/http-proxy-middleware#385]
I would like to use proxy with https://www.npmjs.com/package/http-server.

So if path does not match simply open http-server url and do not proxy it.

Example:

http://abc.com/ -> no proxy needed
http://abc.com/foo -> no proxy needed
http://abc.com/xyz-> proxy to xyz.abc.com

is this possible to do with this middleware?

**Comment by chimurai** [comment]
`http-server` uses the same `http-proxy` library, so in theory you can make it work.

It's all open source software.

You could open a PR to add this feature if you feel the need for it.

https://github.com/http-party/http-server/issues/597
