### ISSUE TITLE
Cannot remove headers from proxyReq in onProxyReq handler.

### ISSUE THREAD

**Issue by AlexLeung** [chimurai/http-proxy-middleware#389]
### Is this a bug report?

I would like to remove a header before proxying the request forward. When using the `onProxyReq` handler, this causes an error.

### Steps to reproduce

```
var express = require('express');
var proxy = require('http-proxy-middleware');

const port = 8080;
const npmRegistryHost = "registry.npmjs.org";

express()
    .use('*', proxy({
        target: `https://${npmRegistryHost}`,
        changeOrigin: true,
        onProxyReq: (proxyReq, req, res) => {
            proxyReq.removeHeader('if-modified-since');
        }
    }))
    .listen(port);
```

### Expected behavior

Header is removed from request send to `registry.npmjs.org`

### Actual behavior

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot remove headers after they are sent to the client
```

### Setup

- http-proxy-middleware: `^0.20.0`

#### client info

Ubuntu 18.04.3

### Reproducible Demo

see attached code

**Comment by jjwallace** [comment]
I see the options docs show:
`onProxyRes(proxyRes, req, res) {
  proxyRes.headers['x-added'] = 'foobar'; // add new header to response
  delete proxyRes.headers['x-removed']; // remove header from response
}`

**Comment by denchen** [comment]
Hey @AlexLeung, how did you resolve the issue? I'm trying to remove some request headers in `onProxyReq()`, but when I check the backend where I'm proxying to, the headers I removed via `proxyReq.removeHeader()` are still there.

Also, @jjwallace , your solution is for a different issue. We're trying to prevent headers being sent to whatever server we're proxying to, not removing headers from the response.

**Comment by Fi1osof** [comment]
Why closed? Any solution?

**Comment by cawoodm** [comment]
Hello, I too am unable to remove headers on `proxyReq`. Indeed there is no `proxyReq.headers` object at all.

**Comment by indatawetrust** [comment]
i added a middleware to set the header values ​​to go and made adjustments to it. it would be nicer if title change feature is added to onProxyReq
```js
router.use((req, res, next) => {
  req.headers = _.pick(req.headers, [
    'cookie',
    'referer',
    'origin',
    'connection',
    'user-agent',
    'content-type',
    'accept',
  ]);

  next();
}, httpProxy);
```
