### ISSUE TITLE
Problem (index):330 WebSocket connection to 'wss://mylocal.com//ws' failed: Error during WebSocket handshake: Unexpected response code: 200

### ISSUE THREAD

**Issue by nocturnesound** [chimurai/http-proxy-middleware#391]
I have an error when use websocket:
WebSocket connection to 'wss://mylocal.com//ws' failed: Error during WebSocket handshake: Unexpected response code: 200

Without http-proxy-middleware everything ok.
`var proxy = require('http-proxy-middleware');
var express = require('express')

var port = 8086

var request = require('request')

const forumProxy = proxy({
    target: 'http://apihand1',
    changeOrigin: true,
    ws: true,
    secure: true,
    xfwd: true,
    logLevel: 'debug'
});

var app = express()

app.use('/', forumProxy);

var server = app.listen(port, () => console.log(`Example app listening on port ${port}!`))
server.on('upgrade', forumProxy.upgrade);
` 

With http-proxy-middleware:
`Request URL: wss://mylocal.com//ws
Provisional headers are shown
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,fr;q=0.6,it;q=0.5
Cache-Control: no-cache
Connection: Upgrade
Cookie: __cfduid=d5d45a4zzz9732d3266cbb5944bcf1580417025; _fbp=fb.1.1580417034705.1510445810
Host: mylocal.com
Origin: https://mylocal.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: MNasXANqZ32qcGhFY2WdWw==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

Without http-proxy-middleware:
`Request URL: wss://mylocal.com//ws
Request Method: GET
Status Code: 101 Switching Protocols
Connection: upgrade
Date: Mon, 03 Feb 2020 23:42:25 GMT
Sec-Websocket-Accept: t4F7du6wW52qkakO7cEl4wvPKYQ=
Server: nginx/1.13.8
Upgrade: websocket
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,fr;q=0.6,it;q=0.5
Cache-Control: no-cache
Connection: Upgrade
Cookie: __cfduid=d55d1a483e023c00edsff5c6dd14f7be81564242344; _fbp=fb.1.1564242348024.1104762243; _fbc=fb.1.1579687754068.IwAR0BBZ4mF2tKIEeaakatk6MpukgBYlWO3y58UBN_vhW-q2BsrKbOhUc08; _ym_d=1590207539; _ym_uid=1564222228144971202
Host: mylocal.com
Origin: https://mylocal.com
Pragma: no-cache
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Sec-WebSocket-Key: ZXEAAPh/znhy+YXAXDFVFOw==
Sec-WebSocket-Version: 13
Upgrade: websocket
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36`

nginx conf:
`location / {
    proxy_pass http://mylocal.com;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}`

How I can fix it?

**Comment by bkniffler** [comment]
How did you solve this?

**Comment by nocturnesound** [comment]
It's was my fault. My nginx settings was without:
proxy_set_header Upgrade $http_upgrade; 
proxy_set_header Connection "upgrade";.
