### ISSUE TITLE
proxy('**/*.do', {...})  throw exception SyntaxError: Invalid regular expression: /**/*.do/: Nothing to repeat

### ISSUE THREAD

**Issue by 029ye** [chimurai/http-proxy-middleware#392]
set  proxy('**/*.do', {...}) ,
 throw exception  :SyntaxError: Invalid regular expression: /**/*.do/: Nothing to repeat

**Comment by chimurai** [comment]
Please provide a minimal example

**Comment by chenxxzhe** [comment]
me too.
![image](https://user-images.githubusercontent.com/9720961/75785685-19aa5d00-5d9f-11ea-9121-0f01e46a5027.png)

**Comment by chenxxzhe** [comment]
"http-proxy-middleware": "^1.0.1",
"@vue/cli-service": "^3.8.0",

**Comment by chenxxzhe** [comment]
```js
devServer: {
    proxy: {
      '**/*.zip': {
        target,
        changeOrigin: true,
        ws: false
      }
    }
  },
```

**Comment by chimurai** [comment]
Unable to reproduce. Closing issue.

Feel free to reopen when minimal working example can be provided
