### ISSUE TITLE
Error occurred while trying to proxy request /api/events from localhost:4200 to http://localhost:4200 

### ISSUE THREAD

**Issue by stutishah1105** [chimurai/http-proxy-middleware#396]
I am using ngf-server with angular 8.

here is my proxy.config.json

{

    "/api":{
        "target":"https://localhost:4200",
        "secure":false,
        "logLevel": "debug",
        "changeOrigin": true
    }
}

**Comment by chimurai** [comment]
Bit strange to proxy to your own server.
Please use stackoverflow for help with your project setup.
