### ISSUE TITLE
Can you define multiple routes?

### ISSUE THREAD

**Issue by wgorder** [chimurai/http-proxy-middleware#4]
Wondering if it possible to define multiple routes to be proxied to the same backend server?

**Comment by chimurai** [comment]
multiple routes are not yet supported.

do you have any thoughts how the function call should look like?

I was thinking something like this:
proxyMiddleware(['/api', '/another_api'], options);

**Comment by wgorder** [comment]
@chimurai that looks good to me, and is what I tried first, just to see if it would work :)

**Comment by wgorder** [comment]
I currently don't have the need to proxy to multiple hosts, however if you were interested in supporting this as well, you may want to consider a way to define a route table.

Examples here:
https://blog.nodejitsu.com/node-http-proxy-1dot0/
and here:
https://www.npmjs.com/package/httpp-proxy#proxy-requests-using-a-proxytable

**Comment by chimurai** [comment]
Interesting idea.
Could you give any practical use-cases for this route table option?

I can only think of a vhost-ish setup.

**Comment by chimurai** [comment]
@wgorder 
I just pushed a new version to npm with multiple route/path support.
Could you verify the functionality and close this issue?

**Comment by giohperez** [comment]
In the documentation is says we can use multiple contexts.. But passing the array of the two different ones don't work.

In my case, I work with more than one server/API.. Our service calls and servers depend on what module of the application it's on.. In some cases I need to call services across 3 or 4 different contexts..

**Comment by giohperez** [comment]
QUOTING FROM NPMJS PAGE....

var proxyMiddleware = require('http-proxy-middleware');
 
var proxy = proxyMiddleware('/api', {target: 'http://www.example.org'});
//                          \____/  \________________________________/ 
//                            |                     | 
//                          context              options 
 
//  'proxy' is now ready to be used in a server. 
 
context: matches provided context against request-urls' path. Matching requests will be proxied to the target host. Example: '/api' or ['/api', '/ajax']

**Comment by chimurai** [comment]
@giohperez could you provide the depencies/devdependencies in your package.json?
and also how you configured the proxy middleware

**Comment by chimurai** [comment]
Closing this issue.
Please leave a reply when you're experiencing issue with multiple contexts.
