### ISSUE TITLE
POST request body is not proxied to the servers

### ISSUE THREAD

**Issue by dejewi** [chimurai/http-proxy-middleware#40]
I have in my backend defined:
```
var proxy = proxyMiddleware('/api', {
        target: 'http://somehost.zero',
        proxyTable: {
            '/api/one': 'http://somehost.one',
            '/api/two': 'http://somehost.two',
        }
    });
app.use(proxy);
```

and when I'm proxing POST request (lets say to the '/api/one': 'http://somehost.one' ) I don't know why but server http://somehost.one get request without body.

Did you had similar problem?

**Comment by chimurai** [comment]
I haven't tested the proxyTable option with POST requests yet.

Which version of http-proxy-middleware are you using?
And which server/version do you use? (connect, express or something else?)

**Comment by dejewi** [comment]
Hi,
I use:
    "express": "~4.0.0",
    "http-proxy-middleware": "^0.9.0",

**Comment by dejewi** [comment]
Here is example 
https://github.com/dejewi/proxy-bug

**Comment by chimurai** [comment]
Thanks.

How does your post request (url) look like?

**Comment by carlskii** [comment]
Hi, I'm seeing this issue too using browsersync. 

```javascript
var proxy = proxyMiddleware('/vedsdk', {
  target: 'https://xxx.xxx.xxx.xxx',
  changeOrigin: true,    // for vhosted sites, changes host header to match to target's host
  secure: false
});
```

My API does not appear to get the body:

```
POST https://xxx.xxx.xxx.xxx/vedsdk/authorize/ 415 (Unsupported Media Type)
```

**Comment by dejewi** [comment]
@chimurai it looks like:
POST http://my.app.host:2000/api/operation/zero/minus/something/else 
or 
POST http://my.app.host:2000/api/one/something

and in both cases data which I'm sending is:
{something: 'one', else: 'two'}

**Comment by carlskii** [comment]
Sorry - do you mean this works for you or am I doing something wrong with my post request ?

**Comment by chimurai** [comment]
Did a little test and I am able to receive POST data at the `target` server.

I noticed you are using the `body-parser` middleware:
https://github.com/dejewi/proxy-bug/blob/master/app.js#L16

**Option 1:**
You might want to change to order of the middlwares you are using.
Try moving the `http-proxy-middleware` above the `body-parser`

> source: http://stackoverflow.com/a/25651651/3841188

**Option 2:**
Use `fixRequestBody`:

```ts
import { createProxyMiddleware, fixRequestBody } from 'http-proxy-middleware';

createProxyMiddleware({ 
  target: 'http://example.com', 
  on: { 
    proxyReq: fixRequestBody, 
  } 
}); 
```

Hope this solves the issue.

**Comment by dejewi** [comment]
Yes, this solved my problem. Thank you very much for your help.

**Comment by yousefamar** [comment]
Apologies for resurrecting this, but anybody aware of another way to avoid this issue when you can't change the order of middleware (e.g. if you're adding proxies at run-time)?

**Comment by IrynaBu** [comment]
The same question :)

**Comment by jgf5013** [comment]
I'm having this same (or a very similar) problem when using browser-sync with http-proxy-middleware. The middleware is moving my POST request to a GET request using x-www-form-urlencoded, which is being rejected by the server.

**Comment by chimurai** [comment]
If you can't change the order of the middleware; You can restream the parsed body before proxying the request. This should fix the POST request:

``` javascript
// restream parsed body before proxying
var restream = function(proxyReq, req, res, options) {
    if (req.body) {
        let bodyData = JSON.stringify(req.body);
        // incase if content-type is application/x-www-form-urlencoded -> we need to change to application/json
        proxyReq.setHeader('Content-Type','application/json');
        proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
        // stream the content
        proxyReq.write(bodyData);
    }
}

var apiProxy = proxyMiddleware('/api', {
    target: 'https://xxx.xxx.xxx.xxx',
    onProxyReq: restream
});


var app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(apiProxy);                // with restreaming
```

source: [node-http-proxy/examples/middleware/bodyDecoder-middleware.js](https://github.com/nodejitsu/node-http-proxy/blob/d0e000e1f91a969f1711eb3be7d1acb16c4538df/examples/middleware/bodyDecoder-middleware.js). (https://github.com/nodejitsu/node-http-proxy/pull/1027)

---

Update: Use `fixRequestBody` to achieve the same:

```ts
import { createProxyMiddleware, fixRequestBody } from 'http-proxy-middleware';

createProxyMiddleware({ 
  target: 'http://example.com', 
  on: { 
    proxyReq: fixRequestBody, 
  } 
}); 
```

**Comment by joshparolin** [comment]
Spent a few hours trying to debug this same issue while setting up multiple proxies. The request would hang at the `target`. Moving `proxyMiddleware` above `bodyParser` solved my problem as well. Thank you!

**Comment by piyushbeli** [comment]
For my purpose, I was able to make this work by changing the order i.e. putting body-parser after proxy-middleware..
Thanks.

**Comment by jeffvandyke** [comment]
GRRR! Hi :) I arrived here from trying to figure out why webpack-dev-server was proxying a POST request and dropping the json body content somewhere on its way to the server. @chimurai 's fix ended up working, but I wasn't even using bodyParser to start with. Is there any webpack-dev-server gurus that know any simpler solution than:

    1. npm install --save body-parser
    2. adding in webpack.config.js: devServer.setup = function (app) { app.use(require('body-parser').json()); }
    3. adding devServer.proxy["/url/to/proxy"].onProxyReq = /*the function @chimurai so generously provided
    4. making sure that the request (which uses fetch) adds the Content-Type: application/json header to the options

which all works, again, finally, but is there any easier way? I'm worried about others who might have to spend a lot of time tracking down that issue.

**Comment by jeffvandyke** [comment]
It seems to work now with Webpack 3.6.0 - I tried removing my fix after I had an issue trying to post JSON.stringify(true), and the proxy no longer chokes on the json body, no matter the shape!

**Comment by jamesjtong** [comment]
I ran into a similar issue where the proxied post parameters weren't being included. The issue was that the request headers didn't specify application/json.
```const headers = {
  Accept: "application/json",
  "Content-Type": "application/json",
};
```
It is strange that isn't any error being specified or logged and that the post body is just ignored.

**Comment by chping2125** [comment]
@chimurai why ? This solved my problem ,but why `body-parser` middleware is causing the problem.

**Comment by aryeharmon** [comment]
@chimurai becuase it changes the req.body property

**Comment by edmundo096** [comment]
@chping2125 Not sure about @aryeharmon answer, but as I understand, the request body data is a node stream (if you remember express tutorials, the `req` object inherits from a node's stream), which body parser *pipes* (an this thus empties) the data from the request stream.
See this here https://github.com/expressjs/body-parser/blob/master/lib/read.js#L162

That is why chimurai said on his post (https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-249430255) that his middleware patch *"restreams"* the body back into the request stream again (like if body parser never emptied it out).

Hope it's clearer now.

**Comment by zhe-he** [comment]
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/modify-post.md 
line 39 `// Remove body-parser body object from the request`

Why delete body-parser  in http-proxy-middleware?

**Comment by ViggoV** [comment]
Is there any way for http-proxy-middleware to do a check for stuff like this in the future? I just spend 2 days ripping out my hair because I had absolutely zero debug info to go on? Just a proxy that did nothing until it timed out..

**Comment by christiaanwesterbeek** [comment]
Here https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-420259997
> I just spend 2 days ripping out my hair

And here https://github.com/chimurai/http-proxy-middleware/issues/177#issuecomment-364054609
> I just spent three days trying to figure out why my proxy was hanging, until I stumbled upon this issue.

And here https://github.com/chimurai/http-proxy-middleware/issues/150#issuecomment-284083246 
> OMFG I have been trying to make this work for 2 days and that totally did it

And I just lost a few hours as well.

Just underscoring that if you see you're GET requests being proxied just fine, but your POST requests seem to hang and not being proxied, this issue is providing solutions.

**Comment by gryslik** [comment]
Hi,

I am still having this problem. Specifically, I am using datatables in R Shiny which doesn't load. I have added the following to app.js:


```
var restream = function(proxyReq, req, res, options) {
    if (req.body) {
        let bodyData = JSON.stringify(req.body);
        // incase if content-type is application/x-www-form-urlencoded -> we need to change to application/json
        proxyReq.setHeader('Content-Type','application/json');
        proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
        // stream the content
        proxyReq.write(bodyData);
    }
}


var myProxy = createProxyMiddleware('/myapp',{ target: 'http://localhost:3838/', changeOrigin: true, ws: true, onProxyReq: restream});

var app = express();


// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'jade');


app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended: true}));

app.use('/myapp', myproxy);
```

I get the following in the console but the datatable never loads

```POST /myapp/session/3d9bab09a45d7bcd067a1ec4f0587546/dataobj/efficient_return_table?w=&nonce=d33a18f6a4132b4d 200 26.748 ms - 147```

If I take out that restream stuff it times out.

**Comment by cawoodm** [comment]
If I remove `body-parser` middleware then `req.body` is always undefined and `restream` fails because it has nothing to parse.

**Comment by ToshKoevoets** [comment]
If you really cant rewrite the order, you can rebuild back the body, mind you this is in JSON format.

```

onProxyReq : (proxyReq, req, res) => {
        if ( (req.method == "POST" ||req.method == "PUT")  && req.body ) {
           let body = req.body;
           let newBody = '';
           delete req.body;

           try {
             newBody = JSON.stringify(body);
             proxyReq.setHeader( 'content-length', Buffer.byteLength(newBody, 'utf8'));
             proxyReq.write( newBody );
             proxyReq.end();
           } catch (e) {
             console.log('Stringify err', e)
           }
         }
     },
}
```

**Comment by Varshini-v** [comment]
Hi all,
I am not using body-parser,
Here is my use case, 
1. Tries to proxy the request to https://target/rest/v1
2. Gets 401 for first invocation. so, in onProxyRes() I have code like below:

if( res.statuscode == 401)
{
req.next() ;    // My next middleware gets the fresh OAuth token and tries to proxy the request again.
}

3. Gets fresh OAuth token and storing in in-memory
4. Now trying to proxy same request again with new token to https://target/rest/v1. At this point, Getting timeout issue with POST requests. however GET requests are working fine.

I am not able to utilize solutions provided above because req.body is undefined as I am not using body-parser

can anyone please help?

**Comment by tverilytt** [comment]
> > If you can't change the order of the middleware; You can restream the parsed body before proxying the request. This should fix the POST request:
> 
> 6+ years later and this is still a lifesaver. Thank you!!

Still is for sure  😎

**Comment by ilyaskarim** [comment]
Node.js sucks!

**Comment by hengkydev** [comment]
in version 3 you can just doing something like this,
is from official documentation, without moving the body parser middleware

```ts
const { createProxyMiddleware, fixRequestBody } = require('http-proxy-middleware');

const proxy = createProxyMiddleware({
  /**
   * Fix bodyParser
   **/
  on: {
    proxyReq: fixRequestBody,
  },
});
```

**Comment by Prakhar301101** [comment]
> in version 3 you can just doing something like this, is from official documentation, without moving the body parser middleware
> 
> ```ts
> const { createProxyMiddleware, fixRequestBody } = require('http-proxy-middleware');
> 
> const proxy = createProxyMiddleware({
>   /**
>    * Fix bodyParser
>    **/
>   on: {
>     proxyReq: fixRequestBody,
>   },
> });
> ```

was struggling with this error a lot, thanks @hengkydev

**Comment by iamnasirudeen** [comment]
> fixRequestBody

This just fixed it for me.. you're such a lifesaver

**Comment by Redisearch-ishaan** [comment]
> Thanks.
> 
> How does your post request (url) look like?





https://nodejser.space/questions/bypassing-http-request-without-the-need-to-transfer-data-in-the-body
