### ISSUE TITLE
require no longer working from 0.22.0-alpha onward.

### ISSUE THREAD

**Issue by aogilvie** [chimurai/http-proxy-middleware#403]
Requiring this module no longer working from `0.22.0-alpha` onward.

### Steps to reproduce

```
const prox = require('http-proxy-middleware');
typeof prox
// undefined
```
### Expected behavior

Should return function.

### Actual behavior

returns undefined.

### Setup

```
// package.json
"http-proxy-middleware": "0.22.0-alpha",
// or
"http-proxy-middleware": "1.0.0",
```

`npm 6.13.4`

---
For now using `0.21.0`

**Comment by chimurai** [comment]
Breaking change was introduced in 1.0.0.

See changelog and release notes for details.

https://github.com/chimurai/http-proxy-middleware/blob/master/CHANGELOG.md#v100

https://github.com/chimurai/http-proxy-middleware/releases

**Comment by coreyleelarson** [comment]
This is not even working for me:

**Source:**
```
const { createProxyMiddleware } = require("http-proxy-middleware");
...
app.use(createProxyMiddleware({ ... }))
```

**Produces:**
```
TypeError: createProxyMiddleware is not a function
```

**Comment by chimurai** [comment]
Just created a tiny project from scratch without issues:

```typescript
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');

const app = express();

app.use(createProxyMiddleware({
  target: 'http://www.example.org',
  changeOrigin: true
}));

app.listen(3000);
```

This might happen if you bump the version in your `package.json` by hand...
Instead of bumping it with `npm install http-proxy-middleware@latest`

You could try to run `npm install --force` or `yarn install --force`.

If that doesn't work remove the `node_modules` and run `npm i` or `yarn` to reinstall all packages.

**Comment by coreyleelarson** [comment]
I'm not quite sure what was happening, but it is working now.

I suspect it had something to do with yarn using the wrong version. My app references 1.0.0 but another one of my dependencies references an older version.
