### ISSUE TITLE
typing and documentation for router's return value seems to be incorrect

### ISSUE THREAD

**Issue by dylang** [chimurai/http-proxy-middleware#408]
### Steps to reproduce

Using TypeScript:

This is typed correctly, but does not work:
```ts
// options
router: (req) => {
	const newTarget = { 
		host: req.context.host || 'localhost',
		protocol: req.context.protocol || 'https:',
		port: req.context.port || 8080
	};
	return `${target.protocol}//${host}:${port}`;
},
```

The return value is typed incorrectly, but this works:

```ts
// options
router: (req) => {
	const newTarget = { 
		host: req.context.host || 'localhost',
		protocol: req.context.protocol || 'https:',
		port: req.context.port || 8080
	};

	return newTarget;
},
```

### Expected behavior

* `router` return type seems like it should be something like:
```ts
interface RouterReturnValue { 
	host: string; 
	protocol: 'http:' | 'https:';  // the : is required!
	port: number;
}
```

### Actual behavior

Using a string doesn't work to dynamically set the `target`.

### Workaround

```ts
router: (req) => {
	const newTarget = { 
		host: req.context.host || 'localhost',
		protocol: req.context.protocol || 'https:',
		port: req.context.port || 8080
	};
	return (newTarget as unknown) as string;
}
```

### Reproducible Demo

I'm not sure yet how to make a standalone example but I can try if needed.

**Comment by chimurai** [comment]
The result of `router` is fed back to `http-proxy-middleware`'s `target`
(which the same as `http-proxy`'s `target`)

Looks like their `target` more complete now.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy/index.d.ts#L20

Here you can find their PR with the changes:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41321

Too bad they didn't export the `ProxyTarget` type...

Care to give it a try?

**Comment by dylang** [comment]
Yes! That worked for me. Great find! And we're luck, they don't need to export it:

```ts
    router?: {
        [hostOrPath: string]: httpProxy.ServerOptions['target'];
    } | ((req: Request) => httpProxy.ServerOptions['target']) | ((req: Request) => Promise<httpProxy.ServerOptions['target']>);
```

Doing types this way ensures that your types will match the input types to their API even if they change the names of their internal interfaces.

**Comment by dylang** [comment]
Let me know if you want a PR for this too and if it can be the same PR as #407.
