### ISSUE TITLE
Disable SSL cert checking

### ISSUE THREAD

**Issue by carlskii** [chimurai/http-proxy-middleware#41]
Hi is this possible ? I'm running against a dev server and can't get a valid cert until we go to prod.

**Comment by carlskii** [comment]
Ignore that - found it.

**Comment by chimurai** [comment]
@carlskii 
Could you share the answer to your question.
Might be useful in case someone else encounters the same problem. Thanks!

**Comment by carlskii** [comment]
I just added the following: 

```javascript
var proxy = proxyMiddleware('/api', {
  target: 'https://xxx.xxx.xxx.xxx',
  changeOrigin: true,    // for vhosted sites, changes host header to match to target's host
  secure: false
 // headers: {'content-type': 'application/json'}
});
```

Just added the `secure: false` option

**Comment by chimurai** [comment]
Great. Thanks!
