### ISSUE TITLE
Do Not Proxy Request When Custom Router Throws Error

### ISSUE THREAD

**Issue by bforbis** [chimurai/http-proxy-middleware#411]
I am trying to take complete control of the target routing. I would like the proxied request to be aborted before the client socket is opened if my router was unable to determine a target host. Is this possible to do?

```js
createProxyMiddleware({
  // target is a required parameter
  target: 'do-not-use', 
  router: (req) => {
    try {
      ...
      return target;
    }
    catch (err) {
      req.res.sendStatus(500);
    }
  },
});
```

The current http-proxy code will still use the original target "do-not-use". I would rather the proxy just abort the request entirely if the router function does not return a target.

**Comment by chimurai** [comment]
Currently it is not possible.

How do you use the http-proxy-middleware?

Via webpack-dev-server? Or do you mount it in your own express or express-like server?

**Comment by bforbis** [comment]
This is in an express server.

**Comment by chimurai** [comment]
You could use express's error handling: https://expressjs.com/en/guide/error-handling.html

Basically `throw` an error in the `router` and use a default middleware error handler to handle all sorts of errors from middlewares.

```typescript
import * as express from 'express';
import { createProxyMiddleware } from 'http-proxy-middleware';

const app = express();

const proxy = createProxyMiddleware({
  // target is a required parameter
  target: 'do-not-use', 
  router: (req) => {
    try {
      ...
      return target;
    }
    catch (err) {
      throw err;
    }
  },
});

app.use(proxy);
app.use((err, req, res, next) => {
  res.send(500, 'oops some routing went wrong')
});

**Comment by bforbis** [comment]
I tried this out, but I am still getting UnhandledPromiseRejection errors logged to the console. Should the code that calls prepareProxyRequest catch the error and then pass it to the next() function?

```
      try {
        const activeProxyOptions = await this.prepareProxyRequest(req);
        this.proxy.web(req, res, activeProxyOptions);
      }
      catch(err) {
        next(err);
      }
```

Also, Using your example error function did not work for me. I get the following error from express
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
```
I think maybe the headers are already set up somewhere, but I couldn't figure out where.

**Comment by chimurai** [comment]
Was hoping that `UnhandledPromiseRejection` wouldn't happen.

Your suggestion to solve it makes sense than.

Do you mind creating PR with your suggestion to fix this issue?
