### ISSUE TITLE
Client certificate isn't been recognized

### ISSUE THREAD

**Issue by atalis** [chimurai/http-proxy-middleware#42]
Hi,

I'm creating a proxy to a server that uses certificate authentication.  
```javascript
    server.middleware = proxyMiddleware('/providers/sse/services/scim',
        {target: 'https://backendserver.com',
          changeOrigin: true,
          port: 443,
          secure: true,  // ignore cert errors
          agent: false,
          https: {
            key: fs.readFileSync('private_key.pem'),
            cert: fs.readFileSync('client_cert.pem')
          },
        });
```

However, when I connect to *my* server, I'm being prompted for the credentials when the request is being forwarded to the backend server.

At the same time, the following code (written by someone else) that creates an http server directly, passing the same client certificate data, passes the client cert data successfully, and I can retrieve data from the backend server without a prompt:

```javascript
http.createServer(onRequest).listen(3030);

function onRequest(client_req, client_res) {
 
  var options = {
    key: fs.readFileSync('private_key.pem'),
    cert: fs.readFileSync('client_cert.pem'),
    agent: false,
    host: backendserver,
    method: client_req.method,
    path: client_req.url,
    headers:{
        Host: backendserver
    }
  };

  var proxy = https.get(options, function(res) {
    client_res.on('data', function(d) {
  });

  res.pipe(client_res, {
      end: true
    });
  });

  client_req.pipe(proxy, {
    end: true
  });
```

Any idea of what might be wrong?

**Comment by chimurai** [comment]
Did you have a look at the [examples](https://github.com/nodejitsu/node-http-proxy/tree/master/examples) of the underlying [`http-proxy`](https://github.com/nodejitsu/node-http-proxy) library?

https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/proxy-https-to-http.js
https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/proxy-https-to-https.js

Think you are setting the certificates on the wrong property;
`ssl` should be used instead of `https`

**Comment by atalis** [comment]
I figured this out, finally.  Instead of providing certificate and key as part of the https (or ssl) object, it should be a part of the target object:

    server.middleware = proxyMiddleware('/providers/sse/services/scim',
        {
          target: {
            host:  'https://backendserver.com',
            port: 443,
            protocol: 'https:',
            key: fs.readFileSync('private_key.pem'),,
            cert: fs.readFileSync('client_cert.pem')
          },
          changeOrigin: true
        });

**Comment by chimurai** [comment]
Thanks for sharing the answer!

**Comment by sternetj** [comment]
@atalis I am having a similar issue with my certificate not being recognized. I tried your solution but I am getting an `ENOTFOUND` error. I specified my url just as you did in your answer. Is there something I am missing?

```
proxyMiddleware('/providers/sse/services/scim',
    {
      target: {
        host:  'https://mybackendserver.com',
        port: 8443,
        protocol: 'https:',
        key: process.env.KEY,
        cert: process.env.CERT
      },
      changeOrigin: true
    });
```

**Comment by imbenwolf** [comment]
> @atalis I am having a similar issue with my certificate not being recognized. I tried your solution but I am getting an `ENOTFOUND` error. I specified my url just as you did in your answer. Is there something I am missing?
> 
> ```
> proxyMiddleware('/',
>     {
>       target: {
>         host:  'https://mybackendserver.com',
>         port: 8443,
>         protocol: 'https:',
>         key: process.env.KEY,
>         cert: process.env.CERT
>       },
>       changeOrigin: true
>     });
> ```

had the same issue: try removing the 'https://' part in your host option
