### ISSUE TITLE
router bad works

### ISSUE THREAD

**Issue by PavlenkoXX** [chimurai/http-proxy-middleware#424]
We are using this package as middleware like

`app.use(proxyMiddleware);`

Where proxyMiddleware is our js file

```
const { createProxyMiddleware } = require('http-proxy-middleware');
const proxyParameters = {
  target: 'http://example.com/':,
  changeOrigin: true,
  router: (req) => { return 'http://intended-destination.com/'},
};

module.exports = () => createProxyMiddleware(proxyParameters);
```

Logging of router each time shows the correct link, but sometimes we're faced with the problem that proxy sends the request to link from target field except for host from router field
And as a result, we've got error:

> [HPM] Error occurred while trying to proxy request /api/someRoute?skip=0&limit=20 from host:port to http://example.com/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

We expect to request to http://intended-destination.com/, but as result sometimes (4 times from 10) request goes to http://example.com/

I think that it will be a bug from your side and I think maybe package send a request before router initialization sometimes
Can you check this problem?

In this case I send request to http://127.0.0.1:8080/api/id/user => in application default link for redirect will be http://127.0.0.1:8062, but in middlewares I found that this route will be redirected to http://127.0.0.1:8064 and in logs of router function in htttp-proxy-middleware was shown correct link = > request goes to 8062 port instead of 8064.

**Comment by chimurai** [comment]
Could you provide a **minimal working example** ([README](https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md#minimal-example
)) in which this behaviour is reproduced?

**Comment by PavlenkoXX** [comment]
In this case I send request to http://127.0.0.1:8080/api/id/user => in application default link for redirect will be http://127.0.0.1:8062, but in middlewares I found that this route will be redirected to http://127.0.0.1:8064 and in logs of router function in htttp-proxy-middleware was shown correct link = > request goes to 8062 port instead of 8064.
