### ISSUE TITLE
Lodash dependency - required?

### ISSUE THREAD

**Issue by Daveawb** [chimurai/http-proxy-middleware#428]
### Is this a question? Yes and... no? Go figure.

I noticed that I had the full blown version of lodash in my dependencies once I had installed this package (which is excellent btw). I started to look through the code base to see if it really was required and I have only found these usages:

**context-matcher.ts**
_.isFunction
_.isString

**config-factory.ts**
_.assign
_.isString
_.isPlainObject

**handlers.ts**
_.camelCase
_.get
_.isFunction

**http-proxy-middleware.ts**
_.assign
_.isFunction

**path-rewriter.ts**
_.isFunction
_.forEach
_.isEmpty
_.isPlainObject
_.isUndefined
_.isNull
_.isEqual
_.isPlainObject
_.forIn

**router.ts**
_.isPlainObject
_.isFunction
_.forIn

Each one of these dependencies can be achieved easily with ES6 without the need for lodash, would you be willing to receive a PR to remove this dependancy?

Most of my projects are built by CI many times / day and anything I can do to reduce the time needed to bootstrap each run is always appeciated.

### Is this a bug report?

No

### Is this a feature request?

Sort of. This request is to remove the lodash dependancy from the project.

Motivation:
- Faster installs. Better performance.

### Setup

Not applicable

**Comment by chimurai** [comment]
Ah, that's a trace of the node 0.10 era. Before we had transpilers like Babel or TypeScript.
Only recently converted to TypeScript to start modernising the codebase.
It's on the todo list to remove it.
Just didn't had the chance to work on it.

**Comment by Daveawb** [comment]
@chimurai happy to put in a PR to remove this.

The only ones I can see that'll need maybe more than a simple change are:
 `_.camelCase`
`_.get` * depending on how it's used

**Comment by chimurai** [comment]
@Daveawb , would be really nice to have a helping hand.

Not always pretty to face the facts... 

source: [bundlephobia.com](https://bundlephobia.com/result?p=http-proxy-middleware@1.0.3)
![image](https://user-images.githubusercontent.com/655241/80726504-c2a5d780-8b04-11ea-9c48-fb370d94d382.png)

**Comment by Daveawb** [comment]
Says it all doesn't it 💯

Sure, I've just had to do this for a number of my own repos so happy to take a look this weekend.

**Comment by Daveawb** [comment]
Made some headway over the weekend. A few tests still failing, will get to them this week at some point.

**Comment by chimurai** [comment]
Nice. Think it is better to have `strict: true` in a separate PR.

**Comment by lattam** [comment]
You can also install only the functions you really use. That should reduce the size significantly.
```
npm i lodash.isfunction
```
etc.

**Comment by Daveawb** [comment]
@lattam I did consider this but really they still bring in a host of lodash functions that just aren't needed. Also, they're removing the individual function imports in v5 https://github.com/lodash/lodash/issues/3838#issuecomment-398592530

**Comment by s100** [comment]
The priority of this task may be about to increase due to [this prototype pollution vulnerability in `lodash`](https://github.com/lodash/lodash/issues/4738), which `lodash`'s maintainers [seem not to be acting on](https://github.com/lodash/lodash/pull/4759).

**Comment by Daveawb** [comment]
Yep ok, I'll crack on at the weekend, apologies, been a bit inactive on this for a while.

**Comment by Daveawb** [comment]
@chimurai nearly there now. I have 4 failing e2e tests that I need to sort out.

**Comment by chimurai** [comment]
let me know if you need any help

**Comment by Daveawb** [comment]
> @chimurai nearly there now. I have 4 failing e2e tests that I need to sort out.

Actaully a second set of eyes on this might be useful. Debugging the websocket test is a pain.
