### ISSUE TITLE
x-www-form-urlencoded

### ISSUE THREAD

**Issue by stigmat4j** [chimurai/http-proxy-middleware#43]
Hi.
Header 'Content-Type: application/x-www-form-urlencoded'
Not working...
Error:
[HPM] Proxy error: ECONNRESET. localhost -> "api.*.com/oauth/token"

**Comment by chimurai** [comment]
Please provide more information:
https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md

Can you provide a minimal working example, if you think it is a bug?

**Comment by stigmat4j** [comment]
My request
```js
export function fetchToken(data) {
  let body = {
    username: data.email,
    password: data.password,
  };
  return fetch(`/oauth/token`, {
    method: 'post',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded'
    },
    body: JSON.stringify(body)
  })
  .then((r) => r.json());
}
```

My server.js
```js
const proxy = proxyMiddleware(['/api', '/oauth'], {
  target: 'http://api.tradeintel.com/',
  xfwd: true   (meybe???)
});

app.use(proxy);
```

Other requests with 'Content-Type: application\json' is good working.

**Comment by chimurai** [comment]
Not sure what is wrong.

Did you try the `changeOrigin` option?
Assuming your target server is an vhost server. (shared ip)

```javascript
const proxy = proxyMiddleware(['/api', '/oauth'], {
  target: 'http://api.tradeintel.com/',
  changeOrigin: true
});
```

**Comment by stigmat4j** [comment]
No, changeOrigin did not help
![Alt text](http://i.imgur.com/vQcvRyz.png)

**Comment by chimurai** [comment]
Try checking this thread: https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-163398924

If you are using multiple middlewares, make sure http-proxy-middleware is on top.
The order is might matter.

**Comment by stigmat4j** [comment]
Yeah!
I'm commented 
```js
// app.use(parser.json());
// app.use(parser.urlencoded({ extended: true }));
```
It works :)
Thx!

**Comment by chimurai** [comment]
Np!

**Comment by exalted** [comment]
@chimurai After all these years, this issue has cost me quite some time. I think it's worthwhile adding a mention about other default/built-in middleware possibly messing with this one. I understand not everyone uses Express, yet I bet many do, so a few lines in the README would save a bunch of time for many folks and improve the UX overall, I think. ✌️
