### ISSUE TITLE
matchSingleStringPath

### ISSUE THREAD

**Issue by gitshuang** [chimurai/http-proxy-middleware#431]
### Is this a bug report?

(Yes)

function matchSingleStringPath(context, uri) {
  const pathname = getUrlPathName(uri);
  return pathname.indexOf(context) === 0;
}

whynot : pathname==context 
pathname.indexOf(context) === 0 cannot be exactly

**Comment by chimurai** [comment]
Not sure if I understand your problem. Can you elaborate it a bit more?
