### ISSUE TITLE
Subdomain routing not working per examples.

### ISSUE THREAD

**Issue by Daemach** [chimurai/http-proxy-middleware#433]
I've been trying to use this component to make browsersync pass subdomains while in proxy mode but I must be misunderstanding something.  I want to get to the point that browsersync launches to http://localtest.me:81 and proxies http://localtest.me:80, and http://subdomain.localtest.me:81 proxies http://subdomain.localtest.me:80.  I tried following these instructions from only 11 months ago but get a "lassie error" from browsersync: https://stackoverflow.com/questions/56295613/browsersync-proxy-subdomains.  I've posted my own question here (no response): https://stackoverflow.com/questions/61492225/how-do-i-proxy-subdomains-with-browsersync-http-proxy-middleware

I also tried this with the code below (same lassie error):  https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/virtual-hosts.md

```
const { createProxyMiddleware } = require('http-proxy-middleware');

const options = {
  target: 'http://localtest.me:80',
  changeOrigin: true,
};

const apiProxy = createProxyMiddleware('/', options);

gulp.task('serve', () => {
    bs.init({
        proxy: {
            middleware: [apiProxy]
        },
        host: "localtest.me",
        port: 81,
        open: 'external',
        notify: false
    });
```

Can you help please?

**Comment by chimurai** [comment]
Anwsered in https://stackoverflow.com/a/56295614/3841188
