### ISSUE TITLE
Support Unix domain socket

### ISSUE THREAD

**Issue by kingsimba** [chimurai/http-proxy-middleware#434]
### Is this a feature request? Yes

I'd like to use ExpressJS and delegate to Nginx on the same machine.
Nginx listens on "unix:/home/simba/gateway.sock" instead of a port number.
http://nginx.org/en/docs/http/ngx_http_core_module.html#listen

```
server
{
    listen       unix:/home/simba/gateway.sock;
    server_name  navicore.mapbar.com;
    ...
}
```

From my past experience, Unix domain socket has much less connection overhead.
Even without "connection: keep-alive", the performance will be maximized.

So is it possible to add this support?

**Comment by chimurai** [comment]
This feature should be requested in the upstream `http-proxy` library

https://github.com/http-party/node-http-proxy/issues

Please link the issues so progress can be tracked. Thanks

**Comment by kingsimba** [comment]
Thanks, I found out it's in fact supported already, though undocumented.
https://github.com/http-party/node-http-proxy/issues/1178
So is this feature also supported in http-proxy-middleware's `createProxyMiddleware()`'s `target` options?

**Comment by chimurai** [comment]
Should work.

`createProxyMiddleware()`'s `target` is directly passed to `http-proxy`'s `target`

If you use typescript. You should have typings for it as well: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy/index.d.ts#L29

**Comment by lichih** [comment]
I don't think createProxyMiddleware()'s target is directly passed to http-proxy's target.
It's been assumed to be a url string to do split and various process before sending to http-proxy.

**Comment by lichih** [comment]
> Should work.
> 
> `createProxyMiddleware()`'s `target` is directly passed to `http-proxy`'s `target`
> 
> If you use typescript. You should have typings for it as well: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/http-proxy/index.d.ts#L29

I don't think createProxyMiddleware()'s target is directly passed to http-proxy's target.
It's been assumed to be a url string to do split and various process before sending to http-proxy.

**Comment by chimurai** [comment]
createProxyMiddleware passes `target` directly to `http-proxy`.

http-proxy does accepts different shapes of data for `target`
- string
- Partial<url.Url>
- ProxyTargetDetailed object

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/eefa7b7fce1443e2b6ee5e34d84e142880418208/types/http-proxy/index.d.ts#L134-L135

> It's been assumed to be a url string to do split and various process before sending to http-proxy.

If you can point out where this happens in http-proxy-middleware, I can take a look at it.

**Comment by chimurai** [comment]
Hope this example will be helpful:

## server with proxy to a Unix domain socket

```js
import express from 'express';
import { createProxyMiddleware } from 'http-proxy-middleware';

const app = express();

app.use(createProxyMiddleware({
  target: {
    socketPath: '/tmp/unix.sock',
  }
}));

app.listen(3000, () => {
  console.log('Example app listening on port 3000!');
});
```

## target server listening on Unix domain socket

```js
import express from 'express';

const app = express();

app.get('/', (req, res) => {
  res.send('Hello World!');
});

// listen to unix domain socket
app.listen('/tmp/unix.sock', () => {
  console.log('Example app listening on port /tmp/unix.sock!');
});
```
