### ISSUE TITLE
http-proxy vulnerability is a high vulnerability in npm audit

### ISSUE THREAD

**Issue by dagda1** [chimurai/http-proxy-middleware#439]
### Is this a bug report?

Running `npm audit` or `yarn audit` is returning a high vulnerability due to the `http-proxy` dependency.

`npm audit`

or

`yarn audit`

### Expected behavior

No high vulnerabilities

(Write what you thought would happen.)

### Actual behavior
a high vulnerability

**Comment by chimurai** [comment]
https://github.com/http-party/node-http-proxy/issues/1446

**Comment by chimurai** [comment]
published in `http-proxy-middleware@1.0.4`
