### ISSUE TITLE
compatibility with fastify ?

### ISSUE THREAD

**Issue by matth-c3** [chimurai/http-proxy-middleware#444]
Hello, 

Switching from `express` to [fastify](https://github.com/fastify/fastify), I was wondering if it could be compatible ( no `.use` like `express` as middleware are handle differently )  ?  

im interrested in [routers case](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md).

Thanks

**Comment by dedd1993** [comment]
I'm interested too

**Comment by andyghiuta** [comment]
You can register the routes you want like this:

```

  const apiProxy = createProxyMiddleware({
    target: 'https://example.com',
  });
  app.get('/api', apiProxy);
  app.post('/api', apiProxy);
  app.put('/api', apiProxy);
  app.delete('/api', apiProxy);
```

**Comment by chimurai** [comment]
Haven't used fastify yet.
Might be possible from their documentation: https://github.com/fastify/fastify/blob/main/docs/Middleware.md#middleware
