### ISSUE TITLE
Is it changeOrigin required???

### ISSUE THREAD

**Issue by wkh2** [chimurai/http-proxy-middleware#446]
### Is this a question?

(write your question here)
### yes,
- I want to know, Is changeOrigin required ??
- 我想问配置代理的时候，changeOrigin这个参数是否为必须配置的。

>>> 因为我在一个react项目中使用的时候，之前的代理配置一直是没有添加这个参数的，代理可以生效，但是今天去访问的时候，代理不生效了。

- the old config :

```
app.use(
    '/api',
    proxy({
      target: 'http://**.*.com'
    })
  )
```
- it doesn't work.
- so I add chaneOrigin.
- the new config 
```
 app.use(
    '/api',
    proxy({
      target: 'http://**.*.com',
        changeOrigin: true,
    })
  )
```
- it is ok.
 ## So, I wonder why?

### Is this a bug report?

(write your answer here)

### Is this a feature request?

(write your answer here)

### Steps to reproduce

(Write your steps here:)

1. 2. 3.

### Expected behavior

(Write what you thought would happen.)

### Actual behavior

(Write what happened.)

### Setup

- http-proxy-middleware: _version_
- http-proxy-middleware configuration
- server: _connect/express/browser-sync..._ + _version_
- other relevant modules

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chimurai** [comment]
This is explained in the documentation:

> 💡 Tip: Set the option changeOrigin to true for name-based virtual hosted sites.

https://en.wikipedia.org/wiki/Virtual_hosting#Name-based

Whether it is required, depends on the target server you are connecting to.
