### ISSUE TITLE
Transfer-encoding should override content-length

### ISSUE THREAD

**Issue by siikasmaa** [chimurai/http-proxy-middleware#447]
### Is this a bug report?

Yes

### Is this a feature request?

No

### Steps to reproduce

1. Setup simple proxy from demo below
2. Set target to any server that serves `gzip` encoded content
3. Request the route that has the demo proxy setup
4. Check that the header `transfer-encoding` exists and `content-length` doesn't

### Expected behavior

Request should be proxied.

### Actual behavior

The following error message is logged `HPE_UNEXPECTED_CONTENT_LENGTH`. 

The request is following the RFC standard. https://tools.ietf.org/html/rfc7230#section-3.3.3

### Setup

- http-proxy-middleware: 0.19.2
- http-proxy-middleware configuration: none

#### client info

MacOS 10.14.6
Google Chrome 83.0.4103.97
Node 12.13.0
Express 4.17.1

#### target server info

Demo page that should send the headers `content-encoding: gzip` and `transfer-encoding: chunked`

### Reproducible Demo

```
const proxy = require('http-proxy-middleware')

const app = express()


app.use('/', proxy({ target: 'http://anglesharp.azurewebsites.net/Chunked' }))

app.listen(8080, '::')
```

**Comment by chimurai** [comment]
Unable to reproduce.
The following example works with chunked transfer encoding:

```js
const express = require('express');
const { createProxyMiddleware } = require('http-proxy-middleware');

const app = express();

app.use('/Chunked', createProxyMiddleware({
    target: 'http://anglesharp.azurewebsites.net',
    changeOrigin: true,
  })
);

app.listen(3000);

console.log('[DEMO] Server: listening on port 3000');
console.log('[DEMO] Opening: http://localhost:3000/Chunked');

```

**Comment by chimurai** [comment]
Looks like server implementation issue (not a proxy issue):

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2

>   A sender MUST NOT send a Content-Length header field in any message
>   that contains a Transfer-Encoding header field.

---

Reproduced the error with:

```js
import { createServer as createNetServer } from 'node:net';
import express from 'express';
import request from 'supertest';
import { createProxyMiddleware } from './dist/index.js';

const upstream = createNetServer((socket) => {
  socket.on('data', () => {
    const body = 'hello';
    const response = [
      'HTTP/1.1 200 OK',
      'Content-Type: text/plain',
      'Transfer-Encoding: chunked',
      'Content-Length: 999',
      'Connection: close',
      '',
      body.length.toString(16),
      body,
      '0',
      '',
      '',
    ].join('\r\n');
    socket.write(response);
    socket.end();
  });
});

await new Promise((resolve) => upstream.listen(0, '127.0.0.1', resolve));
const addr = upstream.address();
const target = `http://127.0.0.1:${addr.port}`;

const app = express();
app.use(
  '/',
  createProxyMiddleware({
    target,
    on: {
      error(err) {
        console.log('PROXY_ERROR_CODE', err?.code);
        console.log('PROXY_ERROR_MSG', err?.message);
      },
    },
  }),
);

const res = await request(app).get('/');
console.log('STATUS', res.status);

await new Promise((resolve) => upstream.close(resolve));
```

```shell
PROXY_ERROR_CODE HPE_INVALID_CONTENT_LENGTH
PROXY_ERROR_MSG Parse Error: Content-Length can't be present with Transfer-Encoding
```
