### ISSUE TITLE
Allow blank 'target' when specifying a custom router

### ISSUE THREAD

**Issue by stuartthomson** [chimurai/http-proxy-middleware#448]
### Is this a feature request?

Yes

### Motivation
I have a proxy which needs to calculate the target at runtime, using infomation in the request, therefore in the options I specify a 'router'. However, it's not possible to run the proxy without also specifying a static 'target' option. This is forcing me to configure a random target which I never actually want to be resolved.

It seems like I'm not the only one who would find this useful, see [here](https://stackoverflow.com/questions/56571972/how-to-proxy-to-many-different-targets-using-http-proxy-middleware).

Thank you!

**Comment by albedoa** [comment]
Thank you for bringing this up @stuartthomson. I would like to add that it is a problem from a documentation and onboarding standpoint too. The `http://www.example.org` value seen throughout the docs looks like a stand-in to be replaced by the user — and in fact that is its intent for many of the examples — but it wasn't until I found your issue that I realized it is a legitimate, non-dummy value in some cases.
