### ISSUE TITLE
[ERROR] - JSON POST BODY

### ISSUE THREAD

**Issue by prajwalkshetty** [chimurai/http-proxy-middleware#455]
### Is this a question?

When using it with express server and trying to post json body, it seems like anything above 1KB since request fails. I tried using express.json() middle also body parser but it does not seem to go along smoothly with the proxy middleware. Any help regarding this issue would be helpful. Thanks in advance for the time.

this.app
            .use(this.parseRequestBody.bind(this))
            .use('*', apiProxy)
            .use(express.json())
            .listen(proxyPort);

### Is this a bug report?

Yes

### Is this a feature request?

No

- http-proxy-middleware: 1.0.4
- http-proxy-middleware configuration
{
            // This value is not used but this is mandatory.
            target: proxyPort.toString(),
            changeOrigin: true,
            followRedirects: true,
            preserveHeaderKeyCase: true,
            pathRewrite: this.rewritePath.bind(this),
            router: this.rewriteHost.bind(this),
            onError: function onError(err, _req, _res) {
                // TODO: In future expose it as a callback.
            },
            onProxyReq: this.onProxyReq.bind(this)
        }
- server: express
- other relevant modules

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chimurai** [comment]
Can't really do anything without minimal reproducible example.

**Comment by prajwalkshetty** [comment]
@chimurai Sorry forgot to update here. I was able to figure out a fix for the issue from my side. Thanks for taking time to review the issue.

**Comment by chimurai** [comment]
Would be nice if you could share your solution for developers running into the same issue.

**Comment by geoangelotti** [comment]
I tried this from https://github.com/chimurai/http-proxy-middleware/issues/320#issuecomment-600470764 and it worked for me.

> 
> 
> You just need to reorder the middlewares;
> put bodyParser after all proxy middlewares and routes without proxy after bodyParser
> ex:
> 
> ```
> app.use('/proxy/routex', myProxy);
> app.use('/proxy/routey', myProxy);
> 
> ... //then, after all proxys
> app.use(bodyParser.json());
> 
> //and now, all no proxy routes
> app.use('/api', (req,res)=>{
> //TODO
> });
> 
> app.get('/api/test', (req,res)=>{
> //TODO
> });
> ```

**Comment by prajwalkshetty** [comment]
@chimurai @geoangelotti Sorry for the delay in responding. Back i already had in that order even after that it was causing me issues, for me it was a specific issue of post body being greater than 1KB. For some reason something was adding a header i had to delete below headers before passing the request object to the proxy middleware and everything worked fine after that.
delete req.headers['expect']
delete req.rawHeaders['expect']
