### ISSUE TITLE
Path matching failure

### ISSUE THREAD

**Issue by nerdog** [chimurai/http-proxy-middleware#456]
### Is this a bug report?

Yes
I set up two proxies with similar names `/some-proxy`, `/some-proxy-extended`
And they targetted same url because of [this line](https://github.com/chimurai/http-proxy-middleware/blob/master/src/context-matcher.ts#L46)
That `indexOf` must be fixed

**Comment by chimurai** [comment]
This is expected behaviour:

createProxyMiddleware('/api', {...}) - matches paths **starting with** /api

You can use your own function if you want different behaviour:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md#custom-filtering
