### ISSUE TITLE
target as a function

### ISSUE THREAD

**Issue by Cyben** [chimurai/http-proxy-middleware#473]
Is there a way for doing something like this:

let c = 1

const checkDefautSite = () => {
     if(c === 1){
        c++
        console.log(c)
        return "http://localhost:8080"
    }else{
        console.log("here")
        return "http://google"
    }
}

const PORT = 4444 

const app = express();
app.use(createProxyMiddleware({target: checkDefautSite()}));
app.listen(PORT,() => {
    console.log("listening on " + PORT)
})

This code just takes the first return from the function and keeps it for all the request

**Comment by Cyben** [comment]
Thanks for your quick response

**Comment by kuropengin** [comment]
Hello. If this issue has already been resolved, that's great to hear. However, if it has not been resolved, please refer to this.

```ts
var c = 1;
var options = {
  target: 'do-not-use',
  router:async function(req){
    if(c === 1){
        c++;
        return "http://localhost:8080";
    }
    else{
        return "http://google";
    }   
  },
  secure: false,
  changeOrigin: true,
};
const Proxy = createProxyMiddleware(options);
```

**Comment by Cyben** [comment]
Hey, thank you.
I'll try it out.
I'm closing for now, if needed I'll reopen
