### ISSUE TITLE
can not proxy socket.io

### ISSUE THREAD

**Issue by brucewar** [chimurai/http-proxy-middleware#479]
http-proxy-middleware: v1.0.6
socket.io-client: 2.3.1
create-react-app: 4.0.0

### react client:
```js
import io from 'socket.io-client';
const socket = io({
  transports: ['websocket']
});
socket.on('connect', () => {
  console.log('socket.io client connected!');
});
```
### setupProxy.js
```js
const { createProxyMiddleware } = require('http-proxy-middleware');

module.exports = (app) => {
  app.use(
    '/socket.io',
    createProxyMiddleware({
      target: 'http://127.0.0.1:7001',
      changeOrigin: true,
      ws: true
    })
  );
};
```
code above not work.

The websocket works well, if the client code is following:
```js
const socket = io('http://127.0.0.1:7001', {
  transports: ['websocket']
});
```

**Comment by dmichel35** [comment]
It seems to be the same problem that the one described here: #463 

It should fix the issue if you change your code to:

```
module.exports = (app) => {
  app.use(
   createProxyMiddleware('/socket.io', {
      target: 'http://127.0.0.1:7001',
      changeOrigin: true,
      ws: true
    })
  );
};
```

**Comment by brucewar** [comment]
not an issue

**Comment by gavihs** [comment]
> It seems to be the same problem that the one described here: #463
> 
> It should fix the issue if you change your code to:
> 
> ```
> module.exports = (app) => {
>   app.use(
>    createProxyMiddleware('/socket.io', {
>       target: 'http://127.0.0.1:7001',
>       changeOrigin: true,
>       ws: true
>     })
>   );
> };
> ```

Yes, I had the same issue and this resolves
Just for future reference

/socket.io is inside createProxyMiddleware <- FYI
