### ISSUE TITLE
How to log request and response urls?

### ISSUE THREAD

**Issue by kimmobrunfeldt** [chimurai/http-proxy-middleware#48]
I would like to log each request no matter what status code the target server responded. I'm trying to achieve the following format:

```js
// Format:
// -->  [METHOD] [PATH_REQUESTED_FROM_PROXY] -> [URL_REQUESTED_FROM_TARGET]
// Example:
// -->  GET /v1/users/123 -> https://my-app.herokuapp.com/api/v1/users/123
```

My proxy options are:
```js
var proxyOpts = {
    target: 'https://my-app.herokuapp.com/',
    pathRewrite: {
        '^/v1' : '/api/v1'
    },
    onProxyReq: function onProxyReq(proxyReq, req, res) {
        // Log outbound request to remote target
        console.log('-->  ', req.method, req.path, '->', proxyReq.baseUrl + proxyReq.path);
    },
    onError: function onError(err, req, res) {
        console.error(err);
        res.status(500);
        res.json({error: 'Error when connecting to remote server.'});
    },
    logLevel: 'debug',
    changeOrigin: true,
    secure: true
};
```

Which outputs:
```
-->   GET /api/v1/users/123 -> undefined/api/v1/users/123
```

Problems:
* `req.path` is already converted to the new format with pathRewrite, I would want to log the url which client actually requested from this proxy server
* `proxyReq.baseUrl` is not defined, I'm not sure what I should use to get the host part of the request.

**Comment by chimurai** [comment]
Unfortunately the `req.path` information is destroyed after it has been rewritten.

I do like your suggested improvements to the logging behaviour.

Do you think logging the rewritten path explicitly is useful?

**Comment by chimurai** [comment]
I think will be nice to encode the proxy behavior in the log statements too;
Different arrows indicate what happend:

* `->` default.
* `~>` pathRewrite applied.
* `=>` proxyTable applied.
* `>>` both pathRewrite and proxyTable applied.

So in your use-case; the original url will get logged, its target URI and the pathRewrite arrow.
```
[HPM] GET /v1/users/123 ~> https://my-app.herokuapp.com/api/v1/users/123
```

Let me know what you think.

**Comment by kimmobrunfeldt** [comment]
Thanks for the quick response! If the default format would be that, I'd be happy! :) Looks good to me.

**Comment by chimurai** [comment]
@kimmobrunfeldt, I just published v0.11.0 with the logging improvements. Can you verify this change?

Let me know if more improvements can be made in logging.

**Comment by mgerring** [comment]
@chimurai sorry to raise this issue from the dead, but I'm wondering how to use this info in a test. I need to write a test to ensure that URLs are being rewritten correctly by the proxy, and I don't know how to get the rewritten URL from the request or response object, or, alternately, how I would use the log output of the proxy in a test. Any suggestions?

**Comment by zanona** [comment]
I have to agree with @mgerring as the current behaviour seems a bit confusing. Ideally I would like to simply obtain the final url requested, however both `onProxyReq` and `onProxyRes`, have `host` and `url` as an empty string with the only available field being `path`?

**Comment by materazu** [comment]
+1

**Comment by TheGooner93** [comment]
@mgerring do we have a way to resolve this ?

**Comment by materazu** [comment]
For the only solution was to concatenate manually the information

```
console.log('[HPM][FWD] ', req.method, req.path, '-- TO -->', `${process.env.API_URL}${req.path}`, 'with params', JSON.stringify(req.query));
```

Bad solution but solution :/

**Comment by TheGooner93** [comment]
@materazu I get what you have tried, but this should be something that `proxyReq` provides. It contains the context as the calls are going through, but the callback is somehow not aware of it?

**Comment by materazu** [comment]
I think too, the callback don't give us the context at this time, it's a good point to search why. If i have time to find this in code, i try to fix it.

**Comment by chimurai** [comment]
Think with `onProxyRes` you should be able to get the logging you want:

```js
  onProxyRes: (proxyRes, req, res) => {
    // log original request and proxied request info
    const exchange = `[${req.method}] [${proxyRes.statusCode}] ${req.path} -> ${proxyRes.req.protocol}//${proxyRes.req.host}${proxyRes.req.path}`;
    console.log(exchange); // [GET] [200] / -> http://www.example.com
  },

```
