### ISSUE TITLE
TypeScript error - no exported member 'Config'

### ISSUE THREAD

**Issue by josh-swayed** [chimurai/http-proxy-middleware#482]
This is a continuation of https://github.com/chimurai/http-proxy-middleware/issues/400#issuecomment-677460084

### Is this a bug report?

Yes

### Steps to reproduce

Similar to how the 'Options' type was exported in the TypeScript definitions, the 'Config' type is not exported.

This is causing TypeScript errors when running inside of webpack-dev-server

**Comment by chimurai** [comment]
Don't think this is a bug in this project.

This'll be fixed in webpack-dev-server v4

**Comment by bhldev** [comment]
> Don't think this is a bug in this project.
> 
> This'll be fixed in webpack-dev-server v4

I am receiving this error running outside of webpack

**Comment by slowaways** [comment]
I received this error in my project that uses http-proxy-middleware as dependency too. How to solve this?

**Comment by bhldev** [comment]
> I received this error in my project that uses http-proxy-middleware as dependency too. How to solve this?

Try to reorder the middleware, it worked for me I think
