### ISSUE TITLE
http-proxy-middleware prepends request path to other requests in html files

### ISSUE THREAD

**Issue by ahmedmagdy11** [chimurai/http-proxy-middleware#490]
I am doing pathRewriting to return the HTML file, it returns the HTML file correctly but every other request in the file has the request in front of it which resolves to 404.
for example `<img src="/img/something.png"/>` resolves to `/api/something/img/something.png`,
here is the code I am using for the proxy
```

router.use("/api/link/ticket/*",createProxyMiddleware({target: process.env.URL,changeOrigin:true,prependPath:false , pathRewrite: (path,req)=>{
    console.log("request to proxy: ", path);
    return "/tickets/ticket.html";
}}));
```

here are the logs after **GET** /tickets/ticket.html is requested.
```

request to proxy:  /api/link/ticket/nothing //first call to the HTML file
request to proxy:  /api/link/ticket/images/icon-left.png
request to proxy:  /api/link/ticket/images/header.png
request to proxy:  /api/link/ticket/images/clock.png
request to proxy:  /api/link/ticket/images/ticket-icon.png
request to proxy:  /api/link/ticket/images/bag-icon.png
request to proxy:  /api/link/ticket/images/app-store-icon.png
request to proxy:  /api/link/ticket/fonts/fontsfree-net-sfprodisplay-bold-webfont.woff2
request to proxy:  /api/link/ticket/fonts/fontsfree-net-sfprodisplay-medium-1-webfont.woff2
request to proxy:  /api/link/ticket/images/play-store-icon.png
request to proxy:  /api/link/ticket/fonts/fontsfree-net-sfprodisplay-bold-webfont.woff
request to proxy:  /api/link/ticket/fonts/fontsfree-net-sfprodisplay-medium-1-webfont.woff
```
the question on [stackoverflow](https://stackoverflow.com/questions/65458354/http-proxy-middleware-prepends-request-path-to-other-requests-in-html-files)

**Comment by chimurai** [comment]
You'll have to modify the html response yourself.

With the `responseInterceptor` it should be quite easy to do
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/response-interceptor.md#response-interceptor
