### ISSUE TITLE
When i cyclic transfer interface,something strange happened!

### ISSUE THREAD

**Issue by sky124380729** [chimurai/http-proxy-middleware#491]
When i cyclic transfer interface,something strange happened!

![1609308222(1)](https://user-images.githubusercontent.com/23203328/103333815-29bbc780-4aaa-11eb-9be9-08430af1388f.jpg)

if i don't use http-proxy-middileware 

![19458de7d69c3021ef831d488131698](https://user-images.githubusercontent.com/23203328/103333857-4f48d100-4aaa-11eb-83f0-eab4b52dc78c.png)

so . who can tell me what happend?..

**Comment by chimurai** [comment]
Can't investigate without minimal reproducible example.
Feel free re-open when one can be provided
