### ISSUE TITLE
pathRewriter happening before ProxyTable

### ISSUE THREAD

**Issue by cedric25** [chimurai/http-proxy-middleware#50]
Hi,

My config are like the following one:

(pathRewrite)
`{
    '^/api/one' : '',
    '^/api/two' : ''
}`

and

(proxyTable)
`{
    '/one' : 'http://localhost:3001',
    '/two' : 'http://localhost:3002'
}`

My use case is that I need the complete path to choose the correct proxy, and only after that it should apply my rules concerning pathRewrite.

If I put the pathRewrite step after the proxyTable one, it works well.

Have I missed something?
What would be a solution?

**Comment by cedric25** [comment]
Ok, I should have looked more, looks like it is going to change in v0.10 :)

**Comment by chimurai** [comment]
It's indeed going to change in `v0.10.0`. (fixed in PR #49)

the beta is available via npm:
`npm install http-proxy-middleware@0.10.0-beta`

Could you close the issue if it fixes the issue?

**Comment by cedric25** [comment]
Thank you for your reactivity.
