### ISSUE TITLE
Upgrade the lodash dev dependency to avoid the security issue

### ISSUE THREAD

**Issue by prmanojbabu** [chimurai/http-proxy-middleware#501]
Upgrade the lodash dev dependency to avoid the security issue

lodash 4.17.20 is having  Command Injection and Regular Expression Denial of Service (ReDoS) issue
which has been fixed in 4.17.21

**Comment by chimurai** [comment]
package.json is using semver:

```
"lodash": "^4.17.20"
```

With [semver](https://semver.org) you should be able to get `4.17.21` already.
(You can verify this with a fresh installation)

Updating project lock files should be your responsibility.
