### ISSUE TITLE
Websocket in Gulp(Ionic)

### ISSUE THREAD

**Issue by huigesv123** [chimurai/http-proxy-middleware#51]
I copy your code in gulpfile.js

```javascript
var proxy = require('http-proxy-middleware');

gulp.task('connect', function() {
     connect.server({
       root: ['./app'],
       port: 2301,
       middleware: function(connect, opt) {
         return [
           proxy('/socket', {
             target: 'https://cloud.vanwardsmart.com',
             changeOrigin:true,
             ws: true,      // <-- set it to 'true' to proxy WebSockets
             secure:true
           })
         ]
       }
     });
 });

gulp.task('default', ['connect']);
```

when I use create websocket instance, just like this:

      var wsUrl = 'wss://192.1.10.80:2301/ws';
      var ws = new WebSocket(wsUrl);

the browser show "failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED" error

**Comment by chimurai** [comment]
Not a middleware issue; But it sounds like #24 

Check following examples on how to configure https correctly, since you are trying to open a secure websocket connection (wss:):
https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/

**Comment by huigesv123** [comment]
@chimurai  

I added agent: "https.globalAgent",But still not work

**Comment by chimurai** [comment]
You are trying to connect to: `wss://192.1.10.80:2301/ws`

Is the `wss://` really needed? Try `ws://`

Also the proxy is configured to listen to path `/socket` only.
Since you are connecting to the `/ws` path; the proxy will not do anything.

**Comment by huigesv123** [comment]
@chimurai  I plan to use 'websocket' connect wss://cloud.vanwardsmart.com:2301/ws ,but the server does not allow different Origin!

So I want to use http-proxy-middleware in gulpfile.But I have set in many way but still it dosen't work.
Can you give me a good example???THx !THx !THx! THx!

**Comment by chimurai** [comment]
Can you send logs output for HPM?

Add the option `logLevel` and set it to `silent`

**Comment by huigesv123** [comment]
@chimurai  I don't know it is gulp server, I run 'ionic serve' to run it ,and it's http 

Can you leave a email address to let me send my code to you so that you can check it easy ?

**Comment by chimurai** [comment]
I don't think this is the right place for troubleshooting your application/development setup;
StackOverflow would be a better place for that.

----

Some pointers in your setup:

* make sure \<protocol>/\<host>/\<path> are correctly configured in your client code: `var ws = new WebSocket('wss://192.1.10.80:2301/ws');` versus `var ws = new WebSocket('ws://192.1.10.80:2301/ws');` (no secure socket)
* option `agent: https.globalAgent` is probably needed if you are proxying to a `https:` target.
* use option `pathRewrite` if the path need be changed from `/ws` to `/socket`
* if you client connects to path `ws`, the proxy should also be configured to the same path.

**Comment by chimurai** [comment]
Don't mind if you need help with HPM configuration.
But please use StackOverflow for your project setup.
