### ISSUE TITLE
onError event not firing on error responses from the target

### ISSUE THREAD

**Issue by ayush42** [chimurai/http-proxy-middleware#518]
I am using http-proxy-middleware for proxying my request to target URLs. 
When the target gives any error response (e.g. 400, 401, 403, 404, 500, 503 etc) then onError event is not firing.
Every time, irrespective of the response status, onProxyRes event is fired.

`
proxyOptions = {
    target: 'http://localhost:8080/',
    secure: false,
    router: {
       '/api/search/' : 'http://localhost:8080/search'
    },
    changeOrigin: true,
    pathRewrite: (path): string => {
      const regex = /\/api\/(.*?)\//;
      return path.replace(regex, '/');
    },
    onProxyReq: (proxyReq, req): void => {
         if (['POST','PUT'].includes(req.method)) {
              const payload = JSON.stringify(req.body);
              proxyReq.setHeader('Content-Length', Buffer.byteLength(payload));
              proxyReq.write(payload);
         }
    },
    onProxyRes: (proxyRes, req, res): void => {
      console.log('inside onProxyRes');
    },
    onError: (_err, _req, res): void => {
      console.log('inside onError');
      res.status(500);
      res.json({
        error: 'Error when connecting to remote server.'
      });
    }
  };
`

Is this an expected behavior ? Tested with two versions : 0.20.0 and 1.1.0
Thanks for your help.

**Comment by chimurai** [comment]
400, 401, 403, 404, 500, 503 are valid responses.

`onError` is a wrapper for `http-proxy` `on('error')`.

From their documentation:
> error: The error event is emitted if the request **to** the target fail. **We do not do any error handling of messages passed between client and proxy, and messages passed between proxy and target, so it is recommended that you listen on errors and handle them.**

https://github.com/http-party/node-http-proxy#listening-for-proxy-events

**Comment by ayush42** [comment]
Thanks @chimurai for the clarification.
