### ISSUE TITLE
Custom filter params do not match documentation; pathname is IncomingMessage not String

### ISSUE THREAD

**Issue by davidjgonzalez** [chimurai/http-proxy-middleware#524]
### Is this a question?

I'm running v1.1.2 of http-proxy-middleware.

I am trying to use the custom filter function to only proxy requests whose paths start with /stuff, are being made to my react app, and then proxying them over to http://locahost:8000

The issue is when my filter function is invoked, i get an error for this expression:  `pathname.match('^/stuff')`

__pathname.match is not a function__

It seems like the `pathname` (first param) is being provided as an `IncomingMessage` object, and then 2nd param as a `ServerResponse`.. which is strange since master branch's types.ts certainly looks like it should be String, Request.

Im not sure if the documentation is wrong, or something else is going on?

### Is this a bug report?

Maybe?

### Steps to reproduce

Add the following proxy to a vanilla project (ex. react app)

```
const { createProxyMiddleware } = require('http-proxy-middleware');


module.exports = function(app) {
  
    const filter = function (pathname, request) {   
        const match = pathname.match('^/stuff') && request.headers.host.match('localhost:3000');
        return match;
    };


    app.use(
        filter,
        createProxyMiddleware({
            target: 'http://localhost:8080',
            changeOrigin: true,
            ws: true,
        })
    );
};
```

1. Add this proxy to your project, and install v1.1.2 of http-proxy-middleware
2. Start the project
3. Observe the error 

### Expected behavior

The Filter should filter the requests properly and `pathname.match(..)` should resolve to a function.

### Actual behavior

Error is thrown.

**Comment by chimurai** [comment]
Looks like you used the `filter` in the wrong location.

Should look like this:

```js
    app.use(
        createProxyMiddleware(filter, {
            target: 'http://localhost:8080',
            changeOrigin: true,
            ws: true,
        })
    );

```
