### ISSUE TITLE
Expose `proxyReqWs` events

### ISSUE THREAD

**Issue by llchan** [chimurai/http-proxy-middleware#55]
We can add a `onProxyReqWs` callback analogous to `onProxyReq` for the `proxyReq` events.

Alternatively, we could expose the proxy object itself.  That'd probably give the user the most flexibility in attaching callbacks.

**Comment by chimurai** [comment]
Totally forgot to expose this event; which has been added in http-proxy v1.12.0

https://github.com/nodejitsu/node-http-proxy/compare/1.11.3...1.12.0

Thanks for reporting!

**Comment by chimurai** [comment]
Just published [v0.12.0](https://github.com/chimurai/http-proxy-middleware/releases/tag/v0.12.0).
With this release, you can subscribe to all events from `http-proxy`.
I've added the missing ones: `proxyReqWs`, `open` and `close`.
