### ISSUE TITLE
 [tsl] ERROR in node_modules/http-proxy-middleware/dist/handlers/response-interceptor.d.ts(2,13)

### ISSUE THREAD

**Issue by RichieChoo** [chimurai/http-proxy-middleware#560]
### Is this a question?

(write your question here)

### Is this a bug report?

(write your answer here)

### Is this a feature request?

(write your answer here)

### Steps to reproduce

(Write your steps here:)

1.2.0 build error in webpack 

### Expected behavior

(Write what you thought would happen.)

### Actual behavior

(Write what happened.)

### Setup

- http-proxy-middleware: _version_
- http-proxy-middleware configuration
- server: _connect/express/browser-sync..._ + _version_
- other relevant modules

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by chimurai** [comment]
Can you reproduce this without webpack?

**Comment by chimurai** [comment]
Not sure what happening with reproducible demo.

This internal refactoring might explain it:

- renamed file `handlers.ts` -> `_handlers.ts` https://github.com/chimurai/http-proxy-middleware/pull/520/commits/3aaf63dea6896f5742ac96ea82367ab020272084

- created new folder `handlers` https://github.com/chimurai/http-proxy-middleware/pull/520/commits/e022a2e1eb4ef6a427fe0f8b4c2e2b05df245eb5#diff-69a794fa1a5a20e2980c70b90ebbc08632809a88138e996525ae9b3b6fe5046a

Can you try removing `node_modules` install dependencies again?

**Comment by chimurai** [comment]
Closing issue without reproducible example.

Feel free to reopen when one can be provided.
