### ISSUE TITLE
How can I proxy only GET method

### ISSUE THREAD

**Issue by slavede** [chimurai/http-proxy-middleware#58]
I would like to proxy only some type of methods (in case I have REST api on same url with GET and POST method). Server has implemented only POST method and I should test only that. I can't specify just to proxy POST.

Is it possible to add that feature?

**Comment by chimurai** [comment]
Coincidence or not. I was just working on a new feature which enables you to customise the filtering behaviour.

You'll be able to distinguish POST requests from GET requests...

```
var filter = function (path, req) {
   return (req.method === 'POST' and path.match('^/somepath'))
};

proxyMiddleware(filter, options);
```

**Comment by slavede** [comment]
Excellent. Let's leave this ticket open and you can close it once PR is merged in, ok? Thanks!

**Comment by chimurai** [comment]
Just published a new version to npm.
@slavede: let me know if you run into issues.
