### ISSUE TITLE
[BUG] Proxy Requests Not Timing Out 

### ISSUE THREAD

**Issue by cmullenx** [chimurai/http-proxy-middleware#594]
Please note your issue will be closed without comment if do not fill out the issue checklist and provide ALL the requested information.

**`yarn why http-proxy-middleware` OR `npm ls http-proxy-middleware` output (mask private folder names with \*\*\*\*\*)**

```shell
[1/4] 🤔  Why do we have the module "http-proxy-middleware"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "http-proxy-middleware@1.3.1"
info Has been hoisted to "http-proxy-middleware"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "176KB"
info Disk size with unique dependencies: "596KB"
info Disk size with transitive dependencies: "1.89MB"
info Number of shared dependencies: 15
```

**Please verify that you've followed these steps**

[x] - I've updated to latest `http-proxy-middleware`.

**Describe the bug**

The proxied request does not timeout after the specified time set in options.proxyTimeout passes

**To Reproduce**

If possible, please provide minimal example on CodeSandbox that demonstrates the issue. You can use the following template: https://codesandbox.io/s/http-proxy-middleware-44oc1

**Step-by-step reproduction instructions**

```text
1. Add a proxyTimeout to the configuration object
2. Try the request
```

**Expected behavior**

I expect the request to timeout at the time specified in the proxyTimeout

**`http-proxy-middleware` configuration**

```javascript
const proxyConfig = {
  changeOrigin: true,
  pathRewrite: {
    [`^/proxy`]: '',
  },
  logLevel: 'silent',
  proxyTimeout: tenSeconds,
}

router.use(
  ['/timeoutTest'],
  createProxyMiddleware({
// target goes to an endpoint with a very long request
    target: 'http://localhost:8081',
    ...proxyConfig,
  })
)

```

**Server (please complete the following information):**

- OS: [MacOS]
- NodeJS version: [e.g. 12.16.3]

**Additional context**

**Comment by chimurai** [comment]
`proxyTimeout` is a configuration option from [http-proxy](https://github.com/http-party/node-http-proxy).

If you experience issues with `proxyTimeout` it should be reported in that project:
https://github.com/http-party/node-http-proxy/issues
