### ISSUE TITLE
Will the x-forward-host be modified after the proxy succeeds

### ISSUE THREAD

**Issue by liuyongly** [chimurai/http-proxy-middleware#598]
proxy is successed ，but x-forward-host is wrong
![image](https://user-images.githubusercontent.com/59298480/117536631-abaa9700-b02e-11eb-9dfc-5d259988bcd0.png)
I don't know what happened，but I fixed it like this
![image](https://user-images.githubusercontent.com/59298480/117536649-d137a080-b02e-11eb-829b-64c2744820ef.png)
Wrong x-forward-host can cause such a problem
https://github.com/kubernetes/ingress-nginx/issues/2463

**Comment by chimurai** [comment]
Problems with `xfwd` should be reported in https://github.com/http-party/node-http-proxy/issues
