### ISSUE TITLE
@types deps should be listed under devDependencies

### ISSUE THREAD

**Issue by lionello** [chimurai/http-proxy-middleware#602]
https://github.com/chimurai/http-proxy-middleware/blob/7c86a2c41219cd6022c22897d59df9eb8d159164/package.json#L84

Listing `@types/http-proxy` under the `"dependencies"` pulls in other types as runtime dependencies as well. These should only be needed during development.

This issue was introduced in #369

**Comment by chimurai** [comment]
http-proxy-middleware types are generated and shipped with the package as well:
https://github.com/chimurai/http-proxy-middleware/blob/7c86a2c41219cd6022c22897d59df9eb8d159164/package.json#L6

Removing `@types/http-proxy` from dependencies, will lead to a broken developer experience.

`target` is a transitive property from http-proxy, which will be missing in the code completion:

![image](https://user-images.githubusercontent.com/655241/117708601-4c848800-b1d0-11eb-948c-b927865a4cb3.png)

**Comment by chimurai** [comment]
Feel free to reopen if you have suggestions to remove `@types/http-proxy` without breaking developer experience

**Comment by lionello** [comment]
Ah, yeah you're right. Only by listing the types under `"dependencies"` do they actually get pulled in automatically in the consuming project. TIL!
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies
