### ISSUE TITLE
IP not changing on each request, any solution for the same?

### ISSUE THREAD

**Issue by arunspericorn** [chimurai/http-proxy-middleware#611]
Please note your issue will be closed without comment if do not fill out the issue checklist and provide ALL the requested information.

**`yarn why http-proxy-middleware` OR `npm ls http-proxy-middleware` output (mask private folder names with \*\*\*\*\*)**

```shell
# paste output here
```

**Please verify that you've followed these steps**

[ ] - I've updated to latest `http-proxy-middleware`.

IP couldn't able to change on multiple requests to target

On every request IP is same while hitting the target
If possible, please provide minimal example on CodeSandbox that demonstrates the issue. You can use the following template: https://codesandbox.io/s/http-proxy-middleware-44oc1

**Step-by-step reproduction instructions**

```text
1. ...
2. ...
```

Expected behaviour is to hit the target with different ip's

**`http-proxy-middleware` configuration**

```javascript
// paste code and configuration here
```

**Server (please complete the following information):**

- OS: [e.g. MacOS, Windows]
- NodeJS version: [e.g. 12.4]

**Additional context**

**Comment by chimurai** [comment]
Please ask questions related to your setup in https://github.com/chimurai/http-proxy-middleware/discussions or [stackoverflow](https://stackoverflow.com)
