### ISSUE TITLE
Handling relative paths

### ISSUE THREAD

**Issue by serganus** [chimurai/http-proxy-middleware#62]
Hi,

I am trying to use the proxy in the following setup :

```javascript
//Hosted on http://localhost:4000
var proxyMiddleware = require('http-proxy-middleware');
var proxy = proxyMiddleware('/api/materials/Csi/Model', {
  target: 'http://localhost:8080/newApp',
  changeOrigin: true
});
app.use(proxy);
```

Now when I do - `http://localhost:4000/api/materials/Csi/Model` it does load the target but the dependencies pop out a 404 error.

I fixed for now using apache2 using mod_proxy (proxy reverse), but I want to use your npm module as can add route based authentication when on port 4000.

Thanks
Gautam

**Comment by chimurai** [comment]
Can you give an example of the expected request url to the `target` server?

**Comment by serganus** [comment]
Ok.

I have java application (App01) hosted with URI : `http://localhost:8080/App?Key1=Value1&Key2=Value2&`

Now I want to do two things in my nodejs application (App02) :

- Create a route `/api/materials/Csi/Model/:id` that should proxy to `http://localhost:8080/App?Key1=Value1&Key2=Value2&`. This should also load the dependencies for App01. 
- I also want to do a POST with different values. Something like, If I call `/api/materials/Csi/Model/`, set new values of key1, key 2 using a simple form and when I do post to `/api/materials/Csi/Model/:id/` it should just change the values on App01 URI.

The issue is App01 is java based and I can only set CORS filter for tomcat.

**Comment by chimurai** [comment]
You might want to try the `pathRewrite` option, it allows you to do some fairly basic request-path rewrites.
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/pathRewrite.md

Think you'll run into the same issue as discussed in https://github.com/chimurai/http-proxy-middleware/issues/52. Path rewrites are limited to 1 rewrite currently, when you've defined multiple rewrite rules.

I've been thinking to change this behavior, so multiple rewrites are allowed. Or allow you to provide a custom path rewrite function, so you have full control on some crazy rewrites. :)

```javascript
pathRewrite: function (path) {
   // custom rewrite logic
   return path;  // rewritten path
}
```

**Comment by chimurai** [comment]
@serganus let me know if the previous reply answers question.

**Comment by chimurai** [comment]
#73 should fixed this issue.
