### ISSUE TITLE
Proxy target supports local file path

### ISSUE THREAD

**Issue by 599316527** [chimurai/http-proxy-middleware#63]
I write some local mockup files to debug APIs when server-side is not ready.
It will be nice to write file path in target to proxy local file.

```js
proxyMiddleware('/login/verify', {
    target: 'file:///home/someone/mockup',
    pathRewrite: {
      '^/login/verify': 'login-verify.json'
    }
})
```

**Comment by chimurai** [comment]
imho, this would be using the wrong tool for the wrong job.

Think it is better to start a separate server to serve your static `.json` files and point the proxy to this server.

This way you can customise your setup to your needs.

**Comment by arloduff** [comment]
Actually, I would also like this feature for my own project. Being able to serve local files for certain routes in a development environment is important for most Javascript projects.

**Comment by adamduncan** [comment]
This issue's been closed for a while, but I was in need of a similar requirement in a **create-react-app** ([proxy docs](https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development)).

To workaround, it was a case of storing mock JSON files in the site's public root directory (e.g. `public/data/mocks/test.json` – which get served from `http://localhost:3000/data/mocks/...` when running the application locally). 

Then we configure rewrite on paths, determining whether the `.json` extension was present in the `path`, and proxying to the original public files with and extension if not:

```
// setupProxy.js
const proxy = require('http-proxy-middleware');

const rewriteFn = function(path) {
  if (path.includes('.json')) return path;
  return path.split('/api')[1] + '.json';
};

module.exports = function(app) {
  app.use(
    proxy('/api/data/mocks', {
      target: 'http://localhost:3000', // same target app runs on
      pathRewrite: rewriteFn
    })
  );
};
```

With this setup, we should be able to access the mock data at both the original URL via filename (`http://localhost:3000/data/mocks/test.json`) and the mock API endpoint (`http://localhost:3000/api/data/mocks/test`)

Hope that helps someone.

Related: #333
