### ISSUE TITLE
TypeScript error in http-proxy-middleware/dist/handlers/fix-request-body.d.ts

### ISSUE THREAD

**Issue by zyf540860996** [chimurai/http-proxy-middleware#630]
### Describe the feature you'd love to see

Failed to compile.

D:/code/node_modules/http-proxy-middleware/dist/handlers/fix-request-body.d.ts
TypeScript error in D:/code/node_modules/http-proxy-middleware/dist/handlers/fix-request-body.d.ts(3,13):
'=' expected.  TS1005

    1 | /// <reference types="node" />
    2 | import { ClientRequest } from 'http';
  > 3 | import type { Request } from '../types';
      |             ^
    4 | /**
    5 |  * Fix proxied body if bodyParser is involved.
    6 |  */

**Comment by chimurai** [comment]
Could you use the BUG template?

https://github.com/chimurai/http-proxy-middleware/issues/new?assignees=&labels=bug&template=bug.yml

GitHub activated the [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) feature, which caused the bug template to be unavailable. (It's fixed now)

Sorry for the inconvenience.

**Comment by chimurai** [comment]
Sounds you're using a really old typescript compiler? (https://stackoverflow.com/a/46399668/3841188)
