### ISSUE TITLE
Server crashes when proxied endpoint sends a 304 (Not Modified) response

### ISSUE THREAD

**Issue by alirezamirian** [chimurai/http-proxy-middleware#643]
### `yarn why http-proxy-middleware` OR `npm ls http-proxy-middleware` output (mask private folder names with *****)

```shell
*****@0.0.1 *****
└─┬ *****@0.4.2
  ├─┬ react-scripts@4.0.3
  │ └─┬ webpack-dev-server@3.11.1
  │   └── http-proxy-middleware@0.19.1  deduped
  └─┬ webpack-dev-server@3.11.2
    └── http-proxy-middleware@0.19.1
```

### 

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

Not sure if there is any other factor to that issue or it's solely related to the proxied endpoint sending a 304 Not Modified response, but here is what happens:
Whenever my proxied endpoint sends 200, it all works out fine. When a 304 response comes, it almost always crashes the server and that happens [here](https://github.com/chimurai/http-proxy-middleware/blob/master/src/_handlers.ts#L82) because something is sent when the socket is already closed.

Suggested fixes: Adding a check for whether the socket is still open, it's possible in express API. Although the real issue might be the fact that error handler is invoked on 304 response.

### Step-by-step reproduction instructions

```shell
1. Proxy an endpoint which returns 304
```

### Expected behavior (be clear and concise)

Server should not crash on 304 responses from proxied endpoints.

### What http-proxy-middleware configuration are you using?

```typescript
{
  target: "******",
  secure: false
}
```

### What OS/version and node/version are you seeing the problem?

```shell
MacOS 11.5
Node 12
```

**Comment by chimurai** [comment]
`http-proxy-middleware@0.19.1` is really old and not supported anymore.

Feel free to re-open new issue when this occurs on the latest version
