### ISSUE TITLE
Breaking change in 2.0.1

### ISSUE THREAD

**Issue by ThomWright** [chimurai/http-proxy-middleware#650]
### `yarn why http-proxy-middleware` OR `npm ls http-proxy-middleware` output (mask private folder names with *****)

```shell
public-api@1.1.0 *****/public-api
└── http-proxy-middleware@2.0.1
```

### 

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

A breaking change was released with 2.0.1. The response type for `onProxyRes` used to be `express.Response`, but is now `http.Response`. This should have been a major version change.

### Step-by-step reproduction instructions

```shell
1. Install 2.0.0. Use e.g. `res.status(200).send()` in `onProxyRes`.
2. Update to 2.0.1. See red squiggly lines. Be sad.
```

### Expected behavior (be clear and concise)

No breaking changes in patch version changes.

### What http-proxy-middleware configuration are you using?

```typescript
N/A
```

### What OS/version and node/version are you seeing the problem?

```shell
N/A
```

**Comment by artemtam** [comment]
Can confirm we have our types broken in `2.0.1`. In `2.0.0` the `onProxyReq` definition is the following:

```typescript
(proxyReq: http.ClientRequest, req: Request, res: Response) => void;
```

In `2.0.1` it is changed to:

```typescript
(proxyReq: http.ClientRequest, req: http.IncomingMessage, res: http.ServerResponse, options: httpProxy.ServerOptions) => void;
```

It is definitely a breaking change, so it must have been a major version bump. Also, it is unclear if it is just a wrong type definition, or the real implementation of `onProxyReq` has changed?

**Comment by asself** [comment]
same issue，why min version upgrade lead to break change?
