### ISSUE TITLE
Running subapps and applying proxy

### ISSUE THREAD

**Issue by tomalex0** [chimurai/http-proxy-middleware#66]
Hi,

First of all thanks for the module, i tired it out and works fine. I'm looking for suggestiosn for my current usecase

I have 3 apps, `a, b and c`, where `a` is main app

### a  - main app  running in port 80
   - route.js
     -  `app.get('/a',function(){})`

### b  - sub app running in port 8001
   - route.js
     -  `app.get('/',function(){})`

### c - sub app running in port 8002
   - route.js
     -  `app.get('/',function(){})`

In `app a` code look like this

```
   function onError(err, req, res) {
        res.writeHead(500, {
            'Content-Type': 'text/plain'
        });
        res.end('Something went wrong. And we are reporting a custom error message.');
    }

    var serverB = 'http://localhost:8001';
    var serverC = 'http://localhost:8002';

    var proxyB = proxyMiddleware('/b', {target: serverB, onError : onError});
    var proxyC = proxyMiddleware('/c', {target: serverC, onError : onError});
    app.use(proxyB );
    app.use(proxyC );
```
I will bring down `b or c` for deployment and  will be showing maintenance page accordingly.

Like to know if this configuration is  good enough to support my usecase.  
Please share your thoughts

**Comment by chimurai** [comment]
Hi @tomalex0 , glad to hear this module is useful :)

Your setup looks valid.

With your proposed error handling you'll serve a maintenance page for **all** proxy errors; Even when `b` or `c` are up and running but application errors thrown.

You could decide to serve the maintenance page and a error page, based on the provided error codes. Just be careful not to expose too much info for people with evil intentions  ;)

**Comment by tomalex0** [comment]
Kind of stuck with one scenario were we have a `SSO` module  applied to `http://localhost` validates when url is accessed, `http://localhost/b` and `http://localhost/c` are also validated.   While authenticating  `req.user` value is updated with the `loggedin` user which will get applicable to `b` or `c`.
Is there a way to  pass `req` values  to proxy servers from parent? 

Or is there any preferable approach to address this?

**Comment by chimurai** [comment]
You could try the http-proxy-middleware `onProxyReq` option.

This option exposes the `proxyReq` event from the underlying `http-proxy` library.

From `http-proxy` documentation:
https://github.com/nodejitsu/node-http-proxy#setup-a-stand-alone-proxy-server-with-proxy-request-header-re-writing

> // To modify the proxy connection before data is sent, you can listen
// for the 'proxyReq' event. When the event is fired, you will receive
// the following arguments:
// (http.ClientRequest proxyReq, http.IncomingMessage req,
//  http.ServerResponse res, Object options). This mechanism is useful when
// you need to modify the proxy request before the proxy connection
// is made to the target.

`http-proxy-middleware` recipe:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/proxy-events.md#onproxyreq

**Comment by tomalex0** [comment]
Other than setting headers what options  do we have ? Had hard time figure out

i'm trying to set value `req.something = 'value'` and expecting to get the samein `sub app`
```
 function onProxyReq(proxyReq, req, res) {
       
        proxyReq.myname = 'myname'
        //proxyReq.body.myname = 'myname';
        proxyReq.setHeader('x-added', 'foobar');
       
    }
```

**Comment by chimurai** [comment]
You can check the NodeJS documentation for the options:
https://nodejs.org/api/http.html

Alternatively you also could just `console.log` those objects, just to see what is available.

Can you post your question on StackOverflow too?
Perhaps someone there might come up with a better solution.

(please link this GitHub issue to StackOverflow and vice versa, in case someone has the same question)

**Comment by tomalex0** [comment]
Added a comment to existing question 
http://stackoverflow.com/questions/36416129/edit-post-parameters-prior-to-forwarding-to-a-proxy-target-and-sending-response/36437108#comment61097514_36437108

**Comment by tomalex0** [comment]
@chimurai  one option suggested from stackoverflow is to use `router.all` ,

https://github.com/tomalex0/middleware-patterns/blob/master/index.js

Couldn't make it work until now. Let me know your thoughts
