### ISSUE TITLE
implement  setHeaders on OutgoingMessage

### ISSUE THREAD

**Issue by m-davoodi** [chimurai/http-proxy-middleware#665]
### Describe the feature you'd love to see

On the `OutgoingMessage`, there is a method called `setHeader`, but in order to set an array of headers, you must loop through the array and set every header manually.

```js
onProxyReq(proxyReq, req) {    
  const headers = getMyCustomeHeaders();
  for (const [key, value] of Object.entries(headers)) {
    proxyReq.setHeader(key, value);
  }
}
```

It would be better to have a method like `setHeaders` which provides an array of headers and sets them all on request.
If it's okay, I'll submit a pull request for the feature

**Comment by chimurai** [comment]
What is your suggested interface / usage example?

**Comment by chimurai** [comment]
Closing issue due to lack of response. Feel free to re-open.
