### ISSUE TITLE
Change target at runtime

### ISSUE THREAD

**Issue by klimashkin** [chimurai/http-proxy-middleware#67]
Hi! It would be great to have some method to change proxy target in runtime by some user interaction!
Without restarting express or httpserver

**Comment by chimurai** [comment]
Hi @klimashkin 

Can you elaborate on "some user interaction"?

It would be helpful if you can describe some use-cases.

**Comment by chimurai** [comment]
Think https://github.com/chimurai/http-proxy-middleware/issues/54 might solve this issue. (WIP)

**Comment by chimurai** [comment]
published in [v0.16.0](https://github.com/chimurai/http-proxy-middleware/releases/tag/v0.16.0)
