### ISSUE TITLE
How to configure tunneling proxy 

### ISSUE THREAD

**Issue by samithaf** [chimurai/http-proxy-middleware#68]
Problem Description

I am using proxy middleware to communicate with an endpoint which lives in open internet but I am behind a corporate proxy. So when I try to connect to the endpoint I am getting following error.

ROXY ERROR: ENOTFOUND. localhost:3000 -> https://www.example.com.au/login

I wonder how to configure **agent** for http-proxy-middleware. 

I have tested a simple https with a **agent** and works fine and code as follows.

```javascript
var tunnel = require('tunnel');
var tunnelingAgent = tunnel.httpsOverHttp({
  proxy: {
    host: 'office.proxy.com.au',
    port: 8080
  }
})

var https = require('https')
  var post_req = https.request({
    host: 'www.example.com.au',
    port: '443',
    path: '/logon',
    method: 'GET',
    agent: tunnelingAgent,
    timeout: 10000,
    followRedirect: true,
    maxRedirects: 10
  }, function(res) {
    res.setEncoding('utf8');
    res.on('data', function (chunk) {
      console.log('Response: ' + chunk);
    });
  });
  post_req.write("name=mario");
  post_req.end();
```

**Comment by chimurai** [comment]
This question is probably related to: https://github.com/chimurai/http-proxy-middleware/issues/22

You might want to check out the corporate proxy example: https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md

Try to use `https-proxy-agent` instead of `tunnel`. Hopefully it will give the desired result.

**Comment by samithaf** [comment]
@chimurai thanks heaps for the reply. I will check first thing in the morning (Aus/Syd) time and update the thread

**Comment by samithaf** [comment]
I am closing this since it's works perfectly well when I pass a https agent as @chimurai mentioned in the post

**Comment by anomistu** [comment]
All seems fine with the proposed solution, yet my auth headers (auth: user:pass option) don't seem to be passed to the endpoint. I'm continuously prompted for my credentials no matter what I do...
Any advice?

**Comment by Tits-McGee** [comment]
Sorry to bring up such an old issue!
When using this solution, proxyReq.SetHeader breaks - the error message is Cannot set headers after they are sent to the client
Any help will be appreciated!

**Comment by jaredxx1** [comment]
> #22

Same here

**Comment by chimurai** [comment]
Please use https://github.com/chimurai/http-proxy-middleware/issues/957  for the `proxyReq.setHeader`  and `ERR_HTTP_HEADERS_SENT` issue.
