### ISSUE TITLE
Error when receive 204 (No-content) response

### ISSUE THREAD

**Issue by TK95** [chimurai/http-proxy-middleware#69]
The app crashes when target server returns 204 (No-content) response.

Here is a console output:
[HPM] PROXY ERROR: HPE_INVALID_CONSTANT. localhost -> http://my-server/order-cancel

Also, i can itercept an error using onErrorHook, and if I type console.log(res) it equals 204.

**Comment by chimurai** [comment]
Hi @TK95 

Don't think this is a http-proxy-middleware issue.

A quick search for `HPE_INVALID_CONSTANT` on StackOverflow and on GitHub returned quite some hits.

http://stackoverflow.com/questions/25090231/getting-proxy-error-when-using-gulp-serve-when-api-returns-204-with-no-content/25090759#25090759

`204` response body should be empty; Perhaps your response does contain some data in it...

**Comment by chimurai** [comment]
@TK95 feel free to re-open this issue if you think it's a bug in this project.

**Comment by TK95** [comment]
@chimurai No, I think everything is ok with http-proxy-middleware. I tried other  proxy libs ang got same errors

**Comment by chimurai** [comment]
Please do share your answer in case you found the answer to the problem.
