### ISSUE TITLE
Type regression (express.Request -> http.IncomingMessage)

### ISSUE THREAD

**Issue by elado** [chimurai/http-proxy-middleware#692]
### Describe the feature you'd love to see

https://github.com/chimurai/http-proxy-middleware/pull/603 reworked some types, but changed 

```ts
// Request is extending express.Request
onProxyReq?(proxyReq: http.ClientRequest, req: Request, res: Response): void;
```

to
```ts
export type OnProxyReqCallback = (
  proxyReq: http.ClientRequest,
  req: http.IncomingMessage,
  res: http.ServerResponse,
  options: httpProxy.ServerOptions
) => void;
```

this changed `req: express.Request` to `req: http.IncomingMessage` which loses some properties like `secure`, `query` etc.

**Comment by bliles** [comment]
This is a problem for me as well.
