### ISSUE TITLE
Add an option to stop proxy and handle response manually

### ISSUE THREAD

**Issue by otakustay** [chimurai/http-proxy-middleware#704]
### Describe the feature you'd love to see

We are working with a "proxy and cache" feature, in which we'd like to proxy a request the first time it appears and cache the response, after then we immediately respond from cache and not to proxy it to target server

After some investigation we find no solution to stop request proxy by a custom function, even though we can handle response in `onProxyRes`, the proxy requests are always sent

We expect to see an `onBeforeProxy(req, res, next)` option to determine whether to forward to proxy or handle it manually

If this is acceptable, I'd like to create a PR for this

**Comment by chimurai** [comment]
Hi,

If you are working with express; middlewares can be chained in express.

In your case you can add a custom caching middleware in front of the proxy middleware to implement the behaviour you just described.

IMHO. This way you can keep middlewares simple and compose the behaviour you want for your application.

**Comment by otakustay** [comment]
Thanks for explanation, I'm doing exactly what you suggested by restrict our webpack's `proxy` config to a very limited set.

It's my mistake to thinking webpack's `proxy` config parsing as a part of `http-proxy-middleware`, it seems I should handle this in webpack or somewhere else.

**Comment by chimurai** [comment]
Think you could look at setting up your own middlewares and configure your own proxy+caching functionality.

https://webpack.js.org/configuration/dev-server/#devserversetupmiddlewares
