### ISSUE TITLE
Handler types are incorrectly coupled to express.js

### ISSUE THREAD

**Issue by cdaringe** [chimurai/http-proxy-middleware#719]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

TS compilation error occurs with compatible response & reply primitives.

I expect a type signature from `createProxyMiddleware` to yield: `(req: IncomingMessage, res: http.ServerResponse, next?: ...) => void`. However, the returned handler is _explicitly_ coupled to express: `(req: expresscore.Request, res: expresscore.Response)`, etc.

This is invalid.

When my server tries to then:

```ts
server.use((req, res, next) => myProxyMiddleware(req,res,next))`
```

i get a compilation error, because i'm using raw node interfaces (legit works!), but createProxyMiddleware _demands_ express.js handlers.

### Step-by-step reproduction instructions

```shell
TypeScript concern only

1. create a typescript project
2. install a non-express server, such as fastify & middie
3. try passing a `req: IncomingMessage` and `res: http.ServerResponse` into a `createProxyMiddleware(...)(req, res)`
4. observe compilation error
```

### Expected behavior (be clear and concise)

No compilation error

### How is http-proxy-middleware used in your project?

```shell
top level dependency
```

### What http-proxy-middleware configuration are you using?

```typescript
programmatic use.
```

### What OS/version and node/version are you seeing the problem?

```shell
n/a
```

### Additional context (optional)

n/a

**Comment by chimurai** [comment]
Hi, thanks for the report.

I'm aware of this issue.

Looking at ways to improve typing so `req` and `res` are not coupled to express. But also vice versa;  Shouldn't be hardcoded to `req: http.IncomingMessage`,  `res: http.ServerResponse`, you'll get the same issue for the express ecosystem.

For now you could try type the middleware with `as any`:

```js
const apiProxy = createProxyMiddleware(apiProxyOptions) as any;
```

(Similar issue with nextjs: https://github.com/chimurai/http-proxy-middleware/issues/713#issuecomment-1046028720)

**Comment by chimurai** [comment]
Express users will loose express specific request and response properties when node primitives are used. This would mean regression for express users.

Happy to see a good solution which'll work for different servers.

**Comment by chimurai** [comment]
Using TypeScript Generics with default values might a solution.

https://github.com/chimurai/http-proxy-middleware/blob/6b5d7a8611ba0b400b1ee2796dada72c90e882bb/src/types.ts#L17-L19

Default values for `req` and `res`
`req: http.IncomingMessage`
`res: http.ServerResponse`

If you need extended `req` and `res` from your favourite server, you can configure and use it.

**Comment by chimurai** [comment]
Fixed in https://github.com/chimurai/http-proxy-middleware/pull/730

Removal of `@types/express` will be investigated in separate PR
