### ISSUE TITLE
feature(pathRewrite): accept a function to rewrite paths

### ISSUE THREAD

**Issue by chimurai** [chimurai/http-proxy-middleware#73]
#### proxy middleware configuration
```javascript
var apiProxy = proxy('/api', {
   target:'http://www.example.org',
   changeOrigin:true,
   pathRewrite: function(path) {
       return path;  // return altered path.
   }
});
```

**Comment by cwei-bgl** [comment]
@chimurai, could you please to pass request object to pathRewrite function also? I have a requirement to custom path based on some query parameters in request.

Thanks, Cheng

**Comment by chimurai** [comment]
@cwei-bgl, can you create a new issue for this?

Would be nice if  you can include a code example if its usage.
