### ISSUE TITLE
POST body is not forwarded in the proxied request

### ISSUE THREAD

**Issue by giuseppepastore10** [chimurai/http-proxy-middleware#741]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

Hi, 
I'm developing a React application and I configured my setupProxy.js but it seems no body data is forwarded to the server in the proxied request. What could be the problem?

### Step-by-step reproduction instructions

```shell
...
```

### Expected behavior (be clear and concise)

Forward the request with the body to the target host

### How is http-proxy-middleware used in your project?

```shell
gymnasio-management-app@0.1.0 /*****/*****/*****/*****/*****/gymnasio-management-app
├── http-proxy-middleware@2.0.4
└─┬ react-scripts@5.0.0
  └─┬ webpack-dev-server@4.7.4
    └── http-proxy-middleware@2.0.4 deduped
```

### What http-proxy-middleware configuration are you using?

```typescript
const {createProxyMiddleware, fixRequestBody} = require('http-proxy-middleware');
const bodyParser = require('body-parser')

module.exports = function(app) {
 var restream = function(proxyReq, req, res, options) {
   if (req.body) {
       let bodyData = JSON.stringify(req.body);
       proxyReq.setHeader('Content-Type','application/json');
       proxyReq.setHeader('Content-Length', Buffer.byteLength(bodyData));
       proxyReq.write(bodyData)
       proxyReq.end();
   }
 }
 
 app.use(bodyParser.json());
 app.use(bodyParser.urlencoded());
 app.use(
   '/api/*',
   createProxyMiddleware({
     target: 'https://<domain>/',
     changeOrigin: true,
     pathRewrite: {
       '^/api/': '<path>'
     },
     logLevel:'debug',
     onProxyReq: restream,  
   })
 );  

};
```

### What OS/version and node/version are you seeing the problem?

```shell
macOS Big Sur v11.5.2
Node v16.13.2
```

**Comment by chimurai** [comment]
Did you try the `fixRequestBody` instead of your own `restream`?

```js
const { createProxyMiddleware, fixRequestBody } = require('http-proxy-middleware');

const proxy = createProxyMiddleware({
  /**
   * Fix bodyParser
   **/
  onProxyReq: fixRequestBody,
});
```

https://github.com/chimurai/http-proxy-middleware#intercept-and-manipulate-requests

**Comment by chimurai** [comment]
dupe #40
