### ISSUE TITLE
web page continuously load when    selfHandleResponse: true, used

### ISSUE THREAD

**Issue by ShanArosh2002** [chimurai/http-proxy-middleware#807]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

web page continuously load when    selfHandleResponse: true, used

### Step-by-step reproduction instructions

```shell
const express = require('express');
const morgan = require("morgan");
const { createProxyMiddleware , responseInterceptor } = require('http-proxy-middleware');

// Create Express Server
const app = express();
// Configuration
const PORT = 3000;
const HOST = "localhost";

const proxy = createProxyMiddleware({
  target: 'http://example.com',
  changeOrigin: true, // for vhosted sites

  /**
   * IMPORTANT: avoid res.end being called automatically
   **/
  selfHandleResponse: true, // res.end() will be called internally by responseInterceptor()

  /**
   * Intercept response and replace 'Hello' with 'Teapot' with 418 http response status code
   **/
  on: {
    proxyRes: responseInterceptor(async (responseBuffer, proxyRes, req, res) => {
      res.statusCode = 418; // set different response status code

      const response = responseBuffer.toString('utf8');
      return response.replace('Hello', 'Teapot');
    }),
  },
});

app.get('/', proxy)

// Start Proxy
app.listen(PORT, HOST, () => {
    console.log(`Starting Proxy at http://${HOST}:${PORT}`);
    
});
```

### Expected behavior (be clear and concise)

normally it loads when   selfHandleResponse: false, but to edit response i need it to be true

### How is http-proxy-middleware used in your project?

```shell
PS C:\Users\In-Motion\Desktop\netninja> npm ls http-proxy-middleware
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
netninja@1.0.0 C:\Users\In-Motion\Desktop\netninja
└── http-proxy-middleware@2.0.6
```

### What http-proxy-middleware configuration are you using?

```typescript
{
  "dependencies": {
    "express": "^4.18.1",
    "http-proxy": "^1.18.1",
    "http-proxy-middleware": "^2.0.6",
    "morgan": "^1.10.0",
    "url": "^0.11.0"
  },
```

### What OS/version and node/version are you seeing the problem?

```shell
Windows 10 64 bit
```

**Comment by chimurai** [comment]
You were looking at v3 documentation and examples.

```js
// v3
on: {
    proxyRes: ...
}
```

```js
v2
onProxyRes: ...
```

You can find the older v2 documentation here:
https://github.com/chimurai/http-proxy-middleware/tree/2.x#intercept-and-manipulate-responses

**Comment by ShanArosh2002** [comment]
Thanks for your response. Thanks for this repo

**Comment by bangank36** [comment]
@chimurai I was setting up the middleware for firebase functions and got stuck with exactly same issue. Thanks for your response!

**Comment by morzel85** [comment]
I stumbled on this issue just today, so be aware that v3 is still in beta and normal `npm install http-proxy-middleware` will give you v2. Do `npm install http-proxy-middleware@beta` instead.
