### ISSUE TITLE
405 not Allowed error on POST call with gulp proxy

### ISSUE THREAD

**Issue by yobre** [chimurai/http-proxy-middleware#81]
### Expected behavior

POST call currectly redirect to proxy port 9000

### Actual behavior
redirect errror : 405 (Method Not Allowed)

### Setup

* http-proxy-middleware: 0.15.0
* server: _connect/express/browser-sync..._ + "express": "^4.13.4"
* other relevant modules

#### Gulp task
```javascript
gulp.task('connect', ['styles'], function() {

  var serveStatic = require('serve-static');
  var serveIndex = require('serve-index');
  var app = require('connect')()
    .use(require('connect-livereload')({port: 35729}))
    .use(serveStatic('.tmp'))
    .use(serveStatic('app'))
    // paths to bower_components should be relative to the current file
    // e.g. in app/index.html you should use ../bower_components
    .use('/bower_components', serveStatic('bower_components'))
    .use(serveIndex('app'))
    .use(require('express')());

  //////////////// PROXY START ////////////////

  // https://github.com/chimurai/http-proxy-middleware#context-matching
  var proxy = require('http-proxy-middleware');
  var options = {
    target: 'http://localhost:9000',
    changeOrigin: true
  };
  app.use('/api', proxy(options));

  //////////////// PROXY END ////////////////

  require('http').createServer(app)
    .listen(8000)
    .on('listening', function() {
      console.log('Started connect web server on http://localhost:8000');
    });
});
```

Stackoverflow answer: http://stackoverflow.com/questions/37302712/405-not-allowed-error-on-post-call-with-gulp-proxy

**Comment by chimurai** [comment]
I've made a minimal example for `connect`:
https://github.com/chimurai/http-proxy-middleware/blob/master/examples/connect/index.js

Try moving the proxy up, instead of configuring as the last middleware.

Not really sure what this is doing: `.use(require('express')());`

**Comment by yobre** [comment]
Thank you for your clean example @chimurai, i removed require('express')() (not really sure about it too) but nothing changed, then i also removed serveIndex('app') and everithing seem to work fine now. 
maybe there was some conflict with serveStatic('app').
