### ISSUE TITLE
logLevel:'debug'  does not take effect in vue-cli5

### ISSUE THREAD

**Issue by li-2021** [chimurai/http-proxy-middleware#814]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

In the Vue project created by vue-cli5, I configured the proxy's loglevel: 'debug', but it did not print any logs on the console.Proxy is actually in effect.
I try to print in the source code.It can print.However, this.logger.debug method does not print.
```javascript
this.prepareProxyRequest = async (req) => {
            // https://github.com/chimurai/http-proxy-middleware/issues/17
            // https://github.com/chimurai/http-proxy-middleware/issues/94
            req.url = req.originalUrl || req.url;
            // store uri before it gets rewritten for logging
            const originalPath = req.url;
            const newProxyOptions = Object.assign({}, this.proxyOptions);
            // Apply in order:
            // 1. option.router
            // 2. option.pathRewrite
            await this.applyRouter(req, newProxyOptions);
            await this.applyPathRewrite(req, this.pathRewriter);
            // debug logging for both http(s) and websockets
            if (this.proxyOptions.logLevel === 'debug') {
                const arrow = (0, logger_1.getArrow)(originalPath, req.url, this.proxyOptions.target, newProxyOptions.target);
                console.log('[HPM] %s %s %s %s', req.method, originalPath, arrow, newProxyOptions.target);
                this.logger.debug('[HPM] %s %s %s %s', req.method, originalPath, arrow, newProxyOptions.target);
            }
            return newProxyOptions;
        };
```

### Step-by-step reproduction instructions

```shell
1. Configure agent in vue-cli5 project logLevel: 'debug'
2. Start project and request interface
```

### Expected behavior (be clear and concise)

When I configure loglevel: 'debug', I should print the relevant logs on the console when I call the interface through inversion.
```javascript
  devServer: {
    https: false,
    proxy: {
      '/container-api': {
        target: 'http://***.***.***.204:30080',
        pathRewrite: { '^/container-api': '' },
        changeOrigin: true,
        logLevel: 'debug'
      },
    }
  },
```

### How is http-proxy-middleware used in your project?

```shell
Configure the proxy directly in the Vue project created by vue-cli5
```

### What http-proxy-middleware configuration are you using?

```javascript
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  devServer: {
    https: false,
    proxy: {
      '/container-api': {
        target: 'http://***.***.***.204:30080',
        pathRewrite: { '^/container-api': '' },
        changeOrigin: true,
        logLevel: 'debug'
      },
    }
  },
})
```

### What OS/version and node/version are you seeing the problem?

```shell
chrome. windows 10 and Node 16.8.0
```

**Comment by chimurai** [comment]
`console.debug` is only visible with node `--inspect`

Explained in: https://stackoverflow.com/a/47147123/3841188

Logging has been improved in v3 (still in beta) of http-proxy-middleware. And will only use `info`, `warn` and `error` for better compatibility: https://github.com/chimurai/http-proxy-middleware/blob/master/src/logger.ts

**Comment by chimurai** [comment]
Closing stale issue.
Feel free to re-open.
