### ISSUE TITLE
proxyReq not available any more

### ISSUE THREAD

**Issue by dirk-ecker** [chimurai/http-proxy-middleware#824]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

The description should be adjusted to the actual implementation. The event section seems to be wrong.
on is not the root, now each event gets an on as a prefix for its name, like onProxyReq.

### Step-by-step reproduction instructions

```shell
nothing to say here
```

### Expected behavior (be clear and concise)

correct description

### How is http-proxy-middleware used in your project?

```shell
as a middleware
```

### What http-proxy-middleware configuration are you using?

```typescript
not relevant
```

### What OS/version and node/version are you seeing the problem?

```shell
not relevant
```

**Comment by chimurai** [comment]
If you are looking at the github documentation you should see this:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/655241/189127021-824f1b31-6843-4a9e-9872-793eeb9ca008.png">

On github master you'll see documentation of the 3.0-beta version.

Guess in your setup you are still using v2.x?

**Comment by dirk-ecker** [comment]
Yes you are right, sorry for the issue.
