### ISSUE TITLE
Delay request/response

### ISSUE THREAD

**Issue by klimashkin** [chimurai/http-proxy-middleware#83]
Hi!
Would be great to have ability to delay request to backend server or response to client in `onProxyReq` or `onProxyRes` hooks respectively. I think this can be done by returning promise from this hooks (just proposal)
This is needed sometimes to emulate long backend response for some concrete url, not for all of them (this can be done with devtools network throttling).

Thank you!

**Comment by chimurai** [comment]
Hi @klimashkin,

Been thinking about this feature too...

Decided not to implement this for the various reasons:

- Simulating network conditions properly is tough and is beyond the scope of this middleware.
- Adds complexity to project 
- Other tools allow you to simulate network conditions; for example [Chrome Dev Tools](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en).

If you still want to delay (certain) requests, you can do it quite easily by chaining middlewares:

```javascript
var exampleProxy = proxy({
    target: 'http://www.example.com',
    changeOrigin: true
});

var delay = function (req, res, next) {
    console.log('[debug] Delaying %s for %sms ', req.originalUrl, 10000);
    setTimeout(next, 10000);
};

app.use('/api', delay, exampleProxy);
```

**Comment by klimashkin** [comment]
Ok, thank you, @chimurai !
That way with additional handler before proxy handler works great towards proxy, for requests.
But is there a way to delay response from proxy to client?

**Comment by chimurai** [comment]
Not sure how to delay responses. But do share the answer if you manage to find out how.

**Comment by klimashkin** [comment]
Wrapping `end` for its postponement solves the problem for me. Example to delay both request and response by 5 seconds each

```
var delay = function (req, res, next) {
    // Delay request 
    setTimeout(next, 5000);
   
    // Delay response end
    const endOriginal = res.end;
    res.end = function (...args) {
        setTimeout(function () {
          endOriginal.apply(res, args);
        }, 5000);
    };
};
app.use('/api', delay, exampleProxy);
```
<img width="424" alt="screen shot 2016-06-06 at 3 27 41 pm" src="https://cloud.githubusercontent.com/assets/576077/15839924/49ebe256-2bfb-11e6-8591-ef0101670885.png">

**Comment by chimurai** [comment]
Awesome! Thanks for sharing the answer.

Think it would make an excellent candidate for a delay/latency recipe.

Do you mind creating a PR of the snippet and add it to the http-proxy-middleware recipes?
https://github.com/chimurai/http-proxy-middleware/tree/master/recipes

All credits are yours of course.
