### ISSUE TITLE
pathFilter is not valid according to the TS files

### ISSUE THREAD

**Issue by jcollum-nutrien** [chimurai/http-proxy-middleware#839]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

In the docs: 

```
createProxyMiddleware({ pathFilter: ['/api', '/ajax', '/someotherpath'], ...})
```

In my code: 

```
app.use(
  '/hub-gql-proxy',
  createProxyMiddleware({
    target: 'https://redacted/',
    changeOrigin: true,
    pathFilter: ['/?GQLoperationName=redacted'],
  })
);

```

Result? TS error: 

![image](https://user-images.githubusercontent.com/99687439/196237717-a6b7ba56-9cef-47b6-be82-5dac78ee883e.png)

The TS binding doesn't have `pathFilter` in `Options` type. 

```
export interface Options extends httpProxy.ServerOptions {
    pathRewrite?: {
        [regexp: string]: string;
    } | ((path: string, req: Request) => string) | ((path: string, req: Request) => Promise<string>);
    router?: {
        [hostOrPath: string]: httpProxy.ServerOptions['target'];
    } | ((req: Request) => httpProxy.ServerOptions['target']) | ((req: Request) => Promise<httpProxy.ServerOptions['target']>);
    logLevel?: 'debug' | 'info' | 'warn' | 'error' | 'silent';
    logProvider?: LogProviderCallback;
    onError?: OnErrorCallback;
    onProxyRes?: OnProxyResCallback;
    onProxyReq?: OnProxyReqCallback;
    onProxyReqWs?: OnProxyReqWsCallback;
    onOpen?: OnOpenCallback;
    onClose?: OnCloseCallback;
}
```

Outdated docs? 

### Step-by-step reproduction instructions

```shell
1. I think this is covered above
2. ...
```

### Expected behavior (be clear and concise)

Docs or TS bindings are accurate. 

### How is http-proxy-middleware used in your project?

```shell
info This module exists because it's specified in "dependencies".
```

```json
  "dependencies": {
    "@types/node": "17.0.12",
    "eslint": "8.24.0",
    "express": "4.18.2",
    "http-proxy-middleware": "2.0.6"
  },
```

### What http-proxy-middleware configuration are you using?

see above

### What OS/version and node/version are you seeing the problem?

```shell
package 2.0.6

`envinfo` won't run, appears to have a bug. It worked a few weeks ago.
```

**Comment by chimurai** [comment]
Looks like you are using v2.x.  ([v2 docs](https://github.com/chimurai/http-proxy-middleware/tree/v2.0.4#readme))

On github master you'll see documentation of the 3.0-beta version.

If you are looking at the github documentation you should see this:

<img width="667" alt="image" src="https://user-images.githubusercontent.com/655241/189127021-824f1b31-6843-4a9e-9872-793eeb9ca008.png">

**Comment by jcollum-nutrien** [comment]
Is the TS that's published to NPM out of sync with the code that's published to NPM? 

If the 3.0 version works better I'll use that. I typically avoid beta software.

**Comment by jcollum-nutrien** [comment]
OK I get it, the docs aren't in sync with the published NPM version.

**Comment by chimurai** [comment]
Sorry for the confusion in the documentation on npm and github.
Should clear up when v3 is finalised.
