### ISSUE TITLE
webpack-dev-server config proxyTable -logLevel：‘debug’ ,can not work

### ISSUE THREAD

**Issue by yxw9527** [chimurai/http-proxy-middleware#859]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

function getInstance() {
    if (!loggerInstance) {
        loggerInstance = new Logger();
    }
    return loggerInstance;
}

  // log will log messages, regardless of logLevels
    log() {
        this.provider.log(this._interpolate.apply(null, arguments));
    }
    debug() {
        if (this._showLevel('debug')) {
            this.provider.debug(this._interpolate.apply(null, arguments));
        }
    }
    info() {
        if (this._showLevel('info')) {
            this.provider.info(this._interpolate.apply(null, arguments));
        }
    }
    warn() {
        if (this._showLevel('warn')) {
            this.provider.warn(this._interpolate.apply(null, arguments));
        }
    }

const logger = (0, logger_1.getInstance)();
 for (const rule of rulesCache) {
            if (rule.regex.test(path)) {
                result = result.replace(rule.regex, rule.value);
                logger.debug('[HPM] Rewriting path from "%s" to "%s"', path, result);
                break;
            }
        }

### Step-by-step reproduction instructions

```shell
1. ...
2. ...
```

### Expected behavior (be clear and concise)

please update this bug and fix it:logger.provider.debug/info/log...

### How is http-proxy-middleware used in your project?

```shell
for webpack
```

### What http-proxy-middleware configuration are you using?

```typescript
logger.getInstance
```

### What OS/version and node/version are you seeing the problem?

```shell
node 12.22.0
window 10
```

**Comment by chimurai** [comment]
not clear what the problem is.

feel free to reopen when a reproducible example can be provided
