### ISSUE TITLE
Add documentation for http proxy middleware in API Routes Nextjs

### ISSUE THREAD

**Issue by phatify** [chimurai/http-proxy-middleware#863]
### Describe the feature you'd love to see

Add documentation for http proxy middleware in API Routes Nextjs

**Comment by justin-together** [comment]
I've found the examples provided elsewhere don't work correctly on the first request.  The first request triggers .on('upgrade') registration, causing subsequent requests to succeed. But the first request hangs indefinitely.

**Comment by chimurai** [comment]
@justin-together could you give concrete urls to the examples you are referring to?

Here you can find a Next.js recipe:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/servers.md#nextjs
