### ISSUE TITLE
Im unable to use Proxy with Google Cloud Functions

### ISSUE THREAD

**Issue by Costiss** [chimurai/http-proxy-middleware#868]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

Iim triyng to use and express server as API Gateway, with Google Cloud Functions

Im running locally with @google-cloud/functions framework. On Cloud the behavior is the same
https://cloud.google.com/functions/docs/running/function-frameworks?hl=pt-br

The request lasts forever. After timeout, I get this error on target server
![image](https://user-images.githubusercontent.com/41318271/214895035-3229fd56-d8bd-47de-b531-091b962c300c.png)

On Gateway server it justs timeout
![image](https://user-images.githubusercontent.com/41318271/214896468-f76aa66b-7459-44d0-854b-230bd4d22d46.png)

### Step-by-step reproduction instructions

```shell
1. Create a express server with createProxyMiddleware
2. run with function-framework
3. try to make a request
```

### Expected behavior (be clear and concise)

Excpected same behavior as runing withou serverless

### How is http-proxy-middleware used in your project?

```shell
http-proxy-middleware@2.0.6
```

### What http-proxy-middleware configuration are you using?

```typescript
createProxyMiddleware(PROXY_PATH, {
    target: TARGET_URL,
    changeOrigin: true,
    pathRewrite: { [PROXY_PATH]: `/api/v1/` },
    secure: false
  })
```

### What OS/version and node/version are you seeing the problem?

```shell
PopOs 22.04LTS && NodeJs v18.13.0
```

**Comment by chimurai** [comment]
Could you try to run your application with Node v14 and see if you have the same issue?
