### ISSUE TITLE
lite server config not working

### ISSUE THREAD

**Issue by MadUser** [chimurai/http-proxy-middleware#88]
this is my bs-config.js.
```javascript
var proxy = require('http-proxy-middleware');

var apiProxy = proxy('/api', {
	target: 'localhost:8444',
	changeOrigin: true   // for vhosted sites
});

module.exports = {
	server: {
		middleware: {
			1: apiProxy
		}
	}
};
```
the default page is loading fine,
but when I set my url to: http://localhost:3000/my-route2
I get 404 from the server.

the angular router doesn't even get the request.

these are my dependencies:
```
"lite-server": "^2.2.2",
"connect-history-api-fallback": "^1.2.0",
"http-proxy-middleware": "^0.16.0",

"dependencies": {
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.3",
    "@angular/forms": "^0.1.1",
    "angular2-in-memory-web-api": "0.0.11",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  }

```

**Comment by chimurai** [comment]
Think the missing protocol in your proxy `target` is the issue.

Try:
```javascript
target: 'http://localhost:8444'
```

**Comment by MadUser** [comment]
No, still 404 :(

**Comment by chimurai** [comment]
Don't think this a library issue.

The scarse information you're providing is not really helpful...

* Make sure the server `http://localhost:8444/api` is running and accessible.

* Provide detailed logging when you add the proxy config `logLevel: debug`

**Comment by MadUser** [comment]
Sorry, I added the dependencies to the first post.
after setting the logLevel I see this error line at the console:

> (index):34 GET http://localhost:3000/browser-sync/browser-sync-client.2.12.12.js 

the server is up but I never really call him (yet)
Thank you.

**Comment by MadUser** [comment]
ok, I found the broblem.
in my npm scripts I have: 
` "lite": "lite-server --entry-file=index.html",`

The bs-config script overrun this configuration param.
I had to add a fallback to solve my problem:

```
var proxy = require('http-proxy-middleware');

module.exports = {
	server: {
		middleware: {
			1: proxy('/forecasts', {
				target: 'http://api.aerisapi.com/forecasts/',
				changeOrigin: true   // for vhosted sites, changes host header to match to target's host
			}),
			2: require('connect-history-api-fallback')({index: '/index.html', verbose: true})
		}
	}
};
```

Thanks chimurai for the help.

**Comment by chimurai** [comment]
Glad to hear you got it sorted.
