### ISSUE TITLE
[HPM] PROXY ERROR: ETIMEDOUT

### ISSUE THREAD

**Issue by raDiesle** [chimurai/http-proxy-middleware#89]
I tried many combinations to have it running with gulp,

but I am getting

[HPM] PROXY ERROR: ETIMEDOUT. localhost:3000 -> https://int-dev.company.com/etc/designs/danube/i18n.json?module=core&lang=en-us

it might be because of our company proxy.

Can you give advice how to debug and how to simulate call ( node-client?) to check if it is http-proxy-middleware or some npm module causing the issue?

**Comment by chimurai** [comment]
Hi @raDiesle,

If you think it's your company proxy, you can try this recipe:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/corporate-proxy.md

For further assistance, please use StackOverflow. I think that would be a better place to troubleshoot your setup.

Thanks.
