### ISSUE TITLE
Modifying the POST body in onProxyReq

### ISSUE THREAD

**Issue by dvmorris** [chimurai/http-proxy-middleware#90]
Following this recipe: https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/modify-post.md, I expect to be able conditionally modify the POST body based on the proxy path. The encodeURIComponent portion of this script only works with objects that are one level deep. 

How do I make this work with any object, no matter how many levels deep it might go, or just bypass the onProxyReq method entirely for other URL's I don't care about?
### Setup
- body-parser: 1.15.1
- http-proxy-middleware: 0.15.2
- express: 4.13.4
#### proxy middleware configuration

``` javascript
const apiProxy = proxyMiddleware('/services', {
  target: config.serverUrl,
  changeOrigin: true,
  pathRewrite: {
    '^/services': ''
  },
  onProxyReq: // just like the recipe linked above, but with a conditional check on proxy path
```
#### server mounting

``` javascript
const app = express();
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.use(apiProxy);
app.listen(3000);
```

**Comment by chimurai** [comment]
Don't have to answer to your question unfortunately...

The recipe originated from this issue: #61 

Can you post this question on StackOverflow with a backlinks between github <-> stackoverflow? In case someone runs into the same issue.

Thanks!

**Comment by yogeshlonkar** [comment]
Body parser is causing issue. In my case I removed these and proxy worked fine
```
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
```
You can use individual routes with bodyParser

```
app.post('/xyz', bodyParser.json(), function (req, res) {
    // use req.body
});
```
