### ISSUE TITLE
Modify Response

### ISSUE THREAD

**Issue by outrunthewolf** [chimurai/http-proxy-middleware#91]
I would like to modify the body of the response as it comes back through the system. Is this possible?

i.e.

```
client request --> connect --> proxy --> remote server
remote server response --> proxy --> MODIFY JSON DATA --> connect --> client
```

**Comment by chimurai** [comment]
I don't have the answer unfortunately.

Happy to add this one to the [http-proxy-middleware recipes](https://github.com/chimurai/http-proxy-middleware/tree/master/recipes).

Can you post this question on StackOverflow? Hopefully your question will get an answer there.

Thanks!

**Comment by outrunthewolf** [comment]
Thanks for responding. In reality I don't think its possible, or if it is possible it breaks the flow of this package. As such i'm closing.
