### ISSUE TITLE
Unable to output console.log and my plugin is not running

### ISSUE THREAD

**Issue by proc07** [chimurai/http-proxy-middleware#914]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

I can make a proxy request, but I can't execute my plug-in.

consle.log can output start without using the createProxyMiddleware function
<img width="1304" alt="截屏2023-05-10 下午4 45 18" src="https://github.com/chimurai/http-proxy-middleware/assets/16809535/344bf2d7-90c0-47c0-a83c-1cb3fd606962">

otherwise，Used, no output
<img width="1182" alt="截屏2023-05-10 下午4 56 53" src="https://github.com/chimurai/http-proxy-middleware/assets/16809535/5e092689-6053-470f-9885-ec77469c42ad">

### Step-by-step reproduction instructions

```shell
1. ...
2. ...
```

### Expected behavior (be clear and concise)

Can execute: console.log('start') console.log(proxyRes.headers["content-encoding"])  and my plunin

### How is http-proxy-middleware used in your project?

```shell
react-project@0.1.0 /Users/*******/Desktop/*******/examples/react-project
├── http-proxy-middleware@2.0.6 -> ./../../node_modules/.pnpm/http-proxy-middleware@2.0.6/node_modules/http-proxy-middleware
└─┬ react-scripts@3.4.4 -> ./../../node_modules/.pnpm/react-scripts@3.4.4_i2aqsaw42spuvzlb62z57gs7x4/node_modules/react-scripts
  ├─┬ mini-css-extract-plugin@0.9.0 -> ./../../node_modules/.pnpm/mini-css-extract-plugin@0.9.0_webpack@4.42.0/node_modules/mini-css-extract-plugin
  │ └─┬ webpack-dev-server@3.11.0 -> ./../../node_modules/.pnpm/webpack-dev-server@3.11.0_webpack@4.42.0/node_modules/webpack-dev-server
  │   └── http-proxy-middleware@0.19.1 deduped -> ./../../node_modules/.pnpm/http-proxy-middleware@0.19.1_tmpgdztspuwvsxzgjkhoqk7duq/node_modules/http-proxy-middleware
  └─┬ webpack-dev-server@3.11.0 -> ./../../node_modules/.pnpm/webpack-dev-server@3.11.0_webpack@4.42.0/node_modules/webpack-dev-server
    └── http-proxy-middleware@0.19.1 -> ./../../node_modules/.pnpm/http-proxy-middleware@0.19.1_tmpgdztspuwvsxzgjkhoqk7duq/node_modules/http-proxy-middleware
```

### What http-proxy-middleware configuration are you using?

```typescript
const path = require('path')
const {createProxyMiddleware} = require('http-proxy-middleware')
const {createRuntimeGeneratedType} = require('../../../dist/index.cjs');

const runtimeGeneratedTypePlugin = createRuntimeGeneratedType({
  dataSource: '',
  outputPath: path.resolve(__dirname, './src/types.ts'),
  baseUrl: '/api/*',
})

module.exports = function(app) {
  console.log('start')
  app.use(
    createProxyMiddleware('/api',{
      logger: console,
      logLevel: 'debug',
      target: 'http://jsonplaceholder.typicode.com',
      changeOrigin: true,
      pathRewrite: {'^/api' : ''},
      plugins: [runtimeGeneratedTypePlugin],
      on: {
        proxyRes: (proxyRes, req, res) => {
          console.log(proxyRes.headers["content-encoding"])
        },
      }
    })›
  );
};
```

### What OS/version and node/version are you seeing the problem?

```shell
macos: 11.6.1
node: v18.15.0
```

**Comment by chimurai** [comment]
I see you have v2.0.6 installed.

Plugins are available in the beta version of v3.

You can install it with:

```
npm install http-proxy-middleware@beta

or

yarn add http-proxy-middleware@beta
```

**Comment by proc07** [comment]
start
[HPM] Missing "target" option. Example: {target: "http://www.example.org"}

<img width="708" alt="截屏2023-05-11 下午3 56 49" src="https://github.com/chimurai/http-proxy-middleware/assets/16809535/141a438e-e0f2-4ffa-b1b9-5e883e2483fc">

i've already set it up target: 'http://jsonplaceholder.typicode.com', @chimurai

**Comment by proc07** [comment]
> I see you have v2.0.6 installed.
> 
> Plugins are available in the beta version of v3.
> 
> You can install it with:
> 
> ```
> npm install http-proxy-middleware@beta
> 
> or
> 
> yarn add http-proxy-middleware@beta
> ```

i used 2.0.6 version，delete plugin code，but following code is not executed either, printing log
```
on: {
        proxyRes: (proxyRes, req, res) => {
          console.log(proxyRes.headers["content-encoding"])
        },
      }
```

**Comment by proc07** [comment]
solved https://github.com/chimurai/http-proxy-middleware/blob/master/MIGRATION.md#removed-context-argument
