### ISSUE TITLE
How to setup multiple proxies?

### ISSUE THREAD

**Issue by hornetnz** [chimurai/http-proxy-middleware#92]
So we have a working proxy that redirects local api requests to our dev public api:

```javascript
server.middleware = proxyMiddleware('http://localhost:3000/platform/api/v2', {
        target: 'https://public-api.domain.com',
        headers: { host: 'public-api.domain.com' },
        pathRewrite: {
            '^/platform/api/v2': '/api/v2'
        }
    });
```

However we now need another proxy for one specific api call that needs to goto another api server (ie: https://public-api.domain2.com). I'v searched around and tried different ideas, but nothing seems to work. How can this be done?

**Comment by chimurai** [comment]
Can think of 2 ways to do it.

**# 1**
Create 2 seperate proxies; Use [context-matching](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md) to include or exclude certain paths.

You can use glob patterns or a custom function in context matching.

```javascript
server.middleware = [proxyMiddleware(/*... config1 ...*/), proxyMiddleware(/*... config2 ...*/)]
```

**# 2**
Create a single proxy and use the [`router`](https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/router.md) option to route a specific request to a different `target`

**Comment by chimurai** [comment]
No response... closing issue.
Feel free to re-open.

**Comment by BiosBoy** [comment]
Hi there! 

I faced the same issue while creating a multi-routing configuration. 

In my case, I was tried to handle that by:
```
const { createProxyMiddleware } = require('http-proxy-middleware')
const { __PATH__, __CHAT_PATH__ } = require('../globals/js/environments'

const commonProxyMiddleware = createProxyMiddleware(
 '/js/**',
  {
    target: __DEV_PATH__,
    changeOrigin: true,
    auth: 'staff:Zuff3qaMvlZlGtZT6',
    ws: true,
    secure: true,
    cookieDomainRewrite: 'localhost',
    headers: {
      origin: __DEV_PATH__,
      Connection: 'keep-alive',
      'Access-Control-Allow-Origin': '*'
    },
    onProxyRes: proxyRes => {
      // it's a hack for activating ServiceWorkers while local developing is going on
      if (proxyRes.req.path.match(/(sw\.js)$/i)) {
        proxyRes.headers['Service-Worker-Allowed'] = '/'
      }
    }
  }
)

const chatProxyMiddleware = createProxyMiddleware(
  '**',
  {
    target: __CHAT_PATH__,
    changeOrigin: true,
    ws: true,
    secure: true,
    cookieDomainRewrite: 'localhost',
    headers: {
      origin: __CHAT_PATH__,
      Connection: 'keep-alive',
      'Access-Control-Allow-Origin': '*'
    }
  }
)

module.exports = [commonProxyMiddleware, chatProxyMiddleware]
```

...and by using such a configuration I'm still having problems with the second one. It just doesn't start. Even if I put some logging option there, it won't fire anyway. 

One interesting thing - if I switch `[commonProxyMiddleware, chatProxyMiddleware]` on `[chatProxyMiddleware, commonProxyMiddleware]`, then the chat middleware will work, and the main one isn't... 

Thant's all so pity.
