### ISSUE TITLE
changeOrigin: true will cause anchor link in html use the proxyed domain name

### ISSUE THREAD

**Issue by cnweibo** [chimurai/http-proxy-middleware#93]
### Actual behavior
when set the changeOrigin option to true, the proxy will transform request to the intended target server. Say: we want to access localhost:8080, the http-proxy-middleware will transform to http://somotherserver.com
That is ok. But in the html returned from sometherserver.com, all the anchor link changed also to http://somotherserver.com/relativeurl/xxx

This cause the issue: i can not click link in the response as localhost:8080/relativeurl/xxx

For the browser-sync proxy, that is not the case. All http request to localhost:8080/relativeurl/xxx will be proxied to http://somotherserver.com/relativeurl/xxx and return the page with link prefixed STILL WITH http://localhost:8080/relurlalso/yyy, instead of pointing to someotherserver.com

Can we do some configure to let this behaviour same as browser-sync??

thanks~!

**Comment by chimurai** [comment]
`changeOrigin` option is provided by the [http-proxy](https://github.com/nodejitsu/node-http-proxy) library.

Suggesting to check [their issue tracker](https://github.com/nodejitsu/node-http-proxy/issues) for a solution. Or post your question on [StackOverflow](http://stackoverflow.com/).

You could try to setting the host header manually and hope it works...

```javascript
proxy('/relativeurl', {
  target: 'http://somotherserver.com',
  headers: {host:'http://somotherserver.com'}
});
```

**Comment by seanmart** [comment]
is there any update on this? I cannot figure out how to get around this
