### ISSUE TITLE
Doesn't seem to recognize non proxy routes (express)

### ISSUE THREAD

**Issue by newmanw** [chimurai/http-proxy-middleware#94]
### Expected behavior
When setting up an express router, routes not in proxy context are not recognized.  IE if filter function returns false, non proxy routes in sub application should be found.

### Actual behavior
404 for routes in sub application

### Setup

* http-proxy-middleware: 0.17.0
* server: express
* other relevant modules

#### proxy middleware configuration
```javascript
var filter = function (pathname, req) {
    return pathname.match(new RegExp('^/api'));
};
var apiProxy = proxy(filter, {target: 'http://www.example.org:8000'});
```

#### server mounting
```javascript
var sub = new express.Router();
sub.use(proxy);

// main app, mount the sub application
var app = express();
app.use('/sub', sub);
```

#### other route in sub application
```javascript
sub.get('/someroute',
   function(req, res, next) {
      // won't find route
   }
);
```

**Comment by chimurai** [comment]
In your filter function you are using a string instead of regex in the `match` function `pathname.match('^/api')`.
Think it should be: `pathname.match(/^\/api/)` or `pathname.match(new RegExp('^/api'))`

This piece of code is also weird:
`var proxy = proxy(filter, {});`

1. You are overriding the original proxy function... use a different variable name`var proxyExample = proxy(filter, {});`
2. `proxy(filter, {});` is missing the `target` value: proxy(filter, {target: 'http://example.org'});`

**Comment by newmanw** [comment]
@chimurai you are correct, I did not copy my example and made a few mistakes when typing it in.  Still having problems, if the filter function returns false, non proxy routes are not hit.

IE, in my example the sub app has a context of sub so if I hit 'http://myserver.com/sub/api', the proxy filter will return true and the request will be proxied.

However if I hit 'http://myserver.com/sub/someroute', the filter function returns false as it should, but the request does not go through to the subroute endpoint.

**Comment by chimurai** [comment]
@newmanw: Could be provide a minimal/small sample app; showing the problem you described? This will help me debug this issue.

**Comment by newmanw** [comment]
@chimurai absolutely, working on it now.

**Comment by chimurai** [comment]
@newmanw Thanks for providing the example.

**Comment by chimurai** [comment]
Hi @newmanw,
Think I've fixed the issue. Can you verify it?

Still need to write some tests for this use-case

**Comment by newmanw** [comment]
Works as I would expect.  Awesome turn around time, thanks so much!

**Comment by chimurai** [comment]
Just pushed v0.17.1 with the fix.

Thanks for reporting the issue and helping out with debugging. Greatly appreciated!
