### ISSUE TITLE
How do I make the proxy use SSL when running locally?

### ISSUE THREAD

**Issue by m90** [chimurai/http-proxy-middleware#95]
### Expected behavior

I'm trying to proxy an API my express app consumes client side in order to add JWT auth headers to all my requests. This works as expected. I specified a `https` URL and set the agent to the https `globalAgent` as per [this example](https://github.com/nodejitsu/node-http-proxy/blob/master/examples/http/proxy-http-to-https.js)

### Actual behavior

Outgoing requests made by the middleware are force downgraded to http.

### Setup

* http-proxy-middleware: 0.15.0
* server: express 4.13.1

FWIW the express application is running inside a Docker container.

#### proxy middleware configuration
```javascript
router.use(proxy({
	pathRewrite: {
		'^/api/': '/'
	}
	, logLevel: process.env.SILENT
		? 'silent'
		: process.env.NODE_ENV === 'production'
			? 'info'
			: 'debug'
	, changeOrigin: true
	, agent: https.globalAgent
	, target: `${process.env.API_BASEURL}/${process.env.API_VERSION}` //this is a https url
	, secure: process.env.NODE_ENV === 'production'
	, onProxyReq: (proxyReq, req) => {
		proxyReq.setHeader('Authorization', `JWT ${req.applicableJwt}`);
	}
}));
```

#### server mounting
```javascript
app.use('/api', ensureLoggedIn(), proxy);
```

Also logging output is ambiguous (notice the https in the second line as opposed to the following ones):

```
app_1   | [HPM] Rewriting path from "/api/users/2" to "/users/2"
app_1   | [HPM] GET /api/users/2 ~> https://my-api.com/v2
app_1   |       → GET http://my-api.com/v2/users/2
app_1   |   200 ← GET http://my-api.com/v2/users/2 173ms
```

**Comment by chimurai** [comment]
Try minimizing your setup to see if the problem still exists. (just the express server and the proxy middleware)

Also please provide the static values in your example configuration. No way I can tell what kind of values are actually being used...

**Comment by m90** [comment]
Turns out both the middleware as well as my setup work well, yet this: https://github.com/floatdrop/debug-http is logging incorrectly, so this is a non-issue.
