### ISSUE TITLE
Calls to `/uri/endpoint` reach target instead of `target/endpoint`

### ISSUE THREAD

**Issue by SylvainBigonneau** [chimurai/http-proxy-middleware#96]
### Expected behavior

Trying to proxy an api (located at `http://localhost:8080/api/rest`) with various endpoints ("/users", "/posts", etc) in a "/rest" route on my app located on `http://localhost:9000`. So to reach `http://localhost:8080/api/rest/users`, for example, I would just have to call `http://localhost:9000/rest/users`.

### Actual behavior

All calls to endpoints ("/rest/users", "/rest/posts", etc) always point to the root of my api, ergo `http://localhost:8080/api/rest`.

For example, if I try to reach `http://localhost:9000/rest/users`, the proxy points to `http://localhost:8080/api/rest` instead of `http://localhost:8080/api/rest/users`:
```
[HPM] GET /rest/users -> http://localhost:8080/api/rest
```

### Setup

* http-proxy-middleware: 0.17.0
* server: browser-sync 2.12.5

#### proxy middleware configuration
```javascript
var apiProxy = proxy('/rest', {
    target: 'http://localhost:8080/api/rest',
    changeOrigin: true,
    logLevel: 'debug'
  });
```
#### server mounting
```javascript
browserSync({
    open: false,
    port: 9000,
    server: {
      baseDir: ['target/tmp/'],
      middleware: [apiProxy]
    }
  }, done);
```

**Comment by chimurai** [comment]
You can use the `pathRewrite` option to modify the `path`; In your case, you're trying the add a "basePath" to all paths you are proxying...

It's documented here:
- https://github.com/chimurai/http-proxy-middleware#http-proxy-middleware-options
- https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/pathRewrite.md#add-paths

```javascript
var apiProxy = proxy('/rest', {
    target: 'http://localhost:8080',
    changeOrigin: true,
    pathRewrite: {
        '^/rest' : '/api/rest'   // <- add basePath '/api'
    },
    logLevel: 'debug'
  });
```

Calls ``

Hope this will solve your problem.

---

Just wondering about your example; How did you came/ended up with the `path` in the `target` configuration: `target: 'http://localhost:8080/api/rest'` ?

To my knowledge the `path` part is being ignored.

**Comment by SylvainBigonneau** [comment]
Thanks ! That worked perfectly indeed.

I now understand what I got wrong : `target` should always contain the host only, without any URI.

For your question, it may have been ignored. I was getting a blank page either way on `http://localhost:8080` or `http://localhost:8080/api/rest` so maybe I was hitting the former.
