### ISSUE TITLE
"Invalid context" error message is unhelpful when mixing paths with globs

### ISSUE THREAD

**Issue by mcFrax** [chimurai/http-proxy-middleware#964]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

This message:
```
ERR_CONTEXT_MATCHER_INVALID_ARRAY = '[HPM] Invalid pathFilter. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]',
```
doesn't explain that mixing globs and non-globs is prohibited. Although it shows one array with just non-glob paths and one with globs, it doesn't clarify that these are examples of 2 separate categories of pathFilters.

I had to find the answer by Googling the error message and _reading the code that produces it_.

### Step-by-step reproduction instructions

```javascript
createProxyMiddleware(['/api/**', '/foo'], {
    target: "https://httpbin.org",
    changeOrigin: true,
  })
```

→ https://codesandbox.io/p/devbox/http-proxy-middleware-forked-6ky4n8?file=%2Fsrc%2Findex.js%3A10%2C5

Error message:

```
[HPM] Invalid pathFilter. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]
<stack trace>
```

### Expected behavior (be clear and concise)

Error explaining that globs and paths cannot be mixed. Perhaps just this explanation added on top of the existing message.

```
[HPM] Invalid pathFilter. Expecting something like: ["/api", "/ajax"] or ["/api/**", "!**.html"]. Plain paths (e.g. "/api") can't be mixed with globs (e.g. "/api/**").
```

### How is http-proxy-middleware used in your project?

```shell
Indirectly, with Webpack's devServer.
```

### What http-proxy-middleware configuration are you using?

```typescript
[irrelevant]
```

### What OS/version and node/version are you seeing the problem?

```shell
[irrelevant]
```

### Additional context (optional)

The error is thrown [in this line](https://github.com/chimurai/http-proxy-middleware/blob/e4932b340603841e9ae3525f72db565b1fcdb0b7/src/path-filter.ts#L32).

The only cases handled for array are `pathFilter.every(isStringPath)` and `pathFilter.every(isGlobPath)`. `isStringPath` checks that the string is _not_ a glob - so for mixed paths and globs neither of the conditions will be fullfilled.

**Comment by chimurai** [comment]
Hi @mcFrax 

Thanks for suggestion. Sounds like a good improvement.

Could you create a PR with your suggestion to improve the error message?
