### ISSUE TITLE
Allow custom Http Method like LIST

### ISSUE THREAD

**Issue by Zetanova** [chimurai/http-proxy-middleware#975]
### Describe the feature you'd love to see

The proxy response with `400 Bad Request` with http request `LIST` 
I could not find any options to allow other http methods over the config.

Tried with the default webpack-dev-server provided with angular 17

**Comment by chimurai** [comment]
`LIST` is not a official HTTP request method, that's why you are getting a `400` response.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
https://datatracker.ietf.org/doc/html/rfc7231#section-4.3

**Comment by Zetanova** [comment]
The proxy is blocking the request and there is no option for configuration/allow custom http methods.

A direct connection to the [Vault API](https://developer.hashicorp.com/vault/api-docs) worked of course without issues.

**Comment by chimurai** [comment]
Think it's the dev server blocking the request. Not the proxy.

https://expressjs.com/en/api.html#routing-methods

### Workaround

https://developer.hashicorp.com/vault/api-docs
>The API documentation uses LIST as the HTTP verb, but you can still use GET with the ?list=true query string.
