### ISSUE TITLE
Removes port from target

### ISSUE THREAD

**Issue by Netail** [chimurai/http-proxy-middleware#985]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

When a target with a port is given, it gets proxied to the domain without port.
E.g. when using http://127.0.0.1:3001 as a target, it will proxy to http://127.0.0.1

### Step-by-step reproduction instructions

```shell
1. Set target to http://127.0.0.1:3001
2. Use the proxy 
3. Redirects to the url without the port
```

### Expected behavior (be clear and concise)

Go to the correct port

### How is http-proxy-middleware used in your project?

```shell
- "_project_#custom-proxy" depends on it
   - Hoisted from "_project_#custom-proxy#http-proxy-middleware"
```

### What http-proxy-middleware configuration are you using?

```typescript
3.0.0 - createProxyMiddleware()
```

### What OS/version and node/version are you seeing the problem?

```shell
MacOS 14.4.1 - Node v20.8.1
```

**Comment by chimurai** [comment]
Can you share your server + proxy configuration?
Even better if can provide a reproducible example

**Comment by max-holland** [comment]
I have the same issue basically my target url is http://localhost:4550, a backend I have running locally.

Using V2 the proxy is fine and works as expected -> [HPM] POST /api/test/search -> http://localhost:4550

Using V3 the port has been removed -> [HPM] POST /api/test/search -> http://localhost/api/test/search [401]

Unless i've missed some config somewhere then I apologies in advance :)

**Comment by Netail** [comment]
> Can you share your server + proxy configuration? Even better if can provide a reproducible example

Seems to be only the logging; https://codesandbox.io/p/devbox/gracious-lamport-jfds4x

**Comment by max-holland** [comment]
@Netail Yeah, looks like it is just the logging. Initially I thought I had an issue with the proxy but that seems to be working as intended.

**Comment by Netail** [comment]
It also automatically adds a trailing slash, to the target which could trigger an infinite loop when the web server has a redirect to the non-trailing slash path

**Comment by chimurai** [comment]
Thank for reporting and the reproduction.
Merged a fix.

---

Trailing slash is added by the `http-proxy` lib.
Should be fixed upstream.

**Comment by chimurai** [comment]
published fix in [3.0.1-beta.0](https://www.npmjs.com/package/http-proxy-middleware/v/3.0.1-beta.0)

**Comment by Netail** [comment]
> Thanks for reporting and the reproduction.
> Merged a fix.
> 
> ---
> 
> Trailing slash is added by the `http-proxy` lib.
> Should be fixed upstream.

Will you make a ticket there or shall I?

**Comment by chimurai** [comment]
Feel free to create a ticket 👍

**Comment by Netail** [comment]
> Feel free to create a ticket 👍

Mhm I doubt it will be picked up, they haven't updated that library for over 4 years now
