### ISSUE TITLE
How to proxy the root url?

### ISSUE THREAD

**Issue by SidKwok** [chimurai/http-proxy-middleware#99]
## Expected behavior
When I use api like `/get_tags`, it will help me proxy to `localhost:3000/get_tags`. But not all my requests such like `/`.

## Actual behavior
All of my requests are proxied to `localhost:3000` .

## Setup
* http-proxy-middleware: 0.12.0
* server: express 4.13.3

### proxy middleware configuration
```javascript
var proxyMiddleware = require('http-proxy-middleware')

var proxyTable = {
        '/': {
            target: 'localhost:3000',
            changeOrigin: true
        }
    };
Object.keys(proxyTable).forEach(function (context) {
  var options = proxyTable[context]
  if (typeof options === 'string') {
    options = { target: options }
  }
  app.use(proxyMiddleware(context, options))
})
```

**Comment by chimurai** [comment]
The scarse information you're providing is not really helpful.

Please follow the [CONTRIBUTING guidelines](https://github.com/chimurai/http-proxy-middleware/blob/master/CONTRIBUTING.md#report-issues) or use the [ISSUE template](https://github.com/chimurai/http-proxy-middleware/blob/master/ISSUE_TEMPLATE.md).

Thanks.

[_How to Ask Good Coding Questions That Get Great Answers..._](http://zellwk.com/blog/asking-questions/)

**Comment by SidKwok** [comment]
Sorry for missing the guidelines. I updated the issue, please noted.

**Comment by chimurai** [comment]
If you just want to proxy `/get_tags` to `http://localhost:3000`, configure it like:

```javascript
var proxyTable = {
  '/get_tags': {
    target: 'http://localhost:3000',    // <-- protocol must be included
    changeOrigin: true
  }
};
```

By using just `'/'` as context, your are basically saying: Proxy all requests to `http://localhost:3000`

You can find more infomation here on context matching:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/context-matching.md

**Comment by SidKwok** [comment]
ok, I get it.
