### ISSUE TITLE
How to reduce logger to only errors?

### ISSUE THREAD

**Issue by elawad** [chimurai/http-proxy-middleware#997]
### Checks

- [X] I understand project setup issues should be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/http-proxy-middleware) or in [GitHub Discussions](https://github.com/chimurai/http-proxy-middleware/discussions).
- [X] I updated to latest `http-proxy-middleware`.

### Describe the bug (be clear and concise)

Before v3 we could use `logLevel: 'error'` to only log errors.
With v3 we now use `logger: console` but this output lots of info logs.

What's the best way to filter only error logs, keeping HPM's log format?

### Step-by-step reproduction instructions

```shell
1. ...
2. ...
```

### Expected behavior (be clear and concise)

A way to reduce logs to only errors.

### How is http-proxy-middleware used in your project?

```shell
=> Found "http-proxy-middleware@3.0.0"
info Has been hoisted to "http-proxy-middleware"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "376KB"
info Disk size with unique dependencies: "896KB"
info Disk size with transitive dependencies: "2.21MB"
info Number of shared dependencies: 7
```

### What http-proxy-middleware configuration are you using?

```js
app.use('/api', createProxyMiddleware({
  target: 'https://example.com/api',
  changeOrigin: true,
  logger: console,
}));
```

### What OS/version and node/version are you seeing the problem?

```shell
MacOS 14.4.1 and Node 20.12.0
```

**Comment by elawad** [comment]
Is the solution to use the `on error` event?
https://github.com/chimurai/http-proxy-middleware/blob/32a5b233a1ba488083821cfd1c356deb56792d27/src/plugins/default/logger-plugin.ts#L22-L31

**Comment by chimurai** [comment]
You can use a logger library and set the log level there:
https://github.com/chimurai/http-proxy-middleware/blob/master/recipes/logger.md

Or create a custom logger object to only log errors:

```js
app.use('/api', createProxyMiddleware({
  target: 'https://example.com/api',
  changeOrigin: true,
  logger: {
    info: () => {},
    warn: () => {},
    error: console.error,
  },
}));
```

**Comment by elawad** [comment]
That's exactly what I wanted, thank you!
